### ISSUE TITLE
Issue installing Omnest 6.0.1 on Centos 7

### ISSUE THREAD

**Issue by peter-newman** [omnetpp/omnetpp#1001]
./configure runs successfully with the output shown below. make fails with the following output:

***** Configuration: MODE=release, TOOLCHAIN_NAME=gcc, SHARED_LIBS=yes, LIB_SUFFIX=.so ****
===== Checking environment =====
===== Compiling utils ====
===== Compiling common ====
make[2]: *** No rule to make target `/local/pnewman/omnest-6.0.1/out/gcc-release/src/common/lcgrandom.o', needed by `/local/pnewman/omnest-6.0.1/out/gcc-release/src/common/liboppcommon.so'.  Stop.

Any ideas?

--Peter

./configure
configure: Environment variables (PATH and PYTHONPATH) are correctly set.
configure: Reading configure.user for your custom settings.
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for icc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for icpc... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for g++... g++
checking for c++14 support... yes
checking for ranlib... ranlib
checking whether g++ supports -fno-omit-frame-pointer... yes
checking whether g++ supports -glldb... no
checking whether g++ supports -ggdb3... yes
checking whether g++ supports -fstandalone-debug... no
checking whether g++ supports -fno-limit-debug-info... no
checking whether g++ supports -Wl,--no-as-needed... yes
checking whether g++ supports -Wl,--as-needed... yes
checking for swapcontext... yes
checking if shared libs need -fPIC... yes
checking for dlopen with CFLAGS="" LIBS=""... no
checking if --export-dynamic linker option is supported/needed... test failed
checking for flags needed to link with static libs containing simple modules... --whole-archive
configure: NOTE: Use the following syntax when linking with static libraries
configure: containing simple modules and other dynamically registered components:
configure:    g++ ... -Wl,--whole-archive <libs> -Wl,--no-whole-archive ...
checking whether linker supports -rpath... yes
checking for bison... bison -y
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking for make... make
checking for perl... perl
checking for swig... swig
checking for python3... python3
checking if all necessary Python modules are available... yes
checking for math with CFLAGS=" -fPIC" LIBS=""... yes
checking for standard C++ lib with CFLAGS=" -fPIC" LIBS="-lstdc++"... yes
checking for dlopen with CFLAGS=" -fPIC" LIBS=""... no
checking for dlopen with CFLAGS=" -fPIC" LIBS="-ldl"... yes
checking for g++ option to support OpenMP... -fopenmp
checking for PTHREAD with CFLAGS=" -fPIC " LIBS="-lpthread"... yes
configure: creating ./config.status
config.status: creating Makefile.inc
config.status: creating src/qtenv/qtenv.pri

OMNEST was configured with $WITH_QTENV = no. The Qt-based graphical
runtime environment (Qtenv) will not be available.

Configuration phase finished. Use 'make' to build OMNEST.

**Comment by rhornig** [comment]
What version of `make` you have? The error complains about missing a rule for creating the `.o` file, but there is clearly a rule in the Makefile for this:

```
$O/%.o: %.cc $(GENERATED_SOURCES) $(CONFIGFILE) $(COPTS_FILE)
	@mkdir -p $O
	$(qecho) "$<"
	$(Q)$(CXX) -c $(CXXFLAGS) $(COPTS) $(EXPORT_DEFINES) $(IMPORT_DEFINES) -o $@ $<
```
check the src/common/Makefile. Maybe it is corrupted?

**Comment by rhornig** [comment]
After a bit of experimenting I was able to get it compile using devtools-10. The main issue is that you seem to have gnu make 3.8. OMNeT++ 6 required gnu make 4.2 so you have to install that too:

```
sudo yum install centos-release-scl
sudo yum install devtoolset-10-gcc* devtoolset-10-make*
scl enable devtoolset-10 bash
```
In that new dev-shell you should be able to build OMNeT++.

**Comment by peter-newman** [comment]
Thank you. That indeed fixes the problem. OMNET++6 has compiled successfully and I have the Eclipse GUI up and running.
