### ISSUE TITLE
run simulation doesn't work : nothing happens except never-ending signal exchanges

### ISSUE THREAD

**Issue by Caillassage** [omnetpp/omnetpp#1004]
**Platform**
 - OMNeT++ version: 6.0.1
 - OS: Ubuntu 22.04.2 LTS
 - INET version : 4.5

**Describe the bug**
When I launch a simulation with a `visualizer` component, it starts but the only thing that happens is an exchange of `PRE_MODEL_CHANGE` and `POST_MODEL_CHANGE` signals between `visualizer` and nodes (as you can see in the picture) :
![image](https://github.com/omnetpp/omnetpp/assets/136718480/0496fc2d-03f2-414d-80df-e22bd25fdaea)
Another strange thing, the simulation starts but the timer at the top of the screen stays at 0sec. The only way for me to make a simulation is to use the fast mode, but I can't see what happens.
Additionally, when I launch a simulation without the `visualizer` component, like `tictoc` tutorials for example, there are no message animations (the little red point traveling between nodes).

**To Reproduce**
1. Install OMNeT++ (I installed it from the [official website](https://omnetpp.org/))
2. Install dependencies
3. `source setenv`
4. `./configure`
5. `make`
6. execute inet4.5/tutorials/wireless/WirelessA.ned

**Comment by rhornig** [comment]
You may have turned off the message animation in the animation settings dialog. Press the gear icon in the toolbar and select the *Animations* tab and check the *Animate messages* option.

**Comment by Caillassage** [comment]
I have already checked these options, as you can see in the picture :
![image](https://github.com/omnetpp/omnetpp/assets/136718480/b50cfa2e-4e72-42b4-8356-83103772004b)
As I said in my last message, the main problem is the never-ending signal exchanges.

**Comment by rhornig** [comment]
The steps to reproduce are not clear:
- there is no `./configure` script in INET.
- how do you *execute* `inet4.5/tutorials/wireless/WirelessA.ned`. This is a NED file. not an executable file

**Comment by Caillassage** [comment]
I'm going to explain what I did with more clarity :

1. Install OMNeT++ directly from the [website](https://omnetpp.org/download/) 
![image](https://github.com/omnetpp/omnetpp/assets/136718480/9f9ffb41-bb6c-4adf-91da-ff158276dcb3)

2. Open a terminal, and go to `omnetpp-6.0.1` directory
3. `source setenv` to get the environment ready 
![Capture d’écran du 2023-07-06 09-43-25](https://github.com/omnetpp/omnetpp/assets/136718480/aa1b58e8-8ee2-4528-a6d9-64cdacc46d12)
4. Now you can configure the simulator with `./configure`. It will check if all dependencies are installed (like `clang`, `gcc`, python modules...). Afterwards this message appears 
![image](https://github.com/omnetpp/omnetpp/assets/136718480/3dbb4f09-24c5-4ed7-9b16-0cfe9177ff48)
5. Build OMNeT++ with `make`
6. Open IDE with `omnetpp` command
7. Finally, you can follow the on-screen instructions to install INET

After doing these, i launched `inet4.5/tutorials/wireless/WirelessA.ned` with the simulation button (it's what I meant when I said *execute*).
As you noticed, the screenshot I'm showing is not from the Wireless Tutorial. I copied it and modified the number of nodes, BUT even the original Wireless Tutorial has the same problem.
I turned off the *Animate Method call* option like you said, and the signal exchange stopped. Thanks for your help ! Now I just have to find a way to display message exchange (actually, I can't see messages traveling between nodes).
