### ISSUE TITLE
Reproducing the example in INET showcase.

### ISSUE THREAD

**Issue by ccsssyyy** [omnetpp/omnetpp#1006]
**Platform**
 - OMNeT++ version: 6.0 , Build ID 220413-71d8fab425
 - INET version: 4.4.0
 - OS: Windows 11 , VMware 16.1.0 build-17198959 , Ubuntu-20.04.4-desktop-amd64
 - Python version : 3.8

**Describe the bug**
Couldnt reproduce the example described at : https://inet.omnetpp.org/docs/showcases/tsn/timesynchronization/clockdrift/doc/index.html
Example: Constant Clock Drift Rate
I want to reproduce the example shown figure -- Clock drift - Constant drift rate, but failed.

**To Reproduce**
Run the showcase in INET -> showcases -> tsn -> timesynchronization -> clockdrift -> omnetpp.ini
Select : ConstantClockDriftRate -- Clocks with constant drift rate diverge over time. And use FAST RUN to speed up the process.
open ConstantClockDriftRate-#0.vec in results folder. Save the corresponding anf file.
Select Browse Data -> Vectors
Plot using Line Chart with all the three timeChanged:vector
Applying Linear Trend operation with argument -1 to reproduce the figure.
![1](https://github.com/omnetpp/omnetpp/assets/132052625/c0fa2c93-8509-4c11-9ca0-744462ade3d0)
![2](https://github.com/omnetpp/omnetpp/assets/132052625/7d2ed808-b1d7-4764-8f01-11babaabb3c7)

![3](https://github.com/omnetpp/omnetpp/assets/132052625/659a68de-acc1-47be-926a-ec335c7b274f)
![4](https://github.com/omnetpp/omnetpp/assets/132052625/37ee19ae-ecc7-44e9-a523-f5074aa249f7)

**Comment by rhornig** [comment]
This is INET related. Unfortunately, I cannot move the issue so please re-file it in the INET issue tracker, if it is still relevant.
