### ISSUE TITLE
cMsgPar::parsimPack() error

### ISSUE THREAD

**Issue by qh747** [omnetpp/omnetpp#1010]
**Platform**
 - OMNeT++ version: [5.6.2]
 - OS: [Windows 10]

**Describe the bug**
When I run the parallel simulation, I found that the message parameter of the char* type will report an error when it is packaged. I found that the reason is caused by the following code. The code is on line 228 of the cmsgpar.cc file

`buffer->pack(ls.str, sizeof(ls.str));`

![image](https://github.com/omnetpp/omnetpp/assets/69048822/b32fcf2f-ed55-4d5a-a5fe-5f4280c1d840)

The type of the parameter (ls.str) is char *, and the result obtained by calling the sizeof() function on the parameter of type char * is only 4 bytes, while the actual parameter has 10 bytes, so I cannot pack the actual data.

**Sloution**
I solved this problem by using strlen() function instead of sizeof() function.

`buffer->pack(ls.str, strlen(ls.str));`

**Comment by avarga** [comment]
Fixed. Thanks for reporting!
