### ISSUE TITLE
Simulation becomes slower over time due to cDatarateChannel::txList being filled with 10s of thousands of transmissions

### ISSUE THREAD

**Issue by levy** [omnetpp/omnetpp#1012]
**Platform**
 - OMNeT++ version: 6.0.1
 - OS: Ubuntu 22.04

**Describe the bug**
Run the simulation in express mode and observe the events per second measurement in Qtenv.

**To Reproduce**

network HubLAN4
{
    submodules:
        hostA: EthernetHost;
        hostB: EthernetHost;
        hostC: EthernetHost;
        hostD: EthernetHost;
        hub: EthernetHub {
            gates:
                ethg[4];
        }
    connections:
        hub.ethg[0] <--> {  delay = 1ns; datarate = 100Mbps; } <--> hostA.ethg;
        hub.ethg[1] <--> {  delay = 3ns; datarate = 100Mbps; } <--> hostB.ethg;
        hub.ethg[2] <--> {  delay = 4ns; datarate = 100Mbps; } <--> hostC.ethg;
        hub.ethg[3] <--> {  delay = 2ns; datarate = 100Mbps; } <--> hostD.ethg;
}

[General]
network = HubLAN4
**.eth.duplexMode = false
**.hostA.cli.destAddress = ""
**.cli.destAddress = "hostA"
**.cli.sendInterval = exponential(1s)
**.cli.startTime = 100ns
**.cli.reqLength = 10B
**.cli.respLength = 10B

**Comment by avarga** [comment]
Fixed in 860852b404 ("cDatarateChannel: fixed issue 1012: clear finished transmissions from txList", 2023-07-17)
