### ISSUE TITLE
Configure: error: Some Python modules required by the IDE were not found: omnetpp

### ISSUE THREAD

**Issue by Chenyu3194** [omnetpp/omnetpp#1017]
**Platform**
 - OMNeT++ version: [e.g. 6.0.1]
 - OS: Win 11

**Describe the bug**
Hi,

I ran into the appeared issue that Python modules missed so that I can not continue with the "$ make" step and therefore I can't open IDE.

**I checked the system variables** and I found the "PYTHONPATH" with a existed variable from SUMO "C:\Program Files (x86)\Eclipse\Sumo\tools\" which I would not change because I need SUMO of course, and I can't put an extra directory with "omnetpp/python" into it. I put the omnett folder into a directory without space in it. How can I fix this

**To Reproduce**
/d/Programm/omnetpp-6.0.1$ ./configure
configure: loading site script /etc/config.site
configure: Environment variables (PATH and PYTHONPATH) are correctly set.
configure: Reading configure.user for your custom settings.
checking build system type... x86_64-w64-mingw32
checking host system type... x86_64-w64-mingw32
checking for clang... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking for clang++... clang++
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking for clang++... clang++
checking for c++14 support... yes
checking for ranlib... ranlib
checking whether LLD linker is available... yes
checking whether clang++ supports -fno-omit-frame-pointer... yes
checking whether clang++ supports -glldb... yes
checking whether clang++ supports -fstandalone-debug... yes
checking whether clang++ supports -Wl,--no-as-needed... no
checking whether clang++ supports -Wl,--as-needed... yes
checking for swapcontext... no
checking if shared libs need -fPIC... no
checking for dlopen with CFLAGS="" LIBS=""... no
checking if --export-dynamic linker option is supported/needed... test failed
checking for flags needed to link with static libs containing simple modules... --whole-archive
configure: NOTE: Use the following syntax when linking with static libraries
configure: containing simple modules and other dynamically registered components:
configure:    clang++ ... -Wl,--whole-archive <libs> -Wl,--no-whole-archive ...
checking whether linker supports -rpath... no
checking for bison... bison -y
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking for make... make
checking for perl... perl
checking for swig... swig
checking for python3... python3
checking if all necessary Python modules are available... no
configure: error: Some Python modules required by the IDE were not found: omnetpp

**Comment by rhornig** [comment]
The content of the `config.log` file would be useful to diagnose this issue.

**Comment by Chenyu3194** [comment]
> The content of the `config.log` file would be useful to diagnose this issue.

So how can I start with the diagnose? I opened the config.log file and searched for keyword Python and the results are same as above. The statement of environmental variables seems to be correct, and the python3 is also found, but I don't know what to do next, or should I use pip install to do this manuelly?

**Comment by rhornig** [comment]
The `omnetpp` package is not hosted in pypi so you would not be able to use pip to install it. The required files should be present in the `<omnetpp_root>/python` directory and the PYTHONPATH variable must contain that directory.

What does 
$ echo $PYTHONPATH
print out exactly in your command prompt where you try to execute ./configure?

**Comment by Chenyu3194** [comment]
> The `omnetpp` package is not hosted in pypi so you would not be able to use pip to install it. The required files should be present in the `<omnetpp_root>/python` directory and the PYTHONPATH variable must contain that directory.
> 
> What does $ echo $PYTHONPATH print out exactly in your command prompt where you try to execute ./configure?

The output of $ echo $PYTHONPATH is as follow:

/d/Programm/omnetpp-6.0.1$ echo $PYTHONPATH
/d/Programm/omnetpp-6.0.1/python:D:\Programm\omnetpp-6.0.1\python

and it seems the directory or the path is recognized.

**Comment by rhornig** [comment]
Where the `D:\Programm\omnetpp-6.0.1\python` comes from? (well, I guess it is coming from the global windows environment setup). That is absolutely wrong. The PYTHONPATH variable should not contain Windows style directory paths (i.e. one with drive letters and backslashes). Only forward slashes are allowed and the colon character is used as a separator.

Delete that PYTHONPATH entry from your global system config... or if you need that (or similar entries in the global environemnt) then modify the `setenv` script in the OMNeT++ root. look for: 
```
export PYTHONPATH=$dir/python:$PYTHONPATH && PYTHONPATH=${PYTHONPATH%:}  # required because colon at the end causes issues on Windows
```

and remove the `:$PYTHONPATH` so it will not pick up your global PYTHONPATH settings.

**Comment by rhornig** [comment]
Picking up the PYTHONPATH global environmetn variable is regularly causing issues because the mingw version of python bundled with OMNeT++ is rather picky about the content of the PYTHONPATH variable causing issues if the user has set somtehing globally. I suggest fully overriding the PYTHONPATH variable to avoid interference from the global state. Sadly, this is not a great behavior on Linux and macOS where we are sourcing the setenv script which would override existing python path setting possibly breaking somnething else. 

This should be further investigated...

**Comment by Chenyu3194** [comment]
> Where the `D:\Programm\omnetpp-6.0.1\python` comes from? (well, I guess it is coming from the global windows environment setup). That is absolutely wrong. The PYTHONPATH variable should not contain Windows style directory paths (i.e. one with drive letters and backslashes). Only forward slashes are allowed and the colon character is used as a separator.
> 
> Delete that PYTHONPATH entry from your global system config... or if you need that (or similar entries in the global environemnt) then modify the `setenv` script in the OMNeT++ root. look for:
> 
> ```
> export PYTHONPATH=$dir/python:$PYTHONPATH && PYTHONPATH=${PYTHONPATH%:}  # required because colon at the end causes issues on Windows
> ```
> 
> and remove the `:$PYTHONPATH` so it will not pick up your global PYTHONPATH settings.

This method solved the problem perfectly. Now I see that the setenv file defined a default path for PYTHONPATH and it ran into conflict with my pre-defined PYTHONPATH from the SUMO programm. Thanks for the solution and suggestion!

**Comment by rhornig** [comment]
We may change that part of setenv because this is the 3rd time we run into an issue on Windows because of this. The pythonpath handling of the mingw version of python is less than optimal.

**Comment by suryasimman** [comment]
Thank you so much for the help! Have a great year
