### ISSUE TITLE
Build Project failed: Veins and OMNet++

### ISSUE THREAD

**Issue by Chenyu3194** [omnetpp/omnetpp#1018]
**Platform**
 - OMNeT++ version: 6.0.1
 - OS: Win 11

**Describe the bug**
Hi,

I am now trying to get OMNet++ and Veins work together, and I followed the instruction to build a project in the workspace. However, after importing project from Veins folder into workspace, I started the Build all Project option, and the build was failed. 

The errors are summarized as 2 errors at the end. I finished the Installation of OMNet++ with Instruction and some adjustment, and I'm wondering which part could be wrong

**To Reproduce**
Creating shared library: ../out/clang-debug/src/libveins_dbg.dll
ld.lld: error: undefined symbol: __declspec(dllimport) closesocket
>>> referenced by veins/modules/mobility/traci/TraCIConnection.cc:87
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIConnection.o:(veins::TraCIConnection::~TraCIConnection())
>>> referenced by veins/modules/mobility/traci/TraCIConnection.cc:127
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIConnection.o:(veins::TraCIConnection::connect(omnetpp::cComponent*, char const*, int))
>>> referenced by veins/modules/mobility/traci/TraCIScenarioManagerForker.cc:152
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIScenarioManagerForker.o:(veins::TraCIScenarioManagerForker::getPortNumber() const)

ld.lld: error: undefined symbol: __declspec(dllimport) inet_addr
>>> referenced by veins/modules/mobility/traci/TraCIConnection.cc:103
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIConnection.o:(veins::TraCIConnection::connect(omnetpp::cComponent*, char const*, int))

ld.lld: error: undefined symbol: __declspec(dllimport) gethostbyname
>>> referenced by veins/modules/mobility/traci/TraCIConnection.cc:107
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIConnection.o:(veins::TraCIConnection::connect(omnetpp::cComponent*, char const*, int))

ld.lld: error: undefined symbol: __declspec(dllimport) htons
>>> referenced by veins/modules/mobility/traci/TraCIConnection.cc:119
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIConnection.o:(veins::TraCIConnection::connect(omnetpp::cComponent*, char const*, int))

ld.lld: error: undefined symbol: __declspec(dllimport) socket
>>> referenced by veins/modules/mobility/traci/TraCIConnection.cc:124
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIConnection.o:(veins::TraCIConnection::connect(omnetpp::cComponent*, char const*, int))
>>> referenced by veins/modules/mobility/traci/TraCIScenarioManagerForker.cc:129
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIScenarioManagerForker.o:(veins::TraCIScenarioManagerForker::getPortNumber() const)

ld.lld: error: undefined symbol: __declspec(dllimport) connect
>>> referenced by veins/modules/mobility/traci/TraCIConnection.cc:126
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIConnection.o:(veins::TraCIConnection::connect(omnetpp::cComponent*, char const*, int))

ld.lld: error: undefined symbol: __declspec(dllimport) setsockopt
>>> referenced by veins/modules/mobility/traci/TraCIConnection.cc:147
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIConnection.o:(veins::TraCIConnection::connect(omnetpp::cComponent*, char const*, int))

ld.lld: error: undefined symbol: __declspec(dllimport) WSAStartup
>>> referenced by D:/Programm/omnetpp-6.0.1/include/omnetpp/platdep/sockets.h:47
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIConnection.o:(initsocketlibonce())
>>> referenced by ../out/clang-debug/src/veins/modules/mobility/traci/TraCIScenarioManagerForker.o

ld.lld: error: undefined symbol: __declspec(dllimport) WSAGetLastError
>>> referenced by D:/Programm/omnetpp-6.0.1/include/omnetpp/platdep/sockets.h:33
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIConnection.o:(sock_errno())

ld.lld: error: undefined symbol: __declspec(dllimport) send
>>> referenced by veins/modules/mobility/traci/TraCIConnection.cc:237
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIConnection.o:(veins::TraCIConnection::sendMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >))
>>> referenced by veins/modules/mobility/traci/TraCIConnection.cc:253
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIConnection.o:(veins::TraCIConnection::sendMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >))

ld.lld: error: undefined symbol: __declspec(dllimport) recv
>>> referenced by veins/modules/mobility/traci/TraCIConnection.cc:188
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIConnection.o:(veins::TraCIConnection::receiveMessage[abi:cxx11]())
>>> referenced by veins/modules/mobility/traci/TraCIConnection.cc:210
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIConnection.o:(veins::TraCIConnection::receiveMessage[abi:cxx11]())

ld.lld: error: undefined symbol: __declspec(dllimport) htonl
>>> referenced by veins/modules/mobility/traci/TraCIScenarioManagerForker.cc:138
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIScenarioManagerForker.o:(veins::TraCIScenarioManagerForker::getPortNumber() const)

ld.lld: error: undefined symbol: __declspec(dllimport) bind
>>> referenced by veins/modules/mobility/traci/TraCIScenarioManagerForker.cc:141
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIScenarioManagerForker.o:(veins::TraCIScenarioManagerForker::getPortNumber() const)

ld.lld: error: undefined symbol: __declspec(dllimport) getsockname
>>> referenced by veins/modules/mobility/traci/TraCIScenarioManagerForker.cc:146
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIScenarioManagerForker.o:(veins::TraCIScenarioManagerForker::getPortNumber() const)

ld.lld: error: undefined symbol: __declspec(dllimport) ntohs
>>> referenced by veins/modules/mobility/traci/TraCIScenarioManagerForker.cc:150
>>>               ../out/clang-debug/src/veins/modules/mobility/traci/TraCIScenarioManagerForker.o:(veins::TraCIScenarioManagerForker::getPortNumber() const)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
D:/Programm/omnetpp-6.0.1/tools/win32.x86_64/mingw64/bin/llvm-ar.exe: error: unable to load '../out/clang-debug/src/libveins_dbg.dll.a': No such file or directory
**make[1]: *** [Makefile:217: ../out/clang-debug/src/libveins_dbg.dll] Error 1**
make[1]: Leaving directory '/d/Programm/veins-5.2/src'
**make: *** [Makefile:36: all] Error 2**
"make MODE=debug -j16 all" terminated with exit code 2. Build might be incomplete.

20:31:09 Build Failed. 2 errors, 1 warnings. (took 34s.873ms)

**Comment by Chenyu3194** [comment]
BTW,

If I insist running the Veins project from the example folder, which is the omnetpp.ini, the following error occurs:

Starting...

$ cd D:/Programm/veins-5.2/examples/veins
$ ../../../omnetpp-6.0.1/bin/opp_run_dbg.exe -m -n .;../../src/veins --image-path=../../images -l ../../src/veins omnetpp.ini

OMNeT++ Discrete Event Simulation  (C) 1992-2022 Andras Varga, OpenSim Ltd.
Version: 6.0.1, build: 220831-e4f07d04b8, edition: Academic Public License -- NOT FOR COMMERCIAL USE
See the license for distribution terms and warranty disclaimer


<!> Error: Cannot load library '../../src//libveins_dbg.dll': ????????

End.

Simulation terminated with exit code: 1
Working directory: D:/Programm/veins-5.2/examples/veins
Command line: ../../../omnetpp-6.0.1/bin/opp_run_dbg.exe -m -n .;../../src/veins --image-path=../../images -l ../../src/veins omnetpp.ini

Environment variables:
PATH=;D:/Programm/veins-5.2/src;D:\Programm\omnetpp-6.0.1\bin;D:\Programm\omnetpp-6.0.1\tools\win32.x86_64\opt\mingw64\bin;D:\Programm\omnetpp-6.0.1\tools\win32.x86_64\usr\bin;D:\Programm\omnetpp-6.0.1\tools\win32.x86_64\mingw64\bin;;D:/Programm/omnetpp-6.0.1/ide//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.stripped.win32.x86_64_17.0.4.v20220805-1047/jre/bin/server;D:/Programm/omnetpp-6.0.1/ide//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.stripped.win32.x86_64_17.0.4.v20220805-1047/jre/bin;D:\Programm\omnetpp-6.0.1\bin;D:\Programm\omnetpp-6.0.1\tools\win32.x86_64\opt\mingw64\bin;D:\Programm\omnetpp-6.0.1\tools\win32.x86_64\mingw64\bin;D:\Programm\omnetpp-6.0.1\tools\win32.x86_64\usr\local\bin;D:\Programm\omnetpp-6.0.1\tools\win32.x86_64\usr\bin;D:\Programm\omnetpp-6.0.1\tools\win32.x86_64\usr\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\Programm\omnetpp-6.0.1\tools\win32.x86_64\usr\bin\site_perl;D:\Programm\omnetpp-6.0.1\tools\win32.x86_64\usr\bin\vendor_perl;D:\Programm\omnetpp-6.0.1\tools\win32.x86_64\usr\bin\core_perl;D:\Programm\omnetpp-6.0.1;
OMNETPP_RELEASE=omnetpp-6.0.1
OMNETPP_IMAGE_PATH=D:\Programm\omnetpp-6.0.1\images

It seems that a .dll file can not be loaded. Is this the problem or could be something else? When this causes the situation then how should this be fixed

**Comment by rhornig** [comment]
This is not an issue with OMNeT++ but with Veins, so must be submitted to the Veins bugtacker.

A quick glance shows however that the winsock2 library is not linked to the venis DLL on Windows. The [changelog](https://veins.car2x.org/download/#compatibility) on the Veins site clearly states that Veins 5.2 does NOT work on Windows with OMNeT++ 6.0 final. It states the it stopped working after OMNeT++ 6.0pre14 version.

Now that piqued my curiosity to see why the build broke. In the `src/makefrag` file in Veins, there is a line
```
ifeq ($(PLATFORM),win32.x86_64)
```
however that should be:
```
ifeq ($(PLATFORM),win32)
```
try to change that and fully rebuild Veins.
