### ISSUE TITLE
missing dll issues

### ISSUE THREAD

**Issue by Thanoon12k** [omnetpp/omnetpp#1036]
**Platform**
 - OMNeT++ : 6.0.1  
 - OS: windows 10

**Describe the bug**
i download omnetpp 6.0.1 from offical website then i unzip the archive in folder D:\omnetpp\omnetpp-6.0.1
after that i open mingwenv.cmd then type this commands
>> ./configure
>> make
>>omnetpp

then omnetpp-6.0.1 ide start after that
-i uncheck inet and examples download 
- in resource are i imported project tictoc from samples
- right click on tictoc project folder >build 
- it build it as expeced and generate makefile and tictoc.exe file 
- right click in omnetpp.ini >run as > omnetpp > simulation run ok as expected
- when i run tictoc.exe file i got dll messing error

**Comment by rhornig** [comment]
You MUST run tictoc either from the IDE (where it runs correctly) or from the mingwenv prompt where the path is correctly set. You should NOT run a simulation from the Windows explorer as the required path is not set up correctly.
