### ISSUE TITLE
Some figures in the Simulation Manual appear to be zoomed to their top-left corner

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#1048]
In the Simulation Manual for OMNeT++ 6.0, figures generated via Graphviz **dot** appear zoomed to their top-left corner. Examples: 
"Figure 8.4: cFigure class hierarchy",  "Figure 9.1: Building and running simulation". This affects both the HTML and PDF versions.

![Screenshot from 2023-09-10 09-55-19](https://github.com/omnetpp/omnetpp/assets/57529/8021eb2a-b0b0-453a-bb0a-40a9cb1b6412)

**Comment by avarga** [comment]
The SVG images generated by dot appear to have a wrong bounding box, 50%-70% smaller than necessary in both dimensions (but aspect ratio is OK). This is obvious when opening the images in e.g. Inkscape:

![Screenshot from 2023-09-10 10-03-44](https://github.com/omnetpp/omnetpp/assets/57529/bb112afb-8529-4b66-aac3-53e3128543b9)

**Comment by avarga** [comment]
Ubuntu 23.04, `dot -V` says `dot - graphviz version 2.43.0 (0)`.

It seems to be related to following bug: "Generated svg output doesn't fit into its own bounding box" https://gitlab.com/graphviz/graphviz/-/issues/1406, where the last comment says "It does work correctly with 5.0.0."

**Comment by avarga** [comment]
Workaround: Python script to update viewBox in SVG files.

**Comment by avarga** [comment]
Note: removing the `width`, `height`, `viewBox` attributes from the `<svg>` element makes the PDF output look good, but not the HTML output.

**Comment by rhornig** [comment]
cherry picked to the 5.7.x and 6.0.x branch

**Comment by Enough7** [comment]
Hey guys,
fyi in the webversion the image is still not fixed:
![image](https://github.com/omnetpp/omnetpp/assets/30051680/3f802010-f3a2-4719-bbca-7a9480a7348b)

**Comment by rhornig** [comment]
updated the website with the upcoming 6.0.3 documentation. Some pictures are still cropped a bit, but much better.
