### ISSUE TITLE
Add copy ctor to omnetpp::cTopology

### ISSUE THREAD

**Issue by t-arik** [omnetpp/omnetpp#1052]
I've noticed that `cTopology`'s [copy constructor](https://github.com/omnetpp/omnetpp/blob/25540536671ebae8151a14d112d5e63cd9a4e82c/src/sim/ctopology.cc#L68) and [`=` operator](https://github.com/omnetpp/omnetpp/blob/25540536671ebae8151a14d112d5e63cd9a4e82c/src/sim/ctopology.cc#L85C8-L85C8) are not implemented yet.

I would be happy to contribute to the implementations and will follow up with a PR.

**Comment by avarga** [comment]
Sure. As long as you are OK with assigning the copyright of your changes to us, you are welcome to do so.

**Comment by rhornig** [comment]
closed due inactivity
