### ISSUE TITLE
X11 forwarding fails with OMNeT++ v6.0.1

### ISSUE THREAD

**Issue by B0GDAN** [omnetpp/omnetpp#1057]
**Platform**
 - OMNeT++ version: 6.0.1.220831
 - OS: Raspbian 11 bullseye (on Raspberry Pi4)

**Describe the bug**
Can't start X11 forwarding with OMNET++. I use MobaXTerm with X11 fwd enabled and it already works with Wolfram Mathematica. When trying the same with OMNET++ I get the following error:

vi /home/pi/Downloads/omnetpp-6.0.1/ide/configuration/1696842179161.log

!SESSION 2023-10-09 11:02:58.635 -----------------------------------------------
eclipse.buildId=6.0.1.220831-e4f07d04b8
java.version=17.0.4
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=aarch64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch aarch64

!ENTRY org.eclipse.osgi 4 0 2023-10-09 11:03:04.938
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
        at org.eclipse.swt.SWT.error(SWT.java:4933)
        at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1167)
        at org.eclipse.swt.widgets.Display.create(Display.java:1091)
        at org.eclipse.swt.graphics.Device.<init>(Device.java:168)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:643)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:634)
        at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:742)
        at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:168)
        at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:182)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:125)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

**To Reproduce**
Help the development team to reproduce the issue.
Provide step-by-step instructions, code examples, etc.

- make sure the prerequisites are the same (HW, OS, Omnet++ version, remote access)
- go to cd /home/pi/Downloads/omnetpp-6.0.1/bin or wherever Omnet++ is installed and run sudo ./omnetpp

**Comment by avarga** [comment]
`SWTError: No more handles [gtk_init_check() failed]` 

This error seems to happen when SWT, the widget library of Eclipse, tries to initialize the underlying GTK library, and fails to do so.  The error seems to happen so early in the startup sequence that likely no OMNeT++ IDE contributed code has run yet.

So, this seems to be an Eclipse (SWT) issue. Have you checked the Eclipse bug tracker and forums?

**Comment by B0GDAN** [comment]
Not yet. I'll check it right away. 
Since it's not related to OMNeT++ I'll close this thread.
Thanks for the update!

**Comment by rhornig** [comment]
Some additional hints: 

This looks like a resource exhaustion issue based on the error message and seeing that you are running on a Raspberry Pi4 only heightens the suspicion.

**Comment by rhornig** [comment]
Would you mind trying the latest 6.0.2 release? I have updated both the JRE and the base Eclipse platform. https://github.com/omnetpp/omnetpp/releases/tag/omnetpp-6.0.2

**Comment by torokati44** [comment]
> go to cd /home/pi/Downloads/omnetpp-6.0.1/bin or wherever Omnet++ is installed and run sudo ./omnetpp

I see you're trying to run the IDE with `sudo`. There's usually no need for that, and can cause problems, even ones like this. Does it work without `sudo`?

**Comment by B0GDAN** [comment]
running omnetpp without sudo:

`pi@raspberrypi:~/Downloads/omnetpp-6.0.1/bin $ ./omnetpp
Environment for 'omnetpp-6.0.1' in directory '/home/pi/Downloads/omnetpp-6.0.1' is ready.
Starting the OMNeT++ IDE...
./omnetpp: 35: ./opp_ide: cannot create ./../ide/error.log: Permission denied
`

regarding libgtk

`pi@raspberrypi:~/Downloads/omnetpp-6.0.1/bin $ dpkg -l libgtk[0-9]* | grep ^i
ii  libgtk2.0-0:arm64 2.24.33-2+rpt1 arm64        GTK graphical user interface library - old version
ii  libgtk2.0-bin     2.24.33-2+rpt1 arm64        programs for the GTK graphical user interface library
ii  libgtk2.0-common  2.24.33-2+rpt1 all          common files for the GTK graphical user interface library
`

X11 forwarding is already enabled

 ⮞ SSH session to *************                                                                    │
    │   • Direct SSH      :  ✓                                                                             │
    │   • SSH compression :  ✓                                                                       │
    │   • SSH-browser     :  ✓                                                                          │
    │   • X11-forwarding  :  ✓  (remote display is forwarded through SSH)  │

**Comment by torokati44** [comment]
> ./omnetpp: 35: ./opp_ide: cannot create ./../ide/error.log: Permission denied

This is probably because you extracted the release using `sudo`...? I don't think anything related to OMNeT++ should be done as `root` (except for installing dependencies).

**Comment by rhornig** [comment]
Yes. Having proper write access to the configuration directory is an absolute must. Eclipse extracts several shared libraries there. Remove the whole omnetpp-6.0.2 directory (with sudo) and then extract and use omnet as a normal user.

**Comment by B0GDAN** [comment]
Yup, this was the reason! Did everything according to the manual and now I'm able to start a remote session from the command line through X11 forwarding. The delay is sadly very high and renders the whole thing unusable. Maybe it can be better from within the local network. It's strange, because I definitely don't experience this with Mathematica.

Thanks for the help!

**Comment by rhornig** [comment]
X11 was not designed to be run over a non-local connection. Your experience may vary depending on the complexity of the application. Probably Mathematica is more forgiving on this. Eclipse was definitely not optimized for long roundtrip X11 connections. An XTerminal could be quite ok on a non-local connection however any CAD software would suffer seriously. I guess eclipse is somewhere between.

Just out of curiosity: what is the reason you are using a raspberry over a non-local connection to run simulations? I guess your desktop machine would be more suitable for this.

**Comment by B0GDAN** [comment]
> An XTerminal could be quite ok on a non-local connection however any CAD software would suffer seriously. I guess eclipse is somewhere between

Thought so too. Mathematica actually has some kind of lower desktop rendering probably it's the reason why it has better performance with X11 forwarding. However, after switching to cloud VNC and then to VNC via SSH tunneling the performance is quite good also with omnet now. 
I'm not always on my desktop PC but I want to be able to play around with my simulator from other terminals as well. That's why a remote connection was mandatory for me.

**Comment by rhornig** [comment]
Ok, thanks for the info. Yes, sometimes even sending invalid screen regions as a compressed bitmap is faster than sending the extreme amount of small X11 primitives over the network. Well, anyway, X11 is now retiring...
