### ISSUE TITLE
`configure` script does not respect `$PYTHON3` environment variable.

### ISSUE THREAD

**Issue by mmfallacy** [omnetpp/omnetpp#1059]
**Platform**
 - OMNeT++ version: **6.0.1**
 - OS: **Ubuntu 22.04.3**
 > I am currently running an Ubuntu 22.04.3 distrobox in Arch Linux. I do think that this issue is not specific to my OS.

**Describe the bug**
Running the `./configure` command fails when checking for specific python packages.
I assume this stems from the fact that at line `4516` (`804` in `configure.in`) , the script specifically uses `python3` instead of using the specified `$PYTHON3` interpreter.

**To Reproduce**
- Create two python environments (say `env1` and `env2`).
- Link `env1/bin/python` to `usr/bin/python3`.
- Export environment variable `PYTHON3` to `env2/bin/python`. 
- Install the necessary dependencies in `env2`.
- Run `./configure`

**Comment by rhornig** [comment]
All scripts assume a python3 interpreter on the path and uses that interpreter by default. The PYTHON3 variable inside the configure.in script is an internal detail as was never meant to override the default interpeter.

If you want to use your own venv, before running ./configure you must active your python virtual environment (i.e. `sourece env2/bin/activate`). The proper order:
```
$ source setenv
$ source env2/bin/activate
$ ./configure
$ make
```
