### ISSUE TITLE
When I step with tictoc tutorial, at the step "Running and Simulation", I'm having problems with "make"

### ISSUE THREAD

**Issue by ycchen112** [omnetpp/omnetpp#1066]
**Platform**
 - OMNeT++ version: [6.0.2]
 - OS: [macos 18.04]

**Describe the bug**
when I step with tictoc , at the step Running and Simulation
```
11:29:46 **** Incremental Build of configuration release for project tictoc ****
make MODE=release all
make: *** No rule to make target 'all'.  Stop.
"make MODE=release all" terminated with exit code 2. Build might be incomplete.
11:29:46 Build Failed. 1 errors, 0 warnings. (took 392ms) 
```

**To Reproduce**
Make tutorials more detailed for newbies

**Comment by rhornig** [comment]
you have a build error, i.e. your code does not compile. You should fix the code (see the problems view for the errors). This has nothing to do with "stepping or debugging"
