### ISSUE TITLE
OSG error when installing 6.0.2 AARCH64 on macOS

### ISSUE THREAD

**Issue by MoienBowen** [omnetpp/omnetpp#1067]
**Platform**
 - OMNeT++ version: 6.0.2
 - OS: macOS 14.1.1

**Describe the bug**
1. `./configure` Unable identify the path of org (no problem with 6.0.1) -> have to change WITH_OSG=no
2. `make -j10` returns `make: *** [allmodes] Error 2` -> `*** No rule to make target `/Users/[user]/Workspace/omnetpp-6.0.2/out/clang-release/src/common/lcgrandom.o', needed by `/Users/[user]/Workspace/omnetpp-6.0.2/out/clang-release/src/common/liboppcommon.dylib'.  Stop.` (no problem with 6.0.1)
3. the commands does not work
```
$ make install-menu-item
$ make install-desktop-icon
```

**To Reproduce**
- Download the AARCH64 package, and follow the instruction at /doc/InstallGuide.pdf
- `./configure`
- `make -j10`

**Comment by MoienBowen** [comment]
in "./configure", the following codes is updated on 22/04/2022 (but not packaged in release 6.0.1) from 

```
if ac_fn_cxx_try_link "$LINENO"; then :
  { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
$as_echo "yes" >&6; }; osg_ok=yes;
else
  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
$as_echo "no" >&6; }; osg_ok=no;
```

to

```
if ac_fn_cxx_try_link "$LINENO"
then :
  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
printf "%s\n" "yes" >&6; }; osg_ok=yes;
else $as_nop
  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
printf "%s\n" "no" >&6; }; osg_ok=no;
```

Is that the reason for bug point 1?

**Comment by MoienBowen** [comment]
Point 2 solved.
Thanks for https://github.com/omnetpp/omnetpp/issues/1001.

The make is 3.81 by default, we need to install newer version via `brew install make` and add it into the path via `PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"`.

**Comment by rhornig** [comment]
At the moment the macOS / aarch64 versions is tested only with the [opp_env](https://github.com/omnetpp/opp_env) (which uses the NIX package manager internally). (and OSG is disabled on those builds). over time we will test also with brew packages.

**Comment by rhornig** [comment]
The install guide got updated for homebrew instructions and OSG is working now when installed from homebrew.
