### ISSUE TITLE
GLIBC version conflict 

### ISSUE THREAD

**Issue by taskkk** [omnetpp/omnetpp#1078]
**Platform**
 - OMNeT++ version: [6.0.2]
 - OS: [Ubuntu 20.04.6LTS]

**Describe the bug**
Have any of you encountered GLIBC version mismatch? omnet++6.0.2 installation document shows that it supports Ubuntu 20.4LTS, and my system is Ubuntu 20.4.6LTS, which supports it, but after installing it, it prompts me that the GLIBC version doesn't match, and the version that comes with the system is 3.1, but omnet++ requires GLIBC3.2. GLIBC3.2, is there any other way to solve the version conflict besides upgrading to a new system? Thanks for your help!

**Comment by rhornig** [comment]
errr... we had to upgrade our build images (to ubuntu 22.04) for unrelated reasons for 6.0.2 (eclipse build issues). This sneakily introduced a dependency on on a newer version of glibc. We had a workaround to avoid this and previously we were able to force building against quite an older version. Sadly, this is no longer working. I'm looking for other solutions...

**Comment by rhornig** [comment]
it seems the old hacks are no longer working :(. I have rebuilt the shared lib on ubuntu 20.04. Would you mind to [try it](https://drive.google.com/file/d/1Lng8GbMj70zBLcqbAWA4SiS8nN7ANH_d/view?usp=drive_link) @gatsby0203 ?

**Comment by gatsby0203** [comment]
@rhornig 
Sorry for the delay, it works now.
I noticed you had updated tarball on the release page, I'd tested it too, and it works fine!
