### ISSUE TITLE
Connection chooser always offers gate[0] and not the first free gate

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#108]
**Reported by andras on 21 Oct 2009 13:27**

**Version:** 4.0

NED editor connection drawer does not work well, the index of the gate does not increased. If the size of the gates was specified, as in the following case:

module M1 {
    gates:    inout g[5];
}                                             

module M2 {
    gates:  inout g[];
}                                        

module CM {
    submodules:
        m11: M1;
        m12: M1;
        m21:M2{
            gates:  g[5];
        }
        m22:M2{
            gates:  g[5];
        }
}

If we use the connection drawer of the IDE, only g[0] will be used.

The following codes are generated by the IDE:
        m12.g[0] &lt;--&gt; m22.g[0];
        m22.g[0] &lt;--&gt; m21.g[0];
        m21.g[0] &lt;--&gt; m11.g[0];
        m11.g[0] &lt;--&gt; m12.g[0];

**Additional information:** Suggested workaround: use g++ and automatic gate size instead.

[Mantis Bugtracker #113](https://dev.omnetpp.org/bugs/view.php?id=113)

**Comment by rhornig** [comment]
As this is non-trivial and indefinitely postponed, I'm closing it.
