### ISSUE TITLE
Error encountered while running osg-satellites

### ISSUE THREAD

**Issue by tongchenqiang** [omnetpp/omnetpp#1083]
Hello, I encountered the following error while running the osg-satellites in omnet：

This example requires OpenSceneGraph and osgEarth installed -- in module (OsgEarthScene) OsgEarthNet.osgEarthScene (id=2), during network initialization

I have installed osgearth，but such problems can also arise. Do you know why?

Thank you!

**Comment by rhornig** [comment]
If you installed osgEarth, you must explictly enable osgEarth support in configure.user, then rerun `./configure` and rebuild OMNeT++.

**Comment by ZHuIMengDY** [comment]
I'm having this issue as well, did you fix it?
