### ISSUE TITLE
Error running ./configure

### ISSUE THREAD

**Issue by chima-okwara** [omnetpp/omnetpp#1087]
**Platform**
 - OMNeT++ version: 6.0.2
 - OS: Linux Mint 21.1

**Describe the bug**
I already installed all required python modules using `python3 -m pip install --user --upgrade numpy pandas matplotlib scipy seaborn posix_ipc ` and then I ran ```source setenv```. When I run `./configure` , I get the error message: 
```
checking if all necessary Python modules are available... no
configure: error: Some Python modules required by the IDE were not found: pandas matplotlib posix_ipc
```

I've tried manually exporting the $PYTHONPATH variable and then removing it, nothing seems to have worked so far.
**To Reproduce**
Extract omnetpp to home directory, open terminal and change directory to omnetpp directory. Run 

```
$ sudo apt-get install build-essential clang lld gdb bison flex perl \
python3 python3-pip qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools \
libqt5opengl5-dev libxml2-dev zlib1g-dev doxygen graphviz \
libwebkit2gtk-4.0-37 xdg-utils
$ python3 -m pip install --user --upgrade numpy pandas matplotlib scipy \
seaborn posix_ipc
```
then run

`source setenv` 

and 

`./configure`

**Comment by rhornig** [comment]
What is the output of `echo $PYTHONPATH` and could you attach the generated `config.log` from the root directory?

**Comment by chima-okwara** [comment]
> What is the output of `echo $PYTHONPATH` and could you attach the generated `config.log` from the root directory?

Thanks for replying. Here's the output of `echo $PYTHONPATH`:

```
home/chima/omnetpp-6.0.2/python
```

Here's the output of `config.log`:
[config.log](https://github.com/omnetpp/omnetpp/files/13675546/config.log)

**Comment by rhornig** [comment]
hmm. This is really unexpected. I cannot tell the reason from the log file. this is the testing code that actually runs:
```
# These should always be available by default, but just as a sanity check:
import argparse, pickle, math, io, sys, os, platform, mmap, pprint, json, \
re, itertools, importlib, inspect, glob, functools, csv, string, \
struct, socket, subprocess, time, traceback, threading, types, copy, \
tempfile, select, shlex, unittest, weakref, logging, multiprocessing, xml

failed = list()

def try_import(name):
global failed
try:
importlib.import_module(name)
except:
failed.append(name)

try_import("difflib") # for opp_test and scave python tester

# for the Analysis Tool:
try_import("omnetpp")
try_import("numpy")
try_import("scipy")
try_import("pandas")
try_import("matplotlib")

if os.name == 'posix':
try_import("posix_ipc")
try_import("fcntl")
else:
try_import("msvcrt")

if failed:
print(" ".join(failed))
exit(1)

# The utils module checks the versions of some Python packages when imported
from omnetpp.scave import utils
```

In a python shell try to import pandas, matplotlib and posix_ipc. For some reason the import fails for these modules. Perhaps directly import them in an interactive will give more hints about the issue.

**Comment by rhornig** [comment]
Also if you prefer, you may try to install omnet via `opp_env` which will handle all the dependencies automagically.
