### ISSUE TITLE
Another Error running configure file 

### ISSUE THREAD

**Issue by mopoa** [omnetpp/omnetpp#1090]
**Platform**
 - OMNeT++ version: 6.0.2
 - OS: Ubuntu 22.04
 - flex 2.6.4
 
I installed all the  dependencies on my machine without any error based on the Installation.pdf file but it encounter an error while configuring the makfile

this is the output of the ./configure execution :

![Screenshot from 2023-12-29 12-14-49](https://github.com/omnetpp/omnetpp/assets/41018831/2c4b7baa-515f-43c2-a1b1-53b8c7322764)

**Comment by rhornig** [comment]
While it complains about Flex, the problem surfaces earlier. The configure script cannot figure out how to create dynamic libraries (and falls back to static libs). Dynamic lib creation is a **must**. probably a system library is missing or incorrectly configured. The content of `config.log` could help to figure out what is missing.
