### ISSUE TITLE
An error occurred while downloading the list of models available for installation

### ISSUE THREAD

**Issue by Arboulahdour** [omnetpp/omnetpp#1094]
**Platform**
 - OMNeT++ version: 6.0.2
 - OS: Ubuntu 22.04

**Describe the bug**
I'm encountering an issue while installing the inet framework. When attempting to access the list of available simulation models by clicking on "Install Simulation Models," I receive the following error: "An error occurred while downloading the list of models available for installation: Server returned HTTP response: 403 for URL https://models.omnetpp.org/descriptors/omnetpp-6.0/descriptors.txt." 

Interestingly, I can access this URL in my browser without any problems. Could you please provide guidance on resolving this issue?

**To Reproduce**
Go to Help -> Install Simulation Models.
![Screenshot from 2024-01-14 13-13-58](https://github.com/omnetpp/omnetpp/assets/58618795/b6cc2409-06f2-4cf7-bd1e-423b649d8cbf)

**Comment by rhornig** [comment]
Could it be that you are in an environment where proxy services should be used? The browser is configured to correctly use the proxy, while it was not set up properly inside eclipse.

**Comment by Arboulahdour** [comment]
> Could it be that you are in an environment where proxy services should be used? The browser is configured to correctly use the proxy, while it was not set up properly inside eclipse.

Well, I'm connecting from home.. I'm not behind any proxy! But it's okay I did the installation of INET manually :)
