### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Ztalhai** [omnetpp/omnetpp#1099]
When I try to install your 5.6 version and 5.5.1 version to work on Ubuntu via artery simulation framework, I keep getting the same error.

./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
configure: -----------------------------------------------
configure: reading configure.user for your custom settings
configure: -----------------------------------------------
checking for clang... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking for clang++... clang++
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking for clang++... clang++
checking for ranlib... ranlib
checking whether clang++ supports -fno-stack-protector... no
checking whether clang++ supports -Wl,--no-as-needed... no
checking whether clang++ supports -Wl,--as-needed... no
checking for swapcontext... no
checking if shared libs need -fPIC... failure
configure: WARNING: COULD NOT FIGURE OUT HOW TO BUILD SHARED LIBRARY -- reverting to static libs
checking for dlopen with CFLAGS="" LIBS=""... no
checking if --export-dynamic linker option is supported/needed... test failed
checking for flags needed to link with static libs containing simple modules... no solution found
configure: WARNING: Avoid linking with static libraries containing simple modules
configure: WARNING: and other dynamically registered components. Those components
configure: WARNING: will not be found by the simulation program, because the linker
configure: WARNING: leaves them out from the executable.
checking whether linker supports -rpath... no
checking for bison... bison -y
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking for make... make
checking for perl... perl
checking for swig... swig
checking for math with CFLAGS="" LIBS=""... no
checking for math with CFLAGS="" LIBS="-lm"... no
configure: error: Standard C math library -lm not found

**Comment by avarga** [comment]
Which Ubuntu version? Did you follow the OMNeT++ Installation Guide and install the required packages in it?

**Comment by avarga** [comment]
This looks bad enough: `configure: WARNING: COULD NOT FIGURE OUT HOW TO BUILD SHARED LIBRARY -- reverting to static libs`. Something is wrong with your Ubuntu installation, but it's hard to tell what. Examining the contents of `config.log` could help.

**Comment by Ztalhai** [comment]
Thank you

**Comment by rhornig** [comment]
I mean, we are still interested in the log file to see why this happened...

**Comment by luisfmnunes** [comment]
Well, Using Ubuntu 22.04 I faced the same problem, sending the [config.log](https://github.com/user-attachments/files/16165151/config.log).

**Comment by luisfmnunes** [comment]
So... I found out how to solve the problem. It`s actually related with `clang`. When you run `clang -v` it chooses the latest GCC installation available, in my case looking at the config.log was the gcc-12. However, Ubuntu 22 `build-essential` package and the instructions in the `InstallGuide.pdf ` install only `g++-11`, which leads to missing references of C++ since `clang` is using gcc-12 installation, leading to version mismatch. To solve this you only need to install `g++12` with `sudo apt install g++-12`.
