### ISSUE TITLE
Error opening .sca/.vci/.vec files

### ISSUE THREAD

**Issue by SeineEloquenz** [omnetpp/omnetpp#1101]
Hi!
I am using omnetpp-6.0.2+inet-4.5.2 in an opp_env installation installed via pip under NixOS.

When I want to view simulation results in the IDE, once I click on a .sca/.vci/.vec file in the Project Explorer, i get the following error dialog instead of the Results Viewer:
![image](https://github.com/omnetpp/opp_env/assets/34923333/494bd629-2169-4063-8c53-4a55fcca0155)

Thanks!

**Comment by rhornig** [comment]
could you provide the `.log` file from the workspace's `.metadata` directory? 

The message is strange as it wants to open an **external** editor. Normally it should open the IDE's build-in editor. Try right clicking the file and select the internal editor with the Open with menu item.

**Comment by SeineEloquenz** [comment]
Hi, I've attached the log file to this comment.
Trying to open the file via the "open with" menu yields the same error.

[log.txt](https://github.com/omnetpp/omnetpp/files/14280272/log.txt)

**Comment by rhornig** [comment]
Hmmm. All the failures in the log indicate that the IDE cannot start the python3 executable. Can you start python3 manually before starting the IDE to see whether it starts?

I have never tried opp_env under NixOS. Maybe this is some interference between the OS packages and the Nix Developer shell opp_env internally starts.

Also, could you try to use the `-i` flag when starting the shell (that will start the shell in isolated mode minimizing the interference).

Maybe this is indeed an opp_env issue and not something specific with OMNeT++ (so I may have to move back this issue :)

**Comment by SeineEloquenz** [comment]
I can start python without problems in the omnetpp shell.
It prints `python 3.10.11`.
I don't have python in in my OS packages or path.
When running the omnetpp shell with the -i flag, the same error still occurs, but I can run python itself fine.

**Comment by rhornig** [comment]
I need to set up a VM to try to reproduce this.

**Comment by rhornig** [comment]
unfortunately, I'm unable to reproduce this so closing. If it still happens, please re-open.
