### ISSUE TITLE
problem with some python modules !!!

### ISSUE THREAD

**Issue by Y-AMDIAZ** [omnetpp/omnetpp#1105]
I want to download the last version of omnet++ but I had a probleme with the instalation , it gives me that I have a messing modules of python or I dont know can some one help me please how can I solve this problem 
Omnet++6.0.1
windows 11 

<img width="865" alt="image" src="https://github.com/omnetpp/omnetpp/assets/129278941/307a5acc-5321-475b-9592-bc02c3000603">

**Comment by rhornig** [comment]
This usually happens because you already have Python installed and mingwenv picks up the system installation and adds that to the PATH. Remove the PYTHONPATH environament variable from the system environment (or add `export PYTHONPATH=` to the setenv script.

**Comment by rhornig** [comment]
Actually omnetpp-6.0.2 contains this fix, so you are probably better off using that version. (or wait for the soon upcoming 6.0.3 version)

or ypu can manually add the the # Windows/MinGW specific settings if/then block.
