### ISSUE TITLE
Map in openstreetmap example is completely distorted

### ISSUE THREAD

**Issue by MaximilianKoestler** [omnetpp/omnetpp#1108]
**Platform**
 - OMNeT++ version: 6.0.2, Build id: 231006-7d5ca33dba
 - OS: Microsoft Windows [Version 10.0.19045.4046]

**Describe the bug**
I wanted to try the `openstreetmap` sample that comes with OMNeT++ on my completely fresh and by-the-book install of version 6.0.2.
When launching the example, the canvas looks like this:

![image](https://github.com/omnetpp/omnetpp/assets/6814304/86e43aa1-c003-4247-9086-3211ed3f042a)

A lot of objects are clustered at the "focal point" of the distortion

![image](https://github.com/omnetpp/omnetpp/assets/6814304/2c4e0106-2da9-4afc-b478-0a581149d8b0)

**To Reproduce**
Import and launch the `openstreetmap` sample.

**Comment by avarga** [comment]
This is strange, as it looks fine on Linux. We'll look into it, thank you for reporting.

**Comment by avarga** [comment]
We need to parse IDs with `strtoll` instead of `strtol`, because longs are only 32-bit on Windows... This caused IDs to get mixed up.

**Comment by torokati44** [comment]
I'm not sure why GitHub didn't backreference it, nevertheless, the fix is in `master`: https://github.com/omnetpp/omnetpp/commit/a836f3a0c725d53056a9f247e3c13a01e789a805
