### ISSUE TITLE
download erreur version Makefile:54: Makefile.inc: No such file or directory Omnet++ 5.6.2

### ISSUE THREAD

**Issue by Y-AMDIAZ** [omnetpp/omnetpp#1113]
I want to download OMNeT++, and I have tried several versions, but it's not working. I don't know how to proceed; I just want to use Simu5G. However, OMNeT++ 5.6.2 won't download, and it gives me an error as shown in the figure. Can you please help me? please help me 
<img width="610" alt="image" src="https://github.com/omnetpp/omnetpp/assets/129278941/5f01fe07-1862-45f1-8a0b-4f1a29d8ff51">

**Comment by rhornig** [comment]
Please, do NOT install OMNeT++ (or any of the models) under a directory path containing **spaces**. That drives the build system crazy and prevents the configure process.

Also, why use such an old version of OMNeT++? Why not the latest?
