### ISSUE TITLE
Unable to determine type name for submodule app, missing entry LTE.server.app[0].typename and no default value

### ISSUE THREAD

**Issue by marshalbabu** [omnetpp/omnetpp#1133]
**Platform**
 - OMNeT++ version: Version: 6.0, Build id: 220413-71d8fab425
 - OS: Windows 11
 - INET 4.5
 - Simu 5G

**Describe the bug**
Unable to determine type name for submodule app, missing entry LTE.server.app[0].typename and no default value, at C:/omnetpp-6.0-windows-x86_64/omnetpp-6.0/myproject/inet4.5/src/inet/node/base/ApplicationLayerNodeBase.ned:20 -- in module (inet::NodeBase) LTE.server (id=7), during network setup

**To Reproduce**

below is my .ini file. I have used simu 5G GUI and multicell example to build lte network.

[General]
network=LTE
eventlog-file = allevent ${resultdir}/${configname}-${iterationvarsf}#${repetition}.elog
record-eventlog = true
sim-time-limit = 1s
simtime-resolution = 100ns
*.ue*.numApps = 1
*.server.numApps = 12
**.numBands = 50
LTE.channelControl.carrierFrequency = 1800MHz
**.eNodeB.masterId =3
**.eNodeB1.masterId=1
**.eNodeB2.masterId=2
# connect each UE to the eNB
**.ue1*.macCellId = 1
**.ue1*.masterId = 1
**.ue2*.macCellId = 2
**.ue2*.masterId = 2
**.ue3*.macCellId = 3
**.ue3*.masterId = 3
**.ue4*.macCellId = 1
**.ue4*.masterId = 1
**.ue5*.macCellId = 2
**.ue5*.masterId = 2
**.ue6*.macCellId = 3
**.ue6*.masterId = 3
**.ue7*.macCellId = 1
**.ue7*.masterId = 1
**.ue8*.macCellId = 2
**.ue8*.masterId = 2
#eNodeB
*.eNodeB.macCellId = 1
*.eNodeB.txPower= 31622mw

# eNodeB 1
*.eNodeB1.macCellId = 2
*.eNodeB1.txPower = 39810mw
*.eNodeB1.nicType = "LteNicEnb"
#eNodeB 2
*.eNodeB2.macCellId = 3
eNodeB.cellularNic.mac.muMimo = false
# positioning and mobility
*.ue*.mobility.initialMovementHeading = uniform(0deg, 360deg)
*.ue*.mobility.constraintAreaMaxX = 1000m
*.ue*.mobility.constraintAreaMaxY = 1000m
*.ue*.mobility.constraintAreaMinX = 0m
*.ue*.mobility.constraintAreaMinY = 0m
*.ue*.mobility.initFromDisplayString = false
*.ue*.mobility.initialX = uniform(0m,300m)
*.ue*.mobility.initialY = uniform(0m,300m)
*.ue*.mobility.initialZ = 0m
*.ue*.mobility.speed = 0mps
*.ue*.mobility.typename = "LinearMobility"

# positioning and mobility
**.mobility.initFromDisplayString = false

*.eNodeB1.mobility.initialX = 300m
*.eNodeB1.mobility.initialY = 250m
*.eNodeB2.mobility.initialX = 700m
*.eNodeB2.mobility.initialY = 250m 
.eNodeB.mobility.initialX = 500m
*.eNodeB.mobility.initialY = 350m
# enable handover
**.cellularNic.phy.enableHandover = true
*.eNodeB*.cellularNic.phy.enableD2DCqiReporting = false
#

# X2 configuration
*.eNodeB*.numX2Apps = 3    # one x2App per peering eNodeB
*.eNodeB*.x2App[*].server.localPort = 5000 + ancestorIndex(1) # Server ports (x2App[0]=5000, x2App[1]=5001, ...)
*.eNodeB1.x2App[0].client.connectAddress = "eNodeB2%x2ppp0" 
*.eNodeB2.x2App[1].client.connectAddress = "eNodeB1%x2ppp0" 

**.vector-recording = true
**.avgServedBlocksDL*.vector-recording = true
**.servingCell*.vector-recording = true

**Comment by rhornig** [comment]
This is not an OMNeT++ issue. Should be reported/discussed on the project's repository (i.e. simu5g)
