### ISSUE TITLE
INI file error in OMNeT++ 6.0.3

### ISSUE THREAD

**Issue by rhornig** [omnetpp/omnetpp#1167]
### Discussed in https://github.com/omnetpp/omnetpp/discussions/1165

<div type='discussions-op-text'>

<sup>Originally posted by **pjpf** May 24, 2024</sup>
Hello,
I am using OMNeT++ 6.0.3 and it I have the following error:

Starting...
[...]
<!> Error: Syntax error in section heading, 'omnetpp.ini' line 1
[...]
End.
Simulation terminated with exit code: 1

Lien 1 in omnetpp.ini is: 
[General] 
network = MobilityShowcase
and it is not marked as an error !

By the way, I have a network which is called MobilityShowcase!

Please, help me !

Best regards.

--Paulo--</div>

**Comment by rhornig** [comment]
Ohh. This is indeed an issue. The config section header parser requires the LINE of a config header entry to end with ].  i.e. no space or comments are allowed at the end of the line...

**Comment by avarga** [comment]
Fixed in b41a689cf716f

**Comment by pjpf** [comment]
Thanks a lot !
