### ISSUE TITLE
qtenv: Executed `cEvent` subclasses don't have banners in the Qtenv log inspector

### ISSUE THREAD

**Issue by torokati44** [omnetpp/omnetpp#1169]
**Platform**
 - OMNeT++ version: 6.0.3
 - OS: Fedora 40

When a `cEvent` subclass is executed, it does not have its own banner in the Qtenv log inspector, like a `cMessage` subclass that was sent or scheduled does.
Also, all logging done in its `execute()` implementation looks like a system message _(such as the ones informing the user about entering/leaving express mode, or the end of the simulation)_, because there is no context component active at the time.

For example, this code snippet:

```c++
void MyEvent::execute() {
    EV_INFO << "MyEvent executed with target: " << (target ? target->getName() : "<nullptr>") << std::endl;
}

cObject *MyEvent::getTargetObject() const { return target; }

void Tester2::initialize() {
    EV_INFO << "Message from the Tester2 initialize." << std::endl;

    cEvent *ev = new MyEvent(nullptr);
    ev->setArrivalTime(SimTime(10, SIMTIME_MS));
    getSimulation()->getFES()->insert(ev);

    ev = new MyEvent(this);
    ev->setArrivalTime(SimTime(15, SIMTIME_MS));
    getSimulation()->getFES()->insert(ev);
}
```

Results in this log:

![image](https://github.com/omnetpp/omnetpp/assets/288816/517ad9ff-766a-49f1-b707-1cf6d8286687)

<details>
<summary>Expand for the text of the screenshot</summary>

```
Initializing module LogFormattingTest2.tester, stage 0
INFO (Tester2)LogFormattingTest2.tester: Message from the Tester2 initialize.
MyEvent executed with target: <nullptr>
MyEvent executed with target: tester
```

</details>

**Comment by torokati44** [comment]
I have a commit in an internal feature branch that makes the output of the snippet above look like this:
![image](https://github.com/omnetpp/omnetpp/assets/288816/1581a6e5-9669-4e4b-8cc2-d5590ac5c2a0)

**Comment by levy** [comment]
I tested this and it looks good. The event banner has 3 spaces after the timestamp though.

**Comment by torokati44** [comment]
> I tested this and it looks good.

Cool, thanks!

> The event banner has 3 spaces after the timestamp though.

Well, yeah, it has been like that for a good while now: https://github.com/omnetpp/omnetpp/commit/3d1115cca963b973b6430ae8a1adc98e12421467#diff-d946fdaaf17ee4198d16cdf34491668f9d981c8d70238f5580c5e281d2a0c876R1022-R1058
