### ISSUE TITLE
Easier generation of scalar plots

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#12]
**Reported by baumgart on 28 Nov 2008 14:57**

**Version:** 4.0b8

I&#039;m wondering if the beautiful new results analysis tool could be used to generate fast plots out of the scenario description in the ini file.

Take for example the following ini file with an additional [Plot] section:

[General]
repeat = 2
**.lifetimeMean = ${lifetime=1000s,10000s}

[Config ChordChurn]
**.overlayType = &quot;ChordModules&quot;
**.stabilizeInterval = ${stab=5s,20s}

[Config KademliaChurn]
**.overlayType = &quot;KademliaModules&quot;

[Plot ChurnComparison]
x = lifetime
y = &quot;*Sent Total Bytes*&quot;
lines = KademliaChurn, ChordChurn-stab=5s, ChordChurn-stab=20s

The idea is, that this could generate a plot with the input parameter &quot;lifetime&quot; on the x axes and the scalar matching the (unambiguous) string &quot;*Sent Total Bytes*&quot; on the y axes. The plot should contain three lines taking the results from the scenarios KademliaChurn and ChordChurn. Because the scenario ChordChurn has a second input parameter &quot;stab&quot;, it has to be specified, too.

The lines should represent the averages of all repetitions. The title and axes labels could be also generated from the plot (&quot;ChurnComparison&quot;, &quot;lifetime&quot;, &quot;Sent Total Bytes&quot;).

Maybe this can already be accomplished with the GUI of the results analysis tool, but probably is a lot more complicated than the ini file approach (at least I haven&#039;t found an easy way to do this with the GUI).

[Mantis Bugtracker #12](https://dev.omnetpp.org/bugs/view.php?id=12)

**Comment by rhornig** [comment]
The IDE in OMNeT++ 6.0 now comes with python support for generating charts so I'm closing this as this is no longer relevant.
