### ISSUE TITLE
OMNET SUMO VEINS EXAMPLE issue

### ISSUE THREAD

**Issue by mfatihkoc** [omnetpp/omnetpp#1214]
**Platform**
 - OMNeT++ version: [6.0.

 - OS: [Windows 11 Enterprise]

I run following:

C:\Users\me\Desktop\omnetpp> C:\Users\me\Desktop\veins-master\veins-master\sumo-launchd.py -vv -c 'C:\Program Files (x86)\Eclipse\Sumo\bin\sumo-gui.exe

But When I go omnet and run simulation, example is running in omnet but I see shell: C:\Program Files (x86)\Eclipse\Sumo\bin\sumo.exe is poping out only sumo is not coming 

and, I do see TCP port is listening or not in shell, pyhton script is coming only. 
![Screenshot (207)](https://github.com/user-attachments/assets/61f3146e-bf7d-4001-ae9e-0f55356792f1)
3]

**Comment by rhornig** [comment]
this is an issue (if at all) in veins so should be reported in veins issue tracker.
