### ISSUE TITLE
Minor UX inconvenience: The submodule filter button in the graphical NED editor is not intuitive

### ISSUE THREAD

**Issue by torokati44** [omnetpp/omnetpp#1222]
The filter button on the "Submodules" section header of the tool drawer in the graphical NED editor is hard to notice, is hard to tell what it does (no tooltip), and it's not intuitive what it does even after pressing it.

There is an attempt to add a (dummy) tooltip, but it unfortunately doesn't work: https://github.com/omnetpp/omnetpp/blob/23482d43991ccec9858a588141f1dc0a080a1252/ui/org.omnetpp.ned.editor/src/org/omnetpp/ned/editor/graph/GraphicalNedEditor.java#L908

Perhaps a different Draw2D Figure, or an actual SWT Widget would work better here.
Ideally, the same thing as what's used for the built-in "Pin" button in the same header.

See this user report: https://github.com/omnetpp/omnetpp/discussions/1221

**Comment by rhornig** [comment]
Probably changing to a SEARCH icon would help somewhat. Technically it is really 'filtering' but the filter icon is not really intuitive.
