### ISSUE TITLE
Icon set to default in task bar in Ubuntu 24

### ISSUE THREAD

**Issue by carlosmn25** [omnetpp/omnetpp#1234]
**Platform**
 - OMNeT++ version: 6.1/6.0.1
 - OS: Ubuntu 24.04

**Description**
I updated my system from Ubuntu 22.04 to Ubuntu 24.04 recently. I had OMNeT 6.0.1 installed. Several things broke apart, mainly graph-related, due to the change in python venvs, but it also affected the execution icon. The icon in the task bar is OMNeT++'s one, but it changes to the GNOME default icon (a gear) when the program is in execution, so it is hard to find sometimes and annoying. I updated OMNeT to version 6.1, and the problem is still there (the rest of the problems disappeared, though). I have made sure that the path to the icon in the .desktop file is correct.

OMNeT icon under execution:
![image](https://github.com/user-attachments/assets/27bbdac1-0384-4af2-888f-a9f1418f7da9)
OMNeT icon in task bar:
![image](https://github.com/user-attachments/assets/a28b3543-9bf4-4893-9c9b-746415856e91)

**To Reproduce**
This is my .desktop entry (NOTE: I know the IDE asks for the user not to launch the IDE from the desktop icon, but it is much more comfortable for me so I do it by launching the "omnetpp" command through bash. This may be affecting the issue):
`
[Desktop Entry]
Type=Application
Exec=bash -ci 'omnetpp'
Icon=/home/carlos/omnetpp-6.1/images/logo/logo128.png
Name=OMNeT++ 6.1 IDE
Categories=Development
`

I also set the environment in my .bashrc file so I can launch it easily:
`#OmNeT binary path
OMNET_VERSION="omnetpp-6.1"
#"omnetpp-6.0.1"
export PATH=$PATH:$HOME/$OMNET_VERSION/bin:$HOME/.local/bin
export SAURON_ROOT=$HOME/src/sauron
export OMNET_ROOT="$HOME/$OMNET_VERSION"
export PATH=$PATH:$OMNET_ROOT/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OMNET_ROOT/lib`

**Comment by rhornig** [comment]
Do you run in wayland shell? Wayland support for top level window icons is quite recent. Sadly I do not have prope rtop-level icons either.

**Comment by carlosmn25** [comment]
I'm using xorg, I stopped using wayland because it caused problems with Qtenv and with other programs. Anyway, I thought this was a problem with my OMNeT++ configuration, but know I see it's not. Thank you!
