### ISSUE TITLE
Running omnetpp error gate already connect

### ISSUE THREAD

**Issue by dion524** [omnetpp/omnetpp#1251]
![image](https://github.com/user-attachments/assets/e7425a80-e949-46bf-adc8-4af648f02c77)

Hello everyone.
I am trying to simulate the Mqtt protocol in order to measure its latency. The codes of the different files are compiled without error. After execution, the environment is displayed but an error is displayed as in the screenshot. Can someone help me?

**Comment by rhornig** [comment]
This is not a bugreport against OMNeT++ so I'm converting it to a discussion topic
