### ISSUE TITLE
Change opp_ide shebang to !#/bin/bash

### ISSUE THREAD

**Issue by kromkelet** [omnetpp/omnetpp#1259]
**Platform**
 - OMNeT++ version: 6.0.1, 6.0.3, 6.1
 - OS: Ubuntu 24, 22, 20, ...

**Describe the bug**
Your opp_ide launcher is working improperly from an application launcher, a quick launch and so on, causing "omnet the ide was not started properly environment variables have not been set properly..." pop-up after launch and IDE finish.

Launching of omnetpp involves opp_ide script which declares that it works under bash or zsh only.
However the shebang of this file declares #!/bin/sh
For a long time, in Ubuntu shell for #!/bin/sh launched not from an interactive terminal, uses dash instead of bash.
Please refer to https://wiki.ubuntu.com/DashAsBinSh

The simple change of opp_ide shebang to #!/bin/bash fixes the issue.

**To Reproduce**
Run install.sh on your Ubuntu and then launch OMNeT IDE from a start menu, not a shell console.

**Comment by rhornig** [comment]
Thanks. I've also run into this issue. Unfortunately only after the 6.1.0 release. Already added a fix (just like you suggested) on the 6.x branch but that will come only with 6.1.1 (the fix also needed in the backward compatibility `omnetpp` script (as that is also sourcing the opp_ide command)
