### ISSUE TITLE
Python3-dev not found when running ./configure

### ISSUE THREAD

**Issue by novasup666** [omnetpp/omnetpp#1261]
**Platform**
 - OMNeT++ version: 6.1.0
 - OS: Pop-os 22.04 LTS (based on ubuntu)

When i try to install omnet++, everything goes just fine until i run ./configure where i get the following error : 

checking for python3-dev with CFLAGS="-I/usr/include/python3.10 -I/usr/include/python3.10" LIBS="-L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -lpython3.10 -lcrypt -ldl  -lm -lm "... no
configure: error: Python support was configured (WITH_SCAVE_PYTHON_BINDINGS=yes), but the Python 3 development package was not found.

I followed the installation steps from InstallGuide.pdf (especially the part on ubuntu dependencies, as pop-os is based on ubuntu) then run install.sh (which runs ./configure ) and this error pops. PLEASE HELP (I have to use Omnet++ for uni)

**Comment by rhornig** [comment]
For ubuntu (and other debian based distros) the 6.1.0 install.sh is slightly bogus. Please install 'python3-dev' manually before executing ./install.sh

Alternatively, just replace `libpython3-dev` with `python3-dev` in the `install.sh` script and restart it again.

**Comment by novasup666** [comment]
Hi, a friend of mine recommended to install libstd++-12-dev and it seems to work.
Thank you for your answer
