### ISSUE TITLE
user-interface = "Qtenv" in General section causes crash

### ISSUE THREAD

**Issue by adamgeorge309** [omnetpp/omnetpp#1271]
**Platform**
 - OMNeT++ version: master (6.1)
 - OS: Ubuntu 24.10

`user-interface = "Qtenv"` in any simulation causes a crash. Tested in INET.

**Comment by avarga** [comment]
Fixed by def09b8ef0 ("sim: fix read config options before having a cSimulation causing crash; fixes #1271", 2024-12-13)

**Comment by torokati44** [comment]
Just to cross-reference: The final commit after rebasing is https://github.com/omnetpp/omnetpp/commit/3de71820557148655d0e65b1af0496d0b1c7c44a.
