### ISSUE TITLE
configure aborts with 'rm: cannot lstat 'conftest.exe': Permission denied on Windows 7

### ISSUE THREAD

**Issue by rhornig** [omnetpp/omnetpp#140]
**Reported by baumgart on 22 Apr 2010 15:05**

I tried to compile the latest omnetpp-4.1b4 on Windows 7. Running ./configure in the MinGW terminal gave several of the following errors:

rm: cannot lstat &#039;conftest.exe&#039;: Permission denied

Since configure doesn&#039;t finish, I&#039;m unable to compile omnetpp-4.1b4.

[Mantis Bugtracker #154](https://dev.omnetpp.org/bugs/view.php?id=154)

**Comment by prool** [comment]
it helped me too in another project

i turned on 'application experience service' on Windows7

and configure worked! :)

(your diskussion i found by google search)
