### ISSUE TITLE
Load NED files from a zip file

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#142]
**Reported by andras on 23 Apr 2010 17:05**

When a zip file occurs in the NEDPATH, the simulator could interpret it as a folder, and read NED files from it. It would be analogous to Java&#039;s jar files. This feature would simplify deploying a simulation on other machines.

[Mantis Bugtracker #156](https://dev.omnetpp.org/bugs/view.php?id=156)

**Comment by rhornig** [comment]
opp_nedtool now can generate C++ code that embeds the NED files and can be linked into the executable.
