### ISSUE TITLE
Line and legend is wrong when multiple result items are plot with the same names

### ISSUE THREAD

**Issue by levy** [omnetpp/omnetpp#144]
**Reported by levy on 26 Apr 2010 11:52**

**Version:** 4.1b3

When multiple vectors are plotted and some of them has the exact same module and result item name, then the legend and the line attributes becomes wrong. This happens because the default algorithm to select the display id fields is wrong. The selected display id does not differentiate between all of the result items. Make sure that it always does so even if it needs to include the result item index or the result item id.

[Mantis Bugtracker #159](https://dev.omnetpp.org/bugs/view.php?id=159)

**Comment by torokati44** [comment]
This no longer happens in the new analysis tool in 6.0.
