### ISSUE TITLE
simulation stop after executing 100 runs with "Cannot open scalar file" error

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#151]
**Reported by jeromerousselot on 4 Jun 2010 12:45**

**Version:** 4.1b4

This happens with Omnet 4.1 rc2 on Ubuntu 10.04 x64.
I have a [General] configuration with some iteration variables.
The simulation is start with a script that calls opp_run, and I do not specify the number of runs. It should run all of them.
The simulations start, until reaching run 101. At the end of that run, I get:

&lt;!&gt; Error in module (wisemac) sim.host[0].nic.mac (id=20): Cannot open output scalar file `results/General-102.sca&#039;.

Restarting the run specifically with -r 102 leads to a successful execution, and correct file generation. I have 50 GB of free space on that partition.

More interestingly, when trying to run the remaining simulations with -r 102-269, i obtain at run 202:

&lt;!&gt; Error in module (wisemac) sim.host[0].nic.mac (id=20): Cannot open output scalar file `results/General-202.sca&#039;.

I did not try to reproduce this with other modules, so there may be a problem with my code. However, I did not modify this c++ code for some time and it used to work with previous versions of omnet.

[Mantis Bugtracker #167](https://dev.omnetpp.org/bugs/view.php?id=167)

**Comment by sadatemurekezi** [comment]
#include <omnetpp.h>

using namespace omnetpp;

class My_Node: public cSimpleModule
{
protected:
    void initialize() override;
    void handleMessage(cMessage *msg) override;
};

Define_Module(My_Node);

void My_Node::initialize()
{
    if (strcmp("Computer1", getName()) == 0) {
        cMessage *msg = new cMessage("Hey Sadate");
        send(msg, "output_gate");
    }
}

void My_Node::handleMessage(cMessage *msg)
{
    if (strcmp("Computer1", getName()) == 0) 
}
  
    else {
        send(msg, "output_gate");
    }

Iam tying to run this in Omnet++ , the message run in zero second it mean ith does pass from node 1 to node2 . Helpe to fixed it.
