### ISSUE TITLE
Cut & Past does not work in browse data filter input line

### ISSUE THREAD

**Issue by rhornig** [omnetpp/omnetpp#152]
**Reported by tobias on 9 Jun 2010 09:44**

The Ctrl-X, Ctrl-V, Ctrl-C key as of no effect when selecting text in the filter input line of the browse data tab in the result analysis. Marking text and selecting Copy, Paste, Insert from the context menu works.

**Steps to reproduce:** Mark text in the filter input line of the browse data tab in the result analysis and press Ctrl-C. The text is not transferred to the clipboard.

[Mantis Bugtracker #168](https://dev.omnetpp.org/bugs/view.php?id=168)

**Comment by torokati44** [comment]
This works now in 6.0.
