### ISSUE TITLE
Path to "doxy.cfg" is not saved

### ISSUE THREAD

**Issue by levy** [omnetpp/omnetpp#189]
**Reported by karl_wessel on 15 Oct 2010 12:01**

**Version:** 4.1

If one sets another path than the base directory for the &quot;doxy.cfg&quot; file under &quot;Properties-&gt;OMNeT++-&gt;Documentation Generator&quot; the change is saved for the workspace but doesn&#039;t seem to be saved for the project itself because if one imports all of the project files into another workspace the path to the doxy.cfg file is back to the default again.
This way one has to set the doxy.cfg path manually each time the project is cloned/copied/etc.

How to reproduce this problem:
- create a new empty omnet++ project
- change its doxy.cfg path to something else (Properties-&gt;OMNeT++-&gt;documentation generator)
- export the project into an archive (File-&gt;Export...-&gt;General-&gt;Archive file)
- delete the project
- import the just exported archive (File-&gt;import..-&gt;existing projects into workspace&quot;
- the path to the doxy.cfg should be back to the default value

[Mantis Bugtracker #211](https://dev.omnetpp.org/bugs/view.php?id=211)

**Comment by rhornig** [comment]
Sadly the dialog's persistent storage is not project specific. The persistence could be viewed as a helper mechanism. omnet 6 will contain command line neddoc generator, so for multiple projects it is advised to use command line generation where you can specify the parameters for each project on the command line.
