### ISSUE TITLE
NED: strange color property editor behavior

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#204]
**Reported by andras on 15 Dec 2010 14:55**

**Version:** 4.1

Using mouse to select a color in the content assist of a color property editor sometimes produces confusing behavior. 

**Steps to reproduce:** 1. Open a NED file, and select something in it (a submodule, a connection, etc.)
2. Open the Properties view, find an unset color property, and click into it
3. Hit Ctrl+Space, and DOUBLE-CLICK a color in the content-assist list
4. Result: property editor apparently loses focus but remains empty! However, if you click any other property in the list, the selected color will be written back into the color property and the change also takes effect in the graphics. 

The result is not consistent: sometimes the selected text is properly inserted in the property editor and it retains focus. In that case, do this before step 3: bring up the color selection dialog with the &quot;...&quot; button then cancel it without selecting anything. This will trigger the above wrong behavior.

Observed both on Win7 and Linux.

[Mantis Bugtracker #228](https://dev.omnetpp.org/bugs/view.php?id=228)

**Comment by rhornig** [comment]
No longer present. tested on OMNeT++ 5.5
