### ISSUE TITLE
Predefined layouts (matrix, ring, etc) don't work in the animation

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#234]
**Reported by andras on 2 Mar 2011 16:15**

**Version:** 4.2b1

Layouts specified in the display string (e.g. matrix, @display(&quot;p=100,100,m&quot;)) are not obeyed.

[Mantis Bugtracker #264](https://dev.omnetpp.org/bugs/view.php?id=264)

**Comment by rhornig** [comment]
Animation player is dropped.
