### ISSUE TITLE
Comparing pointers is often wrong

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#246]
**Reported by jesjones on 20 Apr 2011 19:34**

**Version:** 4.1

It&#039;s fairly common for modules to have things like a std::map of pointers to some value. Unfortunately this can cause non-determinism between runs because objects can be allocated at different locations depending on things like the environment used. And if the behavior of the simulation changes depending on the order in which elements are processed the simulation will not behave the same.

Omnet itself doesn&#039;t seem to suffer much from this problem, but other packages do (e.g. inet). The enclosed patch attempts to address this by adding a std::less partial specialization for pointers which will cause compiler errors if it is instantiated and by adding a ComparePointers struct that can be used if you think it is OK to compare pointers.

[Mantis Bugtracker #278](https://dev.omnetpp.org/bugs/view.php?id=278)

**Comment by rhornig** [comment]
I'm closing this as this should be handled with linters and other static analysis tools instead,
