### ISSUE TITLE
OMNEST: "systemc-embedding" does not compile from the IDE

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#379]
**Reported by andras on 5 Jan 2012 12:13**

**Version:** 4.2.1

C1083: Cannot open include file: &#039;systemc.h&#039;: No such file or directory	

Indeed there isn&#039;t any SystemC header under include/. Is it supposed to be there?

[Mantis Bugtracker #505](https://dev.omnetpp.org/bugs/view.php?id=505)

**Comment by rhornig** [comment]
This is now precompiled on Windows.
