### ISSUE TITLE
MATLAB export output completely broken, CSV output largely useless

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#417]
**Reported by andras on 14 Mar 2012 22:57**

**Version:** 4.2

Issue affects both scavetool and the IDE.

MATLAB export was removed from the UI in 4.2.2, but that&#039;s not a solution.

Both CSV and MATLAB outputs (i.e. MATLAB after fixing errors in the generated script) are nearly unusable: even the most basic contextual information about the exported numbers (i.e. module name, statistic name, and some (any!) identification of the simulation run) is missing, so it is nearly impossible to process the exported data in a sensible way. Judging from the state of the previous two, Octave output is likely broken too.

Both exports have to be reimplemented from scratch, starting from creating a SPECIFICATION for the exported files. Special care must be taken that exported data 
  1) are ORGANIZED LOGICALLY, and 
  2) data exported should have CONTEXTUAL INFORMATION so that export is
     REVERSIBLE, i.e. it must be possible (at least conceptually) to write an
     importer that puts back the same data into OMNeT++ scalar/vector files
     to the right place.

File format limitations of CSV (i.e. a file contains a single table) must be overcome by restricting export to HOMOGENOUS data (scalars-only, vectors-only, histograms-only), and offering EXPORT OPTIONS. Ie. when exporting scalars, the user must be able to select the columns to be created (e.g. runid+module+name+value, or configname+runnumber+module+name+value, etc.)

Specification must be reviewed by ALL members of the company before going to implementation.

The format of exported files MUST BE DOCUMENTED in the OMNET++ MANUAL, and must later be treated as external interface (i.e. stay backward compatible).

[Mantis Bugtracker #553](https://dev.omnetpp.org/bugs/view.php?id=553)

**Comment by torokati44** [comment]
The analysis tool, including export, has been completely reimplemented in 6.0.
