### ISSUE TITLE
truncnormal() sometimes returns INFINITY

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#43]
**Reported by baumgart on 13 Jan 2009 13:40**

**Version:** 4.0rc1

truncnormal() sometimes returns infinity

With a propability of 2^32 genk_dblrand(rng) returns 0. In this case normal() returns infinity (log(0)).

This probably effects other distribution functions with use log() as well.

[Mantis Bugtracker #43](https://dev.omnetpp.org/bugs/view.php?id=43)

**Comment by Moonshineee** [comment]
the erlang_k distribution is also affected. (returns an inf)
