### ISSUE TITLE
A command line option to specify excluded ned packages

### ISSUE THREAD

**Issue by rhornig** [omnetpp/omnetpp#434]
**Reported by rhornig on 5 Jun 2012 15:45**

**Version:** 4.2.2

It would be great to have a command line for this. Sometimes modules contain errors or they refer to types that are not available. this causes a problem for example when a module&#039;s base type is not present in the current ned path. (Submodule types may missing as they would cause trouble only if the module is instatiated, but base types are always required to be valid)

[Mantis Bugtracker #577](https://dev.omnetpp.org/bugs/view.php?id=577)

**Comment by torokati44** [comment]
I believe this is fixed by https://github.com/omnetpp/omnetpp/commit/094d8b9d9af173e6f758a8e0cfebaca901e7c133

**Comment by rhornig** [comment]
Already implemented as the -x option.
