### ISSUE TITLE
Dataset page side toolbar buttons have no effect without selection

### ISSUE THREAD

**Issue by levy** [omnetpp/omnetpp#441]
**Reported by levy on 28 Aug 2012 13:56**

**Version:** 4.2.2

If there&#039;s no selection then clicking a button does nothing. The buttons should be disabled if they have no effect.

[Mantis Bugtracker #588](https://dev.omnetpp.org/bugs/view.php?id=588)

**Comment by rhornig** [comment]
obsolete. 6.0 has new analysis plugin.
