### ISSUE TITLE
chart name is not accessible in the Properties view

### ISSUE THREAD

**Issue by rhornig** [omnetpp/omnetpp#445]
**Reported by tomi on 4 Sep 2012 13:12**

If you want to change the name of the chart, you have to open the &#039;Properties...&#039; dialog, which is inconvenient when you rename charts in bulk.

[Mantis Bugtracker #592](https://dev.omnetpp.org/bugs/view.php?id=592)

**Comment by torokati44** [comment]
This no longer applies to 6.0 with the rewritten analysis tool.
