### ISSUE TITLE
Not possible to sort the rows of the BrowseData page according to two columns (by lexicographic ordering)

### ISSUE THREAD

**Issue by rhornig** [omnetpp/omnetpp#490]
**Reported by tomi on 10 Jun 2013 09:08**

If the heading of column B is clicked, after then the heading of column A is clicked, then the rows should be sorted by A, and rows having the same A value should be sorted by B.

Now, after sorting the rows by A causes the B values to be unordered.

[Mantis Bugtracker #657](https://dev.omnetpp.org/bugs/view.php?id=657)

**Comment by torokati44** [comment]
Sorting `IDList`s is now done with `std::stable_sort`, which fixes this.
