### ISSUE TITLE
std::bad_alloc error happens when several MB .sca files are processed in .anf file to get a chart such as bar or scatter ones

### ISSUE THREAD

**Issue by rhornig** [omnetpp/omnetpp#553]
**Reported by shahrokh6814 on 14 Feb 2014 11:35**

**Version:** 4.4

I have written a project to simulate routings in WSNs within the MiXiM framework. I have some (about 40) scalar result files of the size 3.8 MB. When I want to get the charts from the .anf file, instead of showing the charts, the std::bad_alloc error is being shown to me.
After reproducing the problem with the Tictoc scenario, I found that the problem happens when the size of .sca files become a little large. Ergo, I would be very appreciated if it get resolved, or at least I would be given some guidance upon how to pass that error.
I attach the sample scenario that I have made with the Tictoc.
With great regards,
Shahrokh Bahtooei

**Additional information:** I use Windows 7, OMNeT 4.4 (also had this problem in OMNeT 4.2.2).

[Mantis Bugtracker #731](https://dev.omnetpp.org/bugs/view.php?id=731)

**Comment by torokati44** [comment]
Analysis tool was reimplemented in 6.0, reopen if still applies.
