### ISSUE TITLE
Stopping a running simulation batch doesn't work

### ISSUE THREAD

**Issue by levy** [omnetpp/omnetpp#608]
**Reported by levy on 14 Jan 2015 09:35**

**Version:** 4.6

Clicking the red stop button on the progress view doesn&#039;t stop the running simulation batch.

[Mantis Bugtracker #805](https://dev.omnetpp.org/bugs/view.php?id=805)

**Comment by rhornig** [comment]
Fixed in omnet 5.4 and later.
