### ISSUE TITLE
improper parsing of tkenv-image-path

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#64]
**Reported by johnnie on 12 Apr 2009 06:10**

The paths parsed from the tkenv-image-path command from the ini file are not correctly added to the set of image paths omnet uses. The current workaround is to include a semi-colon in front of the first path. Otherwise, my guess is the first path under tkenv-image-path gets concatenated to something else, creating an invalid path.

[Mantis Bugtracker #64](https://dev.omnetpp.org/bugs/view.php?id=64)

**Comment by rhornig** [comment]
Tkenv is no longer supported.
