### ISSUE TITLE
Missing "No more events --- simulation ended" message in Run mode

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#696]
**Reported by andras on 24 Feb 2017 08:58**

**Version:** 5.1pre3

When I have a simulation with (e.g.) 20 events to simulate, OMNeT++ 5.0 would display a dialog &quot;No more events --- simulation ended at event xy...&quot; and instantly call the finish() method(s).

OMNeT++ 5.1pre3 just stops the simulation. There is no dialog or notification until you start the simulation once again, when the &quot;No more events --- simulation ended ...&quot; dialog pops up and finish() is executed.

This applies to Run mode (not Fast or Express) in Qtenv only (Tkenv is OK), when no simtime limit is set.

Reported by Michael Kirsche.

[Mantis Bugtracker #999](https://dev.omnetpp.org/bugs/view.php?id=999)

**Comment by rhornig** [comment]
works now.
