### ISSUE TITLE
Configuration option "cmdenv-config-name" is ignored

### ISSUE THREAD

**Issue by rhornig** [omnetpp/omnetpp#705]
**Reported by paolinux on 4 May 2017 16:05**

**Version:** 5.1

Since moving to 5.1, the configuration option to indicate the default config to run, cmdenv-config-name, does not seem to be working any longer.

**Steps to reproduce:** In the dyna sample, add 

cmdenv-config-name=Medium

to omnetpp.ini and then run the command

./dyna -u Cmdenv

the General config (rather than &quot;Medium&quot;) gets executed

[Mantis Bugtracker #1008](https://dev.omnetpp.org/bugs/view.php?id=1008)

**Comment by rhornig** [comment]
indeed, it seems `Cmdenv::doRun()` overrides the `configName` option with default value without checking if that was already specified in the INI file.

**Comment by avarga** [comment]
Fixed 6.0.1
