### ISSUE TITLE
Add a new inspector (specifically to the properties view) that shows the packet data if a packet is selected

### ISSUE THREAD

**Issue by levy** [omnetpp/omnetpp#720]
**Reported by levy on 21 Nov 2017 12:57**

**Version:** 5.2

Quite often the user wants to see the actual contents of a packet. The current inspectors show a lot of other technical data such as sender module, etc. This makes it pretty difficult to focus on what is actually present in the packet. The user interface should be able to show a packet strictly focusing only on its contents, that is the data carried by the packet over the wire.

Suggestion: we could annotate descriptors with @packetData properties and the special cPacket inspector could filter fields based on that. The default @packetData value would be specified on the class but it could be overridden with a @packetData on the field.

[Mantis Bugtracker #1024](https://dev.omnetpp.org/bugs/view.php?id=1024)

**Comment by rhornig** [comment]
Present in omnet 5.4+
