### ISSUE TITLE
Queue and PassiveQueue modules of "queueinglib" wrong statistics collection

### ISSUE THREAD

**Issue by rhornig** [omnetpp/omnetpp#736]
**Reported by vallejo on 30 May 2018 12:29**

**Version:** 5.3

Queue and PassiveQueue modules incorrectly collect statistics for 0 messages situation.

In Queue::handleMessage, the empty queue situation is handled with the following code:

```
if (queue.isEmpty()) {
    jobServiced = nullptr;
    emit(busySignal, false);
}
```

With this code, the statistics for 0 messages situation are not correctly collected, affecting also the histogram.

A possible solution is to emit the proper signal:

```
if (queue.isEmpty()) {
    jobServiced = nullptr;
    emit(busySignal, false);
    emit(queueLengthSignal, 0);   /* Proposed solution */
}
```

The same problem occurs in PassiveQueue:

```
else if (length() == 0) {
    // send through without queueing
    sendJob(job, k);
}
```

could be changed to:

```
else if (length() == 0) {
    // send through without queueing
    emit(queueLengthSignal, 0);   /* Proposed solution */
    sendJob(job, k);
}
```

[Mantis Bugtracker #1040](https://dev.omnetpp.org/bugs/view.php?id=1040)

**Comment by rhornig** [comment]
Queue length change statistics should be reported ONLY if the queue length is actually changing and the signal is correctly emitted after all insert and pop operation of the queue. The recommended change would report 0 length signal several times even if the queue length stays at 0, but a message processing has finished. The number of times the signal is reported should be the same as the times the queue length changed and not the times a message was processed. This change is not needed.

**Comment by JA-Vallejo** [comment]
If you apply the criteria of only signaling changes in queue length, the results given by OMNeT++ are not coherent with the ones generated by other queueing software, nor with the queueing theory in general. For that you must record every single time the queue is empty, as is perfectly normal that the queue length stays at 0 after processing a message (job), mostly if the service rate is much larger than the arrival rate. If you don't record those 0 values properly, the answer to a question like: what is the probability of having 0 users at the queue? would be fundamentally wrong.

The results given by OMNeT++ have been compared with:

QtsPlus (by Donald Gross, author of "Fundamentals of Queueing Theory", one relevant book about the subject). This software doesn't use simulation but gives an exact solution for many queue models.

Java Modelling Tools (JMT), a suite of applications developed by Politecnico di Milano and Imperial College London. This software solves the queueing problems by simulation, and with a large enough number of samples gives roughly the same results as QtsPlus and the formulas of the queueing theory.

I don't know if the proposed solution can have unwanted side effects (don't know the inner workings of OMNeT++ that well), but once applied to OMNeT++, the results given by the simulation are very similar to the ones generated by those applications (and the formulas of the queueing theory) in the limited tests I have done, basically with MM1 and MMc queue models.
