### ISSUE TITLE
ANSI text styling

### ISSUE THREAD

**Issue by rhornig** [omnetpp/omnetpp#738]
**Reported by ManiAm on 5 Jun 2018 15:29**

**Version:** 5.3

Qtenv log viewer supports ANSI control sequences for text styling, but apparently this feature is missing in the sequence chart.
![2018-06-03_21-19-15](https://user-images.githubusercontent.com/40529/49438486-c540b800-f7be-11e8-9de0-26fb514806bc.png)

[Mantis Bugtracker #1042](https://dev.omnetpp.org/bugs/view.php?id=1042)

**Comment by torokati44** [comment]
The current standpoint is that we will simply strip these control sequences out of the text in this table, ignoring them. It is still better than having them in there in their raw form. This "fix" is in an internal topic branch.
