### ISSUE TITLE
The image-path config cannot be merged with --image-path command line argument

### ISSUE THREAD

**Issue by levy** [omnetpp/omnetpp#740]
**Reported by levy on 15 Jun 2018 11:41**

In INET, if an example contains specific images in its folder, then there&#039;s no way of specifying the &#039;image-path&#039; in the omnetpp.ini, because the default INET &#039;--image-path&#039; command line argument overrides it.

It would be nice to have a way of saying ${next} or something like that to refer to the value of the next applicable configuration entry. This would allow one to write &#039;--image-path=${next};bar&#039; in the command-line and &#039;image-path=foo&#039; in omnetpp.ini resulting in the &#039;foo;bar&#039; image path.

[Mantis Bugtracker #1044](https://dev.omnetpp.org/bugs/view.php?id=1044)

**Comment by avarga** [comment]
Resolved in version 6.0. From the WHATSNEW:

```
  - There were also several improvements related the image path. The `-i <imgpath>`
    option command-line option has been added. It may occur multiple
    times. The image path is now defined jointly by the `OMNETPP_IMAGE_PATH`
    environment variable, `-i` command-line options, and the `image-path`
    configuration option. `./bitmaps` was removed from default image path, as it
    was virtually unused. The default value `./images` now comes from the
    default value of the image-path configuration option.
```
