### ISSUE TITLE
opp_runall dumps Python stack trace instead of proper, human-readable error reporting

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#741]
**Reported by andras on 19 Jun 2018 16:48**

**Version:** 5.4

Example: trying to run a nonexistent program ./foo:

$ opp_runall ./foo
Traceback (most recent call last):
  File &quot;/home/andras/projects/omnetpp/bin/opp_runall&quot;, line 218, in &lt;module&gt;
    tool.run()
  File &quot;/home/andras/projects/omnetpp/bin/opp_runall&quot;, line 64, in run
    runNumbers = self.resolveRunNumbers(opts.simProgArgs)
  File &quot;/home/andras/projects/omnetpp/bin/opp_runall&quot;, line 115, in resolveRunNumbers
    output = subprocess.check_output(tmpArgs)
  File &quot;/usr/lib/python2.7/subprocess.py&quot;, line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File &quot;/usr/lib/python2.7/subprocess.py&quot;, line 711, in __init__
    errread, errwrite)
  File &quot;/usr/lib/python2.7/subprocess.py&quot;, line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

The expected output would be something like this: 
&quot;Error running simulation: ./foo: No such file or directory&quot; (and no stack trace)

[Mantis Bugtracker #1045](https://dev.omnetpp.org/bugs/view.php?id=1045)

**Comment by rhornig** [comment]
fixed in 5.5.
