### ISSUE TITLE
The IDE can't load .vec file because it cannot tokenize lines longer than 1023

### ISSUE THREAD

**Issue by adamgeorge309** [omnetpp/omnetpp#755]
**Platform**
 - OMNeT++ version: 5.4.1
 - OS: Ubuntu 18.04

Parameters and  their values are included in .vec files. If the parameter value is too long, the IDE can't load the .vec file. (It can load it if I manually remove the parameter from the .vec file)

**Comment by torokati44** [comment]
Fixed internally.

**Comment by mustansarsaeed** [comment]
Hi @adamgeorge309 @torokati44 ,

I am also facing this issue. I have scalars and vector files but IDE is showing this error. How can I resolve this? I am unable to generate dataset/graphs . Please help

**Comment by torokati44** [comment]
The commit that fixes this is now public: https://github.com/omnetpp/omnetpp/commit/0457b4981f7a369174c2c91507624ac0c14ad05f

I do not recommend you switch to the master branch of OMNeT++, but this patch applies to the 5.4.1 release sources (and likely many earlier versions too) without conflicts.

You can download the diff/patch file from [here](https://github.com/omnetpp/omnetpp/commit/0457b4981f7a369174c2c91507624ac0c14ad05f.diff) or [here](https://github.com/omnetpp/omnetpp/commit/0457b4981f7a369174c2c91507624ac0c14ad05f.patch), respectively, then and apply it with the `patch` utility, in the OMNeT++ root:

`patch -p 1 -i 0457b4981f7a369174c2c91507624ac0c14ad05f.diff`

**Comment by torokati44** [comment]
After applying the patch, make sure to rebuild OMNeT++ (starting from `make`), and *additionally* rebuild the native library parts for the IDE, by running `make ui`. You will have to install `swig` for this to work.
