### ISSUE TITLE
Horizonal scrolling in either the Scave charts or the Sequence Chart renders some garbage on the revealed area

### ISSUE THREAD

**Issue by levy** [omnetpp/omnetpp#758]
Dragging the chart with the mouse and scrolling horizontally sometimes draw garbage on the revealed area. Press refresh to redraw the chart to see if it changes. Using OMNeT++ 5.4, Ubuntu 18.10

**Comment by torokati44** [comment]
This seems like a bug in the GTK3 backend of SWT (using Cairo).
Currently tracking [Eclipse Bug 545226](https://bugs.eclipse.org/bugs/show_bug.cgi?id=545226).

**Comment by torokati44** [comment]
The previously linked Eclipse Bug was fixed, but it does not resolve the issue.
The actual cause was since found, and a new Bug Report was submitted: [549626](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549626)

**Comment by torokati44** [comment]
Until 549626 is fixed, a workaround was applied, the glitches are now mostly gone.
