### ISSUE TITLE
No source available for "inet::MACBase::isNodeUp() at 0x6badef83"

### ISSUE THREAD

**Issue by Marconi666** [omnetpp/omnetpp#760]
**Platform**
 - OMNeT++ version: [e.g. 5.0]
 - OS: [win7-x86]

**Describe the bug**
release-run ::
Simulation terminated with exit code: -1073741819...
debug as:
![image](https://user-images.githubusercontent.com/27673304/56215409-3b6cf980-6092-11e9-8482-f8b9bb50d39e.png)

thanks!

**Comment by Marconi666** [comment]
inet 3.4.0

**Comment by rhornig** [comment]
This is a crash in INET, not related to the OMNeT++ code.
