### ISSUE TITLE
IDE start fails for Ubuntu 19.04

### ISSUE THREAD

**Issue by weinrank** [omnetpp/omnetpp#762]
**Platform**
 - OMNeT++ 5.4.1
 - Ubuntu 19.04

**Describe the bug**
The IDE does not start.
Already tried with a fresh copy of of the software and a clean workspace directory.

```
An error has occurred. See the log file
/home/weinrank/omnetpp/samples/.metadata/.log.
```

**To Reproduce**
* Compile OMNeT++ 5.4.1
start IDE by calling `omnetpp`

![image](https://user-images.githubusercontent.com/6726222/57365151-d4b89880-7184-11e9-99aa-e9c9e02934ec.png)

**Comment by mmodenesi** [comment]
If the log says something about:

    java.lang.NoClassDefFoundError: javax/annotation/PreDestroy

This [workarround](https://stackoverflow.com/questions/54093703/omnet-5-4-1-running-error-on-ubuntu-18-10-after-succesfull-installation) did the trick for me.

I am using:

- OMNeT++ 5.4.1
- openjdk 11.0.3 2019-04-16 (relevant for the Eclipse editor)
- Ubuntu 19.04

**Comment by rhornig** [comment]
Yes, the Ubuntu repo has updated it's JDK to v11 and Java11 and Eclipse 4.7 (which is inside OMNET 5.4) broke compatibility. We will release OMNeT++ 5.5 with a new version of Eclipse which will solve this issue until then the mentioned workaround should be used.
