### ISSUE TITLE
cancelAndDelete Method

### ISSUE THREAD

**Issue by swiru95** [omnetpp/omnetpp#764]
**Platform**
 - OMNeT++ version: 5.4.1
 - OS: Ubuntu 18.04 LTS

**Describe the bug**
Hello, I dont really know if it is good not to set deleted object's pointer cMessage in cancelAndDelete(cMessage* msg) to nullptr 0x0, it causes a lot of problems in bigger projects. I think it should be done this way.

**To Reproduce**
Just add line 
msg=nullptr;
at the end.

**Comment by rhornig** [comment]
The `msg` pointer is taken by value, so setting it to `nullptr` at the end of the method would have **no** effect at all on the caller site anyway (in fact it would be a no-operation).
