### ISSUE TITLE
Use Academic Public License for personal student projects?

### ISSUE THREAD

**Issue by chrismessiah** [omnetpp/omnetpp#767]
Hi,

I recently graduated and have a couple of school-related software projects which I would like to release for noncommercial settings in a similar fashion as described by your Academic Public License. 

Is the Academic Public License itself released under a license which allows me to use it? Are there any conditions under which I may use the license such as attribution?

Thanks!

**Comment by rhornig** [comment]
The license is in public domain. Feel free to tailor it to your needs.
