### ISSUE TITLE
Database lock for Sqlite

### ISSUE THREAD

**Issue by admaio** [omnetpp/omnetpp#773]
I have tried to store the results of several simulations for a parameter study in a single .sca and .vec files:

`output-vector-file = ${configname}/v.vec`
`output-scalar-file = ${configname}/s.sca`

using the Sqlite manager:

`outputvectormanager-class="omnetpp::envir::SqliteOutputVectorManager"`
`outputscalarmanager-class="omnetpp::envir::SqliteOutputScalarManager"`

but the simulations crash and return the message:

`<!> omnetpp::common::opp_runtime_error: SQLite error 'database is locked' on file '/home/..../s.sca'`

The issue is solved by redirecting the scalar output of each simulation in a separate .sca file, while still redirecting the vector outputs in a single .vec file for all the simulations.

Why does the database lock issue happen only for .sca files? How can it be fixed so that manual merge of the databases contained in all the .sca files can be avoided?

Thanks.

(System: OMNeT++ 5.5, Ubuntu 16.04.6 LTS)

**Comment by avarga** [comment]
I am unable to reproduce this with either omnetpp-5.5.1 or omnetpp-devel (current master branch), on Ubuntu 18.04 LTS.

I tried the following:

    cd samples/aloha
    ./aloha_dbg omnetpp.ini _sqlite.ini -c PureAlohaExperiment -u Cmdenv

where _sqlite.ini was:

    outputvectormanager-class = omnetpp::envir::SqliteOutputVectorManager
    outputscalarmanager-class = omnetpp::envir::SqliteOutputScalarManager
    output-scalar-file-append = true
    output-scalar-file = "results/General.sca"

It run through without error, and produced a correct SQLite General.sca file.

**Comment by admaio** [comment]
Sorry for the late reply. The issue arises when several simulations are launched in parallel and they all try to write on a single SQLite database. According to [this](https://www.sqlite.org/faq.html#q5) link, this might be the issue.

For example, the aloha scenario you mentioned crashes when this command

`opp_runall -j10 -b1 ./aloha_dbg omnetpp.ini -m -c PureAlohaExperiment -u Cmdenv`

is launched on a system with these characteristics:

OS: CentOS 7.8.2003.x86_64
Processor: 24x Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz
Kernel: 3.10.0-1127.19.1.el7.x86_64
Memory: 62.73 GiB

and adding the following lines to the General section of the ini file:

```
outputvectormanager-class = omnetpp::envir::SqliteOutputVectorManager
outputscalarmanager-class = omnetpp::envir::SqliteOutputScalarManager
output-scalar-file-append = true
output-vector-file-append = true
output-scalar-file = "results/General.sca"
output-vector-file = "results/General.vec"
```

with the following error in the file `results/PureAlohaExperiment-numHosts=10,iaMean=5-#1.out` (and several others):

```
<!> Error: SQLite error 'database is locked' on file
'.../omnetpp-5.6.2/samples/aloha/results/General.vec' while processing statistic signal
channelState (id=2) with data type long, emitted from (aloha::Server)Aloha.server -- in module (aloha::Server)
Aloha.server (id=2), during network initialization
```

Thanks.

**Comment by rhornig** [comment]
Sqlite database files are not meant to be used by multiple processes. You should use a different database file for each run.
