### ISSUE TITLE
Incorrect probability density and cumulative density charts based on a weighted histogram (values > 1 !)

### ISSUE THREAD

**Issue by H828** [omnetpp/omnetpp#775]
**Platform**
 - OMNeT++ version: 5.4.1
 - OS: Windows

**Describe the bug**
Probability density and cumulative density charts based on a weighted histogram include values > 1 ! 
In case of a weighted histogram probability values should be computed based on sum of weights and not on count of observations (as for an unweighted histogram).

**To Reproduce**
Attached files: .sca file and charts for both weighted and unweighted histograms.
[General-#0.txt](https://github.com/omnetpp/omnetpp/files/3692044/General-.0.txt)

![Probability_Density - Unweighted_Histogram](https://user-images.githubusercontent.com/56070495/66235193-d369a880-e6ef-11e9-8e6e-7081d3009702.png)

![Probability_Density - Weighted_Histogram](https://user-images.githubusercontent.com/56070495/66234954-432b6380-e6ef-11e9-8234-a314c9ad15c2.png)

![Cumulative_Density - Unweighted_Histogram](https://user-images.githubusercontent.com/56070495/66235029-73730200-e6ef-11e9-9069-72e2fdd56bdf.png)

![Cumulative_Density - Weighted_Histogram](https://user-images.githubusercontent.com/56070495/66235032-75d55c00-e6ef-11e9-897f-fc7b2757aa24.png)

**Comment by torokati44** [comment]
Thanks for reporting, you are right. The fix is in place internally, and it should be in the next point release.

**Comment by torokati44** [comment]
The fix is included in the 5.6 release.
