### ISSUE TITLE
Omentpp make error

### ISSUE THREAD

**Issue by spiroskat** [omnetpp/omnetpp#776]
When configured with gcc, has make problem: the error is 
osgviewer.cc: In member function ‘virtual void omnetpp::qtenv::OsgViewer::refresh()’:
osgviewer.cc:504:30: error: ‘findTopMostNodeOfType’ is not a member of ‘osgEarth’
         auto sky = osgEarth::findTopMostNodeOfType<osgEarth::Util::SkyNode>(scene);
                              ^~~~~~~~~~~~~~~~~~~~~
osgviewer.cc:504:75: error: expected primary-expression before ‘>’ token
         auto sky = osgEarth::findTopMostNodeOfType<osgEarth::Util::SkyNode>(scene);

**Comment by torokati44** [comment]
Which versions of OMNeT++, OpenSceneGraph, and osgEarth do you have?

**Comment by rhornig** [comment]
This is probably an osgEarth version mismatch. If you don't use OSG/OSGEARTH, just disable it in cofigure.user
