### ISSUE TITLE
Could it use without restricted directories such as perl?

### ISSUE THREAD

**Issue by Vonfry** [omnetpp/omnetpp#784]
**Platform**
 - OMNeT++ version: omnetpp-6.0pre5
 - OS: nixos 19.09.1320.4ad6f1404a8 (Loris)

**Describe the bug**
When runing `./configure`, it complains `configure: error: Perl MUST be available as /usr/bin/perl. Creating a soft link should help: ln -s /nix/store/4jgv6q38ac1wsigy0gnc1x9nsfjqmby9-perl-5.30.0/bin/perl /usr/bin/perl`. 

On some linux distrubtions, such as nixos, here isn't `/usr/bin` dir and user(package manager) cannot write to the path, which only can be done in a sandbox. It uses a special path to save all packages and uses link and enviroment to let shell work.

Could checking be cancelled or use environment variable instead?

**Comment by avarga** [comment]
Hi, this is a leftover check, it will be removed in future versions. There's actually no need for perl to be in /usr/bin, shebangs using it were replaced by '/usr/bin/env perl' a while ago.

For now, you can solve the problem by removing the following lines from the configure script:

if test ! -x /usr/bin/perl; then
   this_perl=`which perl`
   as_fn_error $? "Perl MUST be available as /usr/bin/perl. Creating a soft link should help: ln -s $this_perl /usr/bin/perl" "$LINENO" 5
fi

**Comment by Vonfry** [comment]
Thanks for fixing.

Here are some others which may use `/usr/bin/env` instead.

```
configure
37:# Printing a long string crashes Solaris 7 /usr/bin/printf.
1680:/usr/bin/uname -p = `(/usr/bin/uname -p) 2>/dev/null || echo unknown`
1684:/usr/bin/arch -k       = `(/usr/bin/arch -k) 2>/dev/null       || echo unknown`
1686:/usr/bin/hostinfo      = `(/usr/bin/hostinfo) 2>/dev/null      || echo unknown`
1688:/usr/bin/oslevel       = `(/usr/bin/oslevel) 2>/dev/null       || echo unknown`
6106:# Printing a long string crashes Solaris 7 /usr/bin/printf.

src/utils/config.guess
345:	case `/usr/bin/uname -p` in
383:	case "`/usr/bin/arch -k`" in
505:	UNAME_PROCESSOR=`/usr/bin/uname -p`
542:	if [ -x /usr/bin/oslevel ] ; then
543:		IBM_REV=`/usr/bin/oslevel`
582:	if [ -x /usr/bin/oslevel ] ; then
583:		IBM_REV=`/usr/bin/oslevel`
616:		if [ -x /usr/bin/getconf ]; then
617:		    sc_cpu_version=`/usr/bin/getconf SC_CPU_VERSION 2>/dev/null`
618:		    sc_kernel_bits=`/usr/bin/getconf SC_KERNEL_BITS 2>/dev/null`
812:	UNAME_PROCESSOR=`/usr/bin/uname -p`
1397:/usr/bin/uname -p = `(/usr/bin/uname -p) 2>/dev/null`
1402:/usr/bin/arch -k       = `(/usr/bin/arch -k) 2>/dev/null`
1404:/usr/bin/oslevel       = `(/usr/bin/oslevel) 2>/dev/null`

src/utils/splitvec
1:#!/usr/bin/awk -f
```

**Comment by avarga** [comment]
Thanks for reporting. With awk it doesn't work for some reason, it says:
/usr/bin/env: ‘awk -f’: No such file or directory

About the others: configure is generated (from configure.in by autoconf, which puts in the /usr/bin bits), and config.guess is the output of configure, so I think we cannot do much about them. Are they a problem on NixOS?

**Comment by Vonfry** [comment]
For awk, `/bin/usr/env awk -f` can work for me without quoting `'awk -f'`.

I think this is not a big problem, I have configured omnetpp without changing these.

Thank you.

**Comment by torokati44** [comment]
I'm just curious: if you run `autoconf` on your system in the source directory, the resulting `configure` script still doesn't work?

**Comment by Vonfry** [comment]
@torokati44 Yes, but the problem is different from this issue. 
Here are some problem with variable CFLAGS which is special on NixOS, and I do a patch for myself to deal this. It isn't a common question.

About this issue, perl must be `/usr/bin/perl` is coded in `configure.in`, so without editing it, `./configure` will still fail after `autoconf`. Now, it has been fixed.
