### ISSUE TITLE
binutils: miss an argument for ar command.

### ISSUE THREAD

**Issue by Vonfry** [omnetpp/omnetpp#785]
** `ar --version`**
```
GNU ar (GNU Binutils) 2.31.1
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

**Describe the bug**

For example: [src/envir/Makefile](https://github.com/omnetpp/omnetpp/blob/master/src/envir/Makefile#L112), it runs `ar <path>/omnetpp/out/gcc-release/src/envir/liboppmain.a <path>/omnetpp/out/gcc-release/src/envir/main.o`

It returns an error as following:
```
ar: invalid option -- '/'
# And here is a output for ar --help, which is too long.
```

**GNU binutils**
In [binutils](https://www.gnu.org/software/binutils/) page, here is a [document page](https://sourceware.org/binutils/docs-2.33.1/binutils/ar.html#ar) about ar.

`ar [-]p[mod] [--plugin name] [--target bfdname] [relpos] [count] archive [member…]` 

Note: There is another argument betweent ar and archive. 

**Fix**
I write a patch for myself which make it working, but this may be a problem on other distrubtion.

**Comment by avarga** [comment]
Is this on NixOS as well? I'm not sure what's different on that platform that makes 'ar' fail, while it apparently works on other Linux distros.

**Comment by Vonfry** [comment]
I think the reason is from binutils version. According to the newest version of ar(see [here](https://sourceware.org/binutils/docs-2.33.1/binutils/ar.html#ar)), it needs another argument in the ar usage document. I mean contributors may  take a consider on this.

By the way, if it is only a nixos special problem, I will fix it by myself as much as possible without open an issue.

**Comment by avarga** [comment]
Thanks for pointing that out. Interestingly, the [doc page for version 3.30](https://sourceware.org/binutils/docs-2.30/binutils/ar.html#ar) (which I currently have on Ubuntu) has exactly the same content as 3.33.1, and yet omnetpp compiles fine. Maybe they adjusted the actual behavior to match the documentation?

**Comment by Vonfry** [comment]
Sorry for bothering. I recheck the configure scripts, it is set automatically, which is not effect for me.
