### ISSUE TITLE
cMessage "messageId" is not indicative of total number of messages created in a network

### ISSUE THREAD

**Issue by RickyDenton** [omnetpp/omnetpp#786]
**Platform**
 - OMNeT++ version: 5.5.1
 - OS: Linux Mint 19.2 Tina (in VM)

**Describe the bug**
The "messageId" field of a cMessage object is not indicative of the total number of messages created in a network.
This is due to the fact that, when a message is sent from one module to another through the sendDelayed() function, a copy of the sent message is created by the privateDup() function, which by increasing the "next_id" static member of the cMessage class causes the next "real" message created in the network to have its "messageId" shifted by one.
Needless to say, this causes issues in simulations driven by a specific number of messages being created, and whether the "messageId" value should represent the number of "real" messages created in the network or not, a big warning in the documentation would be appreciated. 

**To Reproduce**
Simply have a module creating and sending messages to another, and log the messageIds.

**Comment by avarga** [comment]
> The "messageId" field of a cMessage object is not indicative of the total number of messages created in a network.

This is correct, but what makes you think it is supposed to? For cMessage::getId(), the API doc only [says](https://doc.omnetpp.org/omnetpp/api/classomnetpp_1_1cMessage.html) it "Returns a unique message identifier assigned upon message creation", which it does.

**Comment by RickyDenton** [comment]
In such case I would add a paragraph in the documentation warning that messages are also created for purposes internal to the simulation kernel, thus the "messageId" value shouldn't be used as a metric for the total number of "effective" messages created as seen by the network.

Thanks anyway

**Comment by torokati44** [comment]
Is perhaps `cMessage::getTotalMessageCount()` or `cMessage::getLiveMessageCount()` what you're looking for?
