### ISSUE TITLE
Use comma as digit separator in the Qtenv simtime display

### ISSUE THREAD

**Issue by avarga** [omnetpp/omnetpp#788]
The Qtenv simtime display (top right corner) currently uses apostrophe as digit separator in the "seconds" field by default. It diverges from conventional notation (comma), and easy to mistake for minutes.  The display can be customized using the context menu, but the default should be the one we recommend (comma?).

OMNeT++ 5.5

**Comment by rhornig** [comment]
In OMNeT++ 6 the default is now space, but make sure to delete `~/.qtenvrc` as 5.x versions tend to write out their actual settings there...
