### ISSUE TITLE
cAbstractHistogram::getCDF() does not return the CDF (sum)

### ISSUE THREAD

**Issue by roland-bless** [omnetpp/omnetpp#789]
**Platform**
 - OMNeT++ version: 5.5.1
 - OS: Ubuntu 19.10

**Description**
the getCDF() does not return the CDF (sum of probabilities) 

**Patch**
Sorry, don't know how to better provide the fix (pull request?)

    diff` --git a/src/sim/cabstracthistogram.cc b/src/sim/cabstracthistogram.cc
    index 3dfe170501..64918c4b3b 100644
    --- a/src/sim/cabstracthistogram.cc
    +++ b/src/sim/cabstracthistogram.cc
    @@ -85,13 +85,16 @@ double cAbstractHistogram::getCDF(double x) const
     
         int numBins = getNumBins();
     
    +    double sum= 0;
         // returns 0..1; uses linear approximation between two markers
         for (int i = 0; i < numBins; ++i) {
             double lowerEdge = getBinEdge(i);
             double upperEdge = getBinEdge(i + 1);
     
             if (x < upperEdge)
    -            return getBinValue(i) * ((x - lowerEdge) / getSumWeights() / (upperEdge - lowerEdge));
    +            return sum + getBinValue(i) * ((x - lowerEdge) / getSumWeights() / (upperEdge - lowerEdge));
    +       else
    +               sum+= getBinValue(i) / getSumWeights();
         }
     
         if (x < getMax())

**Comment by avarga** [comment]
Fixed, thanks very much for reporting!
