### ISSUE TITLE
Debugger support under MacOS 10.14 and higher

### ISSUE THREAD

**Issue by screw** [omnetpp/omnetpp#790]
With the last two OMNeT++ releases I want to ask if you know if there has been any progress towards supporting debugger under MacOS version 10.14.
The only working solution I found is to use lldb-mi2 project.
It has two main issues:
1. Sometimes the displayed value of a variable is not updated when the same code is visited again.
2. Does not support STL
Thanks.

**Comment by screw** [comment]
I tried it just now and yes, lldbmi2 is pre-configured as default when you install the GDB extension to eclise.
But it fails when I try to start the debug of INET example with:

<!> Error: Line must be in the form key=value, 'omnetpp.ini' line 41

**Comment by rhornig** [comment]
We do not have a proper LLDB based debugger for Eclipse at the moment. Everything is based on gdb or lldb-mi which has some serious limitation. For the time being, we must rely on lldb-mi2. I wish someone would implement an Eclipse debugger based on Debug Adapter Protocol. 

Currently, Visual Studio Code works fine with LLDB (using Debug Adapter Protocol) and you can use that for debugging, however this kind of defies the purpose of the IDE if you have to debug in a different environment. We will keep an eye on possible solutions.
