### ISSUE TITLE
IDE gets stuck indexing

### ISSUE THREAD

**Issue by screw** [omnetpp/omnetpp#792]
**Platform**
 - OMNeT++ version: [e.g. 6.0pre6]
 - OS: [e.g. MacOS v10.14.6 (18G103)]

**Describe the bug**
The IDE nearly hangs (sometimes completely freezes) when indexing new INET project.
The indexing gets to `/inet/src/inet/linklayer/ieee80211/mac/blockack/RecipientBlockAckAgreementHandler.cc`
and does not progress further. 
The same happens under on MacOS with OMNeT 5.4.1.

**To Reproduce**
Install OMNeT 6.0pre6 (or 5.4.1) on MacOS, clone INET project, import it and observe.
Sometimes it also happens when I switch branches/skip through commits and the C/C++ indexer is triggered.
I get around it by disabling few project features, restart IDE, let the indexing finish and restore the project features.
At times the IDE becomes so unresponsive that it's not possible to get to the project features and I have to kill it and try as fast as possible with a new process.

**Comment by rhornig** [comment]
I've tried to reproduce this, but the indexing finishes correctly for me (tested with INET 4.2, OMNeT++ 6.0pre6). Is this only a problem with the master branch only, or INET 4.2 also produces this? It consumes almost 1.5Gb during the indexing though, however this should not be a problem on any (not to ancient hardware)

**Comment by rhornig** [comment]
The issue with OMNeT++ 5.4.1 is to be expected, however a workaround was introduced in 5.5 and 5.6 and also in 6.0 previews. See #754 for details. What is the memory usage of the IDE process when this happens?

**Comment by screw** [comment]
I didn't see the original ticket for 5.4.1.
Tested fresh install of 6.0pre6 with fresh INET v4.2.0 and indexing went smooth.
Same with the latest master.
So it must have been some artefacts left after switching between branches/commits (or fix in the master since last week?).

Maybe irrelevant but it still happens with my forked branch that is based on `7fc835544b98ff46652ae50dd83efb1525227188`.

**Comment by rhornig** [comment]
Indexer seems to be working on omnet 6pre11
