### ISSUE TITLE
Windows 10: OMNeT++ 6 Preview 6/9: inet v3.6.7/v3.6.8: Examples not running 

### ISSUE THREAD

**Issue by Musteblume** [omnetpp/omnetpp#794]
**Platform**
 - OMNeT++ version: 6.0 Preview 6
 - OS: Windows 10

**Describe the bug**
The examples in the inet-framework v3.6.7 are terminating with exit code 1 (Cannot load library libINET.dll) in Windows.

**To Reproduce**
- Install OMNeT++ 6 Preview 6 in Windows 10 (1909)
- Build (release) inet-framwork v3.6.7
- Start any example

**Comment by Musteblume** [comment]
Still the same in OMNeT++ 6.0 preview 9 with inet-framework v3.6.8 in Windows 10 (20H2).

**Comment by torokati44** [comment]
Could you please try applying this patch on top of the OMNeT++ source, then rebuilding it?
https://gist.github.com/torokati44/9130641f2978d14af1a17c2a26a71a81
Perhaps it will give a more useful error message...
(Rebuilding INET should not be necessary.)

**Comment by Musteblume** [comment]
Here is the additional error message (Sorry my OS is configured to german):
![Error](https://user-images.githubusercontent.com/22887071/100440436-29906c80-30a5-11eb-89ab-71383de58a9f.jpg)

**Comment by torokati44** [comment]
Maybe you could try the workaround described here: https://github.com/inet-framework/inet/pull/570#issuecomment-724688986

**Comment by Musteblume** [comment]
I have switched the libws2_32.a in OMNeT++ 6.0 Preview 9 with the one located in OMNeT++ 5.6.2. Now the examples are starting and running like expected.

**Comment by Musteblume** [comment]
Fixed with OMNeT++ 6.0 Preview 10 and inet-framework 3.7
