### ISSUE TITLE
Windows 10: OMNeT++ 6 Preview 6: Python is missing from mingwenv

### ISSUE THREAD

**Issue by Musteblume** [omnetpp/omnetpp#795]
**Platform**
 - OMNeT++ version: 6.0 Preview 6
 - OS: Windows 10

**Describe the bug**
mingwenv couldn't find python. So fingerprint scripts are not runnable.

**To Reproduce**
- Install OMNeT++ 6 Preview 6 in Windows 10 (1909)
- Build (release) inet-framwork v3.6.7
- Run inet fingerprint test script in mingwenv

**Comment by rhornig** [comment]
Yes. OMNeT++ 6 contains only python3. Probably INET 3.6.7 should be updated also to run on python3. This is an INET issue to be addressed there

**Comment by rhornig** [comment]
Should be fixed in INET 3.6.x branch.
