### ISSUE TITLE
Broken charts

### ISSUE THREAD

**Issue by screw** [omnetpp/omnetpp#800]
**Platform**
 - OMNeT++ version: 5.6
 - OS: MacOS Mojave 10.14.6 

**Describe the bug**
Generated chart is 'broken' when viewed on MacBook without external screen.
<img width="1183" alt="Screenshot 2020-03-03 10 17 58" src="https://user-images.githubusercontent.com/1584633/75763825-2b5b1880-5d3d-11ea-8bca-3816e5cc80ec.png">

When you do right-click in the generated image (for zoom-in etc) the glitch disappears (for as long as you hold the click).
It only happens if I DON'T HAVE any external screens connected.

**To Reproduce**
Create line-chart, open it.
When I connect external display afterwards the view is refreshed and the issue is fixed.

**Comment by torokati44** [comment]
We are aware of a very similar glitch that has been fixed internally.
Hopefully we'll release yet another 6.0 preview release soon, which will likely include a fix for it.
Although the relevance of an external display being present or not is really strange, we haven't experienced that.
If you could please try to reproduce it with said next preview release when it comes out, and verify that it is indeed fixed, it might be backported to the 5.x branch as well.
Thanks for reporting.

**Comment by torokati44** [comment]
This should be fixed in 6.0pre7. Could you verify, @screw?
