### ISSUE TITLE
How to start a omnet simulation *.exe in python3.6?

### ISSUE THREAD

**Issue by 179416326** [omnetpp/omnetpp#805]
I tried to start a omnet simulation *.exe in python3.6 in this way:
omnet_output = subprocess.check_output([simexe, '-n', simfolder, simini, env.folder + 'folder.ini']).decode()
But it cannot start the simexe, i have tried to start other windows exe, it works well. Please help, thanks.

**Comment by rhornig** [comment]
Make sure, you are running this from the MINGW console otherwise .dll files needed by the simulator will not be found.
