### ISSUE TITLE
Memory corruption with long file paths

### ISSUE THREAD

**Issue by knrafto** [omnetpp/omnetpp#806]
**Platform**
 - OMNeT++ version: 5.6
 - OS: Linux

**Describe the bug**
When .ned file path is longer than 200 bytes or so, the simulation segfaults.

**To Reproduce**
Pass in a long .ned path (for example, by creating a nested hierarchy of directories with long names) via the -n option.

The cause is in src/nedxml/yyutil.cc: https://github.com/omnetpp/omnetpp/blob/9063bf4386deb9327097ad0af39eb6aba9b593f1/src/nedxml/yyutil.cc#L78

I'd suggest using a larger buffer size (1024 should be enough for our use case), and using snprintf to prevent memory corruption if the file path is too long.

**Comment by avarga** [comment]
Fixed, thank you for reporting!
