### ISSUE TITLE
Issue using channel types to see if the channel is busy?

### ISSUE THREAD

**Issue by ujur007** [omnetpp/omnetpp#808]
**Platform**
 - OMNeT++ version: [e.g. 5.5.1]
 - OS: Windowns 10

**Describe the bug**

I am working on a project where I want to use a dataratechannel and see if it is busy or free for next message transmission. 

What is suspicious to me is that when there are two messages's to be transmitted only one of them is transmitted and BUT after the first call to scheduleAt() the next message is able to travel even though the channel is busy!! rather it should schedule again the self message.

**To Reproduce**
cChannel *tX=gate("port$o",0)->getTransmissionChannel();
cDatarateChannel *tXX=check_and_cast<cDatarateChannel *>(tX);
simtime_t delay=tXX->getDelay();
simtime_t txfinishtime=tXX->getTransmissionFinishTime();

if(txfinishtime<simTime()){
}
else{
scheduleAt(simTime()+0.1,new cMessage);
}

**Comment by rhornig** [comment]
OMNeT++ 6 preview 9 has some reworked API for TransmissionChannels, but generally, user models (not 
 OMNeT++) should keep a tab, whether a channel can be used for transmission or not. (i.e. busy or not).
