### ISSUE TITLE
Support layouting multiple submodules/submodule vectors as a single group

### ISSUE THREAD

**Issue by levy** [omnetpp/omnetpp#812]
Sometimes different submodules/submodule vectors should be layouted as a coherent group. For example, there are several optional submodules without gates in network nodes in INET. These could be positioned by a single layouting algorithm if there would be a way to specify that they are part of the same layout group. There are other examples such as similar submodules of networks, network interfaces within network nodes, etc.

The proposed solution is to introduce a new display string tag to specify the layout group.

**Comment by rhornig** [comment]
Layout groups implemented in fa5ad494030e5d93182639972935a5ecb96ab721 solve this.
