### ISSUE TITLE
A linux installation issue

### ISSUE THREAD

**Issue by ruidazeng** [omnetpp/omnetpp#814]
**Platform**
 - OMNeT++ version: [e.g. 5.6.1]
 - OS: [e.g. Ubuntu 18.04]

Is there a fundamental Linux installation issue that is preventing me from getting configuration to work properly? I followed the instructions exactly with help from a colleague who has omnetpp successfully installed including setting PATH and ENV correctly. My `./configure` will always return the following error:

configure: error: Qtenv cannot find qmake -- maybe it is not in the PATH or has some exotic name (tested names were: qmake qmake-qt5 qmake5) - disabling Qtenv. You can try setting the QT_PATH variable in configure.user to a valid location.

**Comment by gargmohit24** [comment]
I am facing the same problem. OMNET++ 5.5.1, Ubuntu 20.04

**Comment by Krupenz** [comment]
same thing on pop_os 20.04

**Comment by PilotoEspacial** [comment]
Same on Debian12

**Comment by rhornig** [comment]
Would you mind trying out the just released 5.6.3? It was specifically updated for newer distro releases.

**Comment by PilotoEspacial** [comment]
Sorry, first time reporting an issue, I have solved it.

Nice work you´ve done!
