### ISSUE TITLE
Could not connect to TraCI server;

### ISSUE THREAD

**Issue by doubley529** [omnetpp/omnetpp#817]
HELLO,when i run a veins project in omnet, always come up this bug. please help me, thanks!

** Event #1 t=0 RSUExampleScenario.manager (TraCIScenarioManagerLaunchd, id=6) on selfmsg connect (omnetpp::cMessage, id=14)

WARN:Could not connect to TraCI server; error message: 0: No error -- Will retry in 1 second(s).

**Comment by tenplus-thu** [comment]
I meet the same error with you! I have tried several different version, including omnet++ 5.6.1, 5.6.2, sumo 0.30.0, 1.0.0, 1.3.0, 1.6.0, and veins 5.0. But every time after I build up the project, and click "run" button, there comes the bug: ** Event #1 t=0 RSUExampleScenario.manager (TraCIScenarioManagerLaunchd, id=6) on selfmsg connect (omnetpp::cMessage, id=14). Error number: 10054.
Help!!!

**Comment by rhornig** [comment]
This is not related to the core omnetpp kernel.
