### ISSUE TITLE
Call DLL dynamically. Function cannot have arguments

### ISSUE THREAD

**Issue by pfliu721** [omnetpp/omnetpp#818]
Call DLL dynamically. Function cannot have arguments. 
An error is reported by the compiler if the function takes arguments.
error: too many arguments to function call, expected 0, have 1.
Can you help me? Thank you very much.

**Comment by levy** [comment]
This is not a forum to ask questions. Please use the mailing list for that.

**Comment by torokati44** [comment]
To call any functions from a DLL, the function has to be declared in the loading application as well. Either by including a header, or writing the function declaration into the loading/calling code directly.
You probably don't have this, so the function is declared implicitly without arguments (but you should see a compiler warning about this); or it does not exactly match the actual function built into the DLL.

**Comment by pfliu721** [comment]
@levy 
All right.This is the first time I have asked a question. I don't know the rules very well.I feel guilty for not following the rules.
