### ISSUE TITLE
Adding multiple sinks in omnet++

### ISSUE THREAD

**Issue by mtanushree** [omnetpp/omnetpp#824]
**Platform**
 - OMNeT++ version: [e.g.  5.6.2]
 - OS: [e.g. Ubuntu 18.04]

Hi sir,
I am doing project on multiple sinks. I am not able to add multiple sinks in the network. Currently i have added the host as the sink.
Please help me to add the multiple sinks

**Comment by torokati44** [comment]
This issue tracker is here for you to report bugs in OMNeT++, not to ask for help on how to use it.
