### ISSUE TITLE
Get cModuleType from static cModule function

### ISSUE THREAD

**Issue by karlhto** [omnetpp/omnetpp#828]
Hello!

It would be very convenient if there was some function that allows you to get a `cModuleType` from a NED module with a C++ definition. For instance, instance, instead of doing:

```cpp
cModuleType *modeleType = cModuleType::get("some.ned.path.CoolModule");
```
...you could do:

```cpp
cModuleType *moduleType = CoolModule::getModuleType();
```

**Comment by torokati44** [comment]
A single C++ class can implement multiple simple modules - although it is rare, but technically possible (see: the `@class` NED property). So it is not possible to look up "the" module type for a C++ class, since it is ambiguous.

**Comment by karlhto** [comment]
I see, thanks for your reply!

Closing.
