### ISSUE TITLE
INET (queueing) modules ignore channel definition (cChannel class)

### ISSUE THREAD

**Issue by Kathess** [omnetpp/omnetpp#830]
**Platform**
 - OMNeT++ version: 5.6.1
 - INET version: 4.2.0
 - OS: Linux Mint 19.3 

**Describe the bug**
When using INET modules, the channel definition is completely ignored. Regardless, of the channel-type (tested with DatarateChannel, DelayChannel and own delay definition, see example code). One would expect that a packet would get delayed or get lost (e.g. if the channel parameter "disabled" is set to true) but the channel definition is just ignored. No error, no warning, just no effect.

**To Reproduce**
I've appended a minimalistic example project, just including one .ini and one .ned file. Even though, a delay is configured in the NED file, the delay that the packet experienced at the sink will always be 0. To run it, the reference to the current INET version needs to be set and to observe the delay, the sink's code could be extended with the following line in the function `void PassivePacketSink::consumePacket(Packet *packet)`:

```C++
simtime_t creationTime = packet->getCreationTime();
EV << "Packet delay: " << simTime() - creationTime << endl;
```

Here is the critical code, which is also included in the ZIP file.
```ruby 
    submodules:
        producer: ActivePacketSource {
            @display("p=100,100");
        }
        consumer: PassivePacketSink {
            @display("p=300,100");
        }
    connections:
        producer.out --> {  delay = 100s; } --> consumer.in; 
```

[channelBug.zip](https://github.com/omnetpp/omnetpp/files/5031373/channelBug.zip)

**Comment by levy** [comment]
Thanks for the bug report!

Unfortunately, you chose the wrong forum, because this is an INET bug and it should be filed at https://github.com/inet-framework/inet . I'll leave this open until the issue is resubmitted there.

Indeed, the queuing model elements communicate with synchronous C++ method calls and they completely bypass the channels currently. This can be changed though, I think.

**Comment by levy** [comment]
Thanks again for moving the issue to the INET forum!

**Comment by Kathess** [comment]
Thank you for your quick and informative response! I've reposted it there!
