### ISSUE TITLE
INET PacketServer processingBitrate only adds integer seconds delay

### ISSUE THREAD

**Issue by Kathess** [omnetpp/omnetpp#832]
**Platform**
- OMNeT++ version: 5.6.1
- INET version: 4.2.0
- OS: Linux Mint 19.3

**Describe the bug**
The PacketServer of INET correctly handles its parameter _processingTime_ but _processingBitrate_ only results in real integer values. This means, the server only adds a delay of 0s, 1s, 2s and so on, but never 0.5s. The delay is always rounded to the next smaller integer. No error, no warning, only the delay is not added correctly.

For example, if we define a _processingBitrate_ of _10Mbps_ and a _packetLength_ at the source of 10Mb then the delay is correctly 1s. But if the _packetLength_ is 5Mb then the delay is 0s.

**To Reproduce**
I provide the .ned and .ini file below. The delay should be 0.502s (0.002s from the _processingTime_ delay and 0.5s from the _processingBitrate_ delay). Instead, it is 0.002s. It increases to 1.002s if we increase the packet size to 10Mb. 

The most basic example to see this effect has the following .ned file:

```javascript
import inet.queueing.queue.PacketQueue;
import inet.queueing.server.PacketServer;
import inet.queueing.sink.PassivePacketSink;
import inet.queueing.source.ActivePacketSource;


network SmallExampleNetwork
{
    @display("bgb=585,237");
    submodules:
        producer: ActivePacketSource {
            @display("p=100,100");
        }
        queue: PacketQueue {
            @display("p=229,100");
        }
        server: PacketServer {
            @display("p=330,100");
        }
        consumer: PassivePacketSink {
            @display("p=502,100");
        }
    connections:
        producer.out --> queue.in;
        queue.out --> server.in;
        server.out --> consumer.in;
}
```

with the following .ini configuration:
```python
[General]
network = SmallExampleNetwork
*.producer.packetLength = 5Mb # same result e.g. with 625000B 
*.producer.productionInterval = 2s

*.server.processingBitrate = 10Mbps
*.server.processingTime = 2ms
```

To track the delay, the sink's code could be adapted e.g. with:
```C++
simtime_t creationTime = packet->getCreationTime();
EV << "Packet delay: " << simTime() - creationTime << endl;
```

**Comment by levy** [comment]
Thanks for the bug report!

Unfortunately, you chose the wrong forum, because this is an INET bug and it should be filed at https://github.com/inet-framework/inet . This has been fixed in the INET master since 4.2 was released, see 322ebcffe6210d7267bbc5d7482960edec2016b4. Please note that the latest INET master branch requires a not yet released OMNeT++ 6 version.
