### ISSUE TITLE
Issues when installing the software

### ISSUE THREAD

**Issue by zhishiwanwan01** [omnetpp/omnetpp#838]
**Platform**
 - OMNeT++ version: [e.g. 5.6.2]
 - OS: [e.g. windows 10]

**Describe the bug**
Hi, I have a problem when installing the software. After doing ./configure, when I do the `make` command, things like this appeared.

 1 [main] perl 4992 child_info_fork::abort: address space needed by 'Cwd.dll' (0x5168E0000) is already occupied
      1 [main] perl 17336 child_info_fork::abort: address space needed by 'Cwd.dll' (0x5168E0000) is already occupied
      0 [main] perl 20896 child_info_fork::abort: address space needed by 'Cwd.dll' (0x5168E0000) is already occupied
      1 [main] perl 2588 child_info_fork::abort: address space needed by 'Cwd.dll' (0x5168E0000) is already occupied
      0 [main] perl 10692 child_info_fork::abort: address space needed by 'Cwd.dll' (0x5168E0000) is already occupied
      0 [main] perl 1088 child_info_fork::abort: address space needed by 'Cwd.dll' (0x5168E0000) is already occupied
      0 [main] perl 23384 child_info_fork::abort: address space needed by 'Cwd.dll' (0x5168E0000) is already occupied
      1 [main] perl 22540 child_info_fork::abort: address space needed by 'Cwd.dll' (0x5168E0000) is already occupied

What should I do to fix this problem?

**Comment by rhornig** [comment]
This may be caused by an antivirus software, or simply because of address space randomization feature. You may also try to 'rebase' the mingw DLL-s in the distro. There is a script in the tools/win64 folder that can rebase all DLLs in the toolchain distro. That *might* help.

**Comment by shiv-sugay** [comment]
Hi Rhornig,

I am also facing with the same issue.
Could you please give some information how to 'rebase' step.

Thank you in advance.

**Comment by rhornig** [comment]
I recommend using the latest version of OMNeT++, but the rebase script to be executed is: `tools/win64/autorebase.bat`
