### ISSUE TITLE
Omnet++ RFID simulation? 

### ISSUE THREAD

**Issue by amalhub** [omnetpp/omnetpp#840]
Hi, 
I need to set up a simulation using a basic RFID tag and an RFID reader (any out of the box component without creating a custom component) placed 10 meters apart inside a metallic tunnel and move the RFID reader(antenna) towards the RFID tag(passive tag) in the simulation. Then log(plot) the RSSI and Phase values against the distance between the RFID tag and antenna.

I'm new to Omnet++ software. Could you please let me know whether my requirement is possible to do with Omnet++ simulation and if it is possible then the way forward on getting it done or getting myself educated to achieve the task?

**Comment by avarga** [comment]
Hi, you submitted your question at the wrong place. This is a bug tracker for problems found in the OMNeT++ software package itself, and not a support forum. Re-post your questions to the mailing list.
