### ISSUE TITLE
MATLAB - OMNET real time communication

### ISSUE THREAD

**Issue by NovasMax** [omnetpp/omnetpp#844]
**Platform**
 - OMNeT++ version: 5.6.2
 - OS: Windows 10
 - MATLAB: r2019b

**Describe the bug**
Hi everyone !

I am working on a project that aims to simulate a network of vehicles. All the dynamic and control part of the network is already designed on simulink in MATLAB, and I would like to keep it that way. But for this simulation to work, each vehicle needs informations about the other ones (position, speed, etc...). For now, they have direct access to all the information of the other vehicles, but I would like to transmit these information between vehicles with V2V communications using 802.11p protocol in OMNET.
So to sum up, if a message must be sent from a vehicle to another in MATLAB, this message is sent to omnet (through a TCP socket ), which simulate the communication, and send back the message to the second vehicle in MATLAB ( with delay, etc...), in real time. I know that such real time communication with other software is already being done with SUMO thanks to the TraCI protocol and veins, and I managed to make omnet and matlab discuss through this protocol. But Veins scenarios are pretty complex and handle for instance the mobility aspect of the vehicles. In my case, I just want to simulate the communications between the nodes that represents vehicles. But using TraCi is the only way I have found so far to make OMNET and MATLAB communicate. 

Do you have some advice about how I should proceed, or if some existing projects are tackling a similar subject ? 

Thanks in advance for your help, I hope my question is clear.

You can find below on example of what I want to do.

![Schéma d'échange](https://user-images.githubusercontent.com/57716360/97413974-b3f97b00-1903-11eb-8c08-b57f61a674a0.png)

**Comment by rhornig** [comment]
I'm closing this, because this is an issue tracker for the OMNeT++ simulator. I suggest try to ask this on the OMNeT++ mailing list, which is intended for that purpose.
