### ISSUE TITLE
Cannot attach vector to axis in flow chart of elog

### ISSUE THREAD

**Issue by roialtair** [omnetpp/omnetpp#845]
**Platform**
 - OMNeT++ version: 6.0 pre9
 - OS: Ubuntu 18.04 (also on windows)

when i try to attach vector to axis it lets me select the vector file and the item but then is gives error that the file cannot be open.
the same code and also the same elog&vec files works ok on version 5.4

![image](https://user-images.githubusercontent.com/73942384/98109036-98fbad80-1ea5-11eb-90cf-fb71daf3122d.png)

attached are the results files for reproduction of the problems
[files.zip](https://github.com/omnetpp/omnetpp/files/5487636/files.zip)

**Comment by levy** [comment]
I can't reproduce this issue with the latest versions because I cannot load the elog file. This file was written with an older version of omnetpp. There was a large refactor and some bug fixes related to loading vector files, so this issue may have been already fixed.
