### ISSUE TITLE
cHasher::add - correction & optimisation

### ISSUE THREAD

**Issue by chris0e3** [omnetpp/omnetpp#846]
Hello,

I was just driving by when I noticed the following:
in https://github.com/omnetpp/omnetpp/blob/master/src/sim/chasher.cc
```
void cHasher::add(const char *p, size_t length)
…
        merge((uint32_t)(p[i] | (p[i+1] << 8) | (p[i+2] << 16) | (p[i+3] << 24)));
…
        case 1: merge((uint32_t)(p[i])); break;
        case 2: merge((uint32_t)(p[i] | (p[i+1] << 8))); break;
        case 3: merge((uint32_t)(p[i] | (p[i+1] << 8) | (p[i+2] << 16))); break;
…
```

In the above, the calls to `merge` will sign extend the chars read from `p` before shifting & or’ing them together - this is probably not what was intended, is bad for UTF-8 text (where chars may < 0) & is very non-optimal.
The following corrects this, shortens the entire function & reduces the ‘bulk’ loop from 19 instructions to 6 (Clang 11.0 on x86-64):

```
void cHasher::add(const char* p, size_t length)
{
    using u32 = uint32_t;
    u32 v = value; auto s = (const uint8_t*) p;
    auto Merge = [&](u32 x) { v = ((v << 1) | (v >> 31)) ^ x; };
    // add the bulk in 4-byte chunks
    for (; length >= 4; length -= 4, s += 4)
        Merge(u32(s[0]) | (u32(s[1]) << 8) | (u32(s[2]) << 16) | (u32(s[3]) << 24));

    // add the 1, 2 or 3 bytes left
    switch (length) {
        case 0:                                                             break;
        case 1: Merge(u32(s[0]));                                           break;
        case 2: Merge(u32(s[0]) | (u32(s[1]) << 8));                        break;
        case 3: Merge(u32(s[0]) | (u32(s[1]) << 8) | (u32(s[2]) << 16));    break;
    }
    value = v;
}
```

Please feel free to use the above how (& if) you please.

Regards,

CHRIS

**Comment by avarga** [comment]
I committed both the fix of the sign extension bug and the improvement, albeit in a slightly different form. I appreciate your contribution!
