### ISSUE TITLE
omnetpp gui not showing under WSL2 with VcXsrv

### ISSUE THREAD

**Issue by CrenshawCoding** [omnetpp/omnetpp#847]
**Platform**
 - OMNeT++ version: 5.6.2
 - VM OS: Ubuntu 20.04.1 LTS
 - Host OS: Windows 10 Version 2004 (Build 19041)

**Describe the bug**
I wanted to launch omnetpp in my WSL terminal. I can launch other gui applications like gedit with my X Server from there without issue. When I enter "omnetpp" into the terminal, nothing happens.

**To Reproduce**
1. Follow the [Installing OMNeT++ on Windows Subsystem for Linux (WSL 2)](https://docs.omnetpp.org/articles/wsl2/) Instructions
2. Try to launch omnetpp

**Comment by rhornig** [comment]
It's hard to say what is causing this. First you should check whether there are any issues starting the IDE itself. The error log should be available in the `ide/error.log` file. Also please check whether the actual Qtenv samples (e.g. samples/aloha) is running and displaying correctly.

**Comment by rhornig** [comment]
WSLg 2 (GUI apps in WSL) is working with omnet 6 and should solve this issue.
