### ISSUE TITLE
firstAvailableOrEmpty

### ISSUE THREAD

**Issue by TangJiZ** [omnetpp/omnetpp#849]
how can i find it (firstAvailableOrEmpty) and how to use it , thanks

**Comment by torokati44** [comment]
This is an issue tracker for reporting bugs and problems with OMNeT++ itself, and not the right place to ask for guidence on how to use it.

**Comment by TangJiZ** [comment]
> This is an issue tracker for reporting bugs and problems with OMNeT++ itself, and not the right place to ask for guidence on how to use it.

thanks for your answer but what's the meaning of this?    （  firstAvailableOrEmpty("Udp") != ""  ）this is in inet framework  ,thanks.
