### ISSUE TITLE
Simulation manual doesn't document `itervar` lines.

### ISSUE THREAD

**Issue by vassilyl** [omnetpp/omnetpp#850]
Appendix I: Result File Formats in Simulation Manual (/doc/src/manual/appendix-result-file-formats.tex) doesn't say a word about lines starting with 'itervar'.

**Comment by torokati44** [comment]
You are right, this is an unfortunate omission of the documentation.
They were [separated from run attributes a couple versions ago](https://github.com/omnetpp/omnetpp/commit/faeb5ea36a2aa16305364ff2740d4f1442e458b5) to make them distinguishable.
They can still be parsed the same way - they just use a different keyword.
Thanks for the report!

**Comment by avarga** [comment]
Currently working on updating the manual, will be fixed in the next 6.0 prerelease.
