### ISSUE TITLE
Project Explorer in OMNeT++ 6.0pre9 do not show any information about projcet,such as ,project name 

### ISSUE THREAD

**Issue by Stephenhua** [omnetpp/omnetpp#852]
When I install OMNET++ 6.0pre9  in windows, open IDE ,Project Explorer  do not show any information about projcet,such as ,project name . I don't konw why .How to slove it.

**Comment by torokati44** [comment]
There is not nearly enough information in this report for us to be able to do anything about it.
Do you have any projects in the workspace in the first place?
What information about what project do you expect to see there?
What do you see instead?

**Comment by Stephenhua** [comment]
I do not know how to descirbe .You can browse this url: https://stackoverflow.com/questions/65037193/project-explorer-in-omnet-6-0pre9-do-not-show-any-information-about-porject .I think you will understand when you see image in url.

**Comment by torokati44** [comment]
This is rather strange...
Do you see any error messages printed anywhere, like in the Error Log, or in the terminal?
Do any other Eclipse-based tools (for example, vanilla Eclipse JDT or CDT) have the same issue?
Does this happen with other projects (OMNeT++ samples or INET) as well?

**Comment by Stephenhua** [comment]
It's amazing. I install OMNeT++ with other version , this problem can not appear ,so I do not know why.,and I am trying install many times, this problem still exist . when I install it , I can not see any error messages printed anywhere.  Click with the mouse to see that there are directories, but the name of the directory will not be displayed. Even if I create a new project file, the new project file name will not be displayed.

**Comment by avarga** [comment]
The IDE logs errors to the `<workspace>/.metadata/.log` file. The workspace is normally the "samples" directory of your OMNeT++ installation. Does that file contain something interesting?

**Comment by Stephenhua** [comment]
> The IDE logs errors to the `<workspace>/.metadata/.log` file. The workspace is normally the "samples" directory of your OMNeT++ installation. Does that file contain something interesting?
I open this log file， but  I do not konw if this flie contain something interesting. I open  `<workspace>/ide/error.log` file, I find som error messages :
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by Stephenhua** [comment]
> This is rather strange...
> Do you see any error messages printed anywhere, like in the Error Log, or in the terminal?
> Do any other Eclipse-based tools (for example, vanilla Eclipse JDT or CDT) have the same issue?
> Does this happen with other projects (OMNeT++ samples or INET) as well?

I open <workspace>/ide/error.log file, I find som error messages :
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by rhornig** [comment]
I cannot reproduce this. Hopefully newer Eclipse versions bundled with OMNeT++ 6.0 fixed this. If not, please reopen this with additional info.
