### ISSUE TITLE
Incorrect Python path on macOS

### ISSUE THREAD

**Issue by screw** [omnetpp/omnetpp#854]
**Platform**
 - OMNeT++ version: 6.0_pre9
 - OS: [e.g. macOS Catalina 10.15.7]

**Describe the bug**
./configure fails checking to run Python

Checking the previous version (pre7) the provided python (tools/macosx/lib/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python) uses relative path (executable_path/../../../../Python)

but the one in pre9 refers to specific system path (which might not exist since you have a newer version of python 3.5 installed)

**To Reproduce**
run ./configure

**Comment by screw** [comment]
The output from the configure script
```
checking if all necessary Python modules are available... dyld: Library not loaded: /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/Python
  Referenced from: <my-path>/omnetpp-6.0pre9/tools/macosx/lib/Python.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python
  Reason: image not found
```
And system python
```
ls /usr/local/Cellar/python@3.8
3.8.6_2
```

**Comment by rhornig** [comment]
Thanks for reporting. I will check this. It's definitely an issue with the bundled toolchain.

**Comment by rhornig** [comment]
Confirmed. I fixed the issue and will bundle a corrected version with preview 10. (in addition I have also figured out that python's site-packages was not bundled which contains all locally installed python packages like numpy, matplotlib etc.). If someone has the urgent need, I can provide a separate toolchain archive that works with the current preview 9. just let me know)

**Comment by torokati44** [comment]
Now with 6.0pre10 released, this should be resolved.

**Comment by torokati44** [comment]
If it were to happen again, feel free to reopen, @screw.
