### ISSUE TITLE
Toolbar icons are not displayed in the simulation window

### ISSUE THREAD

**Issue by kevinyuan** [omnetpp/omnetpp#855]
**Platform**
 - OMNeT++ version: omnetpp-6.0pre9
 - OS: omnetpp-6.0pre9

**Describe the bug**
Toolbar icons are not displayed in the simulation window, please see the screenshot:

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/231197/101588196-c7c6ef80-3a20-11eb-825c-dd6836ee00ad.png">

**To Reproduce**
> cd omnetpp-6.0pre9/samples/dyna 
> ./dyna

**Comment by torokati44** [comment]
Please fill in the OS information appropriately!
What version of Qt do you have? You can check this in the Help > About Qtenv dialog.
How was this Qt installed - from a standard package repository, or downloaded separately?
Are there any messages printed to the console?

**Comment by torokati44** [comment]
If your OS has a package named `libqt5svg5` or `qt5-qtsvg`, or similar, make sure it is installed.

**Comment by kevinyuan** [comment]
Hi @torokati44 :

Qtenv was compiled with Qt 5.9.7, is runing with Qt 5.9.7.

Is that ok?

Thanks.

**Comment by kevinyuan** [comment]
@torokati44 ,

Just installed qt5-qtsvg and it works.

thanks
:)

**Comment by torokati44** [comment]
Interesting that you had the rest of the Qt base package installed, but not QtSVG.
Maybe we should mention this package as well in the Install Guide?
