### ISSUE TITLE
Missing instructions to install scipy

### ISSUE THREAD

**Issue by screw** [omnetpp/omnetpp#856]
**Platform**
 - OMNeT++ version: 6pre9
 - OS: Ubuntu 20.04

**Describe the bug**
The install guide is missing instructions to install scipy python package.
Trying to plot any data results in an error (on module import).

**To Reproduce**
Try to plot some data.

Fix: pip3 install scipy

**Comment by torokati44** [comment]
Thanks, we'll update the Install Guide.

**Comment by torokati44** [comment]
https://github.com/omnetpp/omnetpp/commit/c11f57efffe724e941366a37b9cd5d7d5f002d7b adds SciPy to the list of Python packages that need to be installed.
