### ISSUE TITLE
Windows 10 20h2: OMNeT++ 6.0 preview 10/11: Linking with INET 3.7.0/3.7.1 fails

### ISSUE THREAD

**Issue by Musteblume** [omnetpp/omnetpp#862]
**Platform**
 - OMNeT++ 6.0 preview 10
 - OS: Windows 10 20h2

**Describe the bug**
- Linking with INET 3.7.0 fails with multiple "lld-link: error: duplicate symbol:" errors
- Also tested in Ubuntu 20.04: No errors
- I think this is related to a msys2 issue: https://github.com/msys2/MINGW-packages/issues/6855
   -> The proposed workaround "LDFLAGS += -Wl,-Xlink=-force:multiple" fixed it for me.

**To Reproduce**
- Install OMNeT++ 6.0 preview 10
- Clone, import and build inet v3.7.0
- Clone Import CoRE4INET (https://github.com/CoRE-RG/CoRE4INET)
- Add/Edit following lines in makefrag:
  `CFLAGS += -std=c++14`
  `MSGCOPTS += --msg4`
- In src/core4inet/utilities/modules/MessageNumProfiler replace:
  `defaultListSize()` with `getNumOwnedObjects()`
  `defaultListGet(i)` with `getOwnedObject(i)`
- Build CoRE4INET

**Comment by Musteblume** [comment]
Sadly, the workaround crashes the linker when used in further projects dependent on CoRE4INET (ex. SignalsAndGateways - https://github.com/CoRE-RG/SignalsAndGateways). Again, on Linux Ubuntu 20.04 there are no problems.

**Comment by Musteblume** [comment]
Still present in OMNeT++ 6.0 preview 11 with INET 3.7.1

**Comment by rhornig** [comment]
This is a model related issue. I'm closing this as this will be tracked at: https://github.com/inet-framework/inet/issues/723
