### ISSUE TITLE
Cannot import message files from neighboring directory without adding '../src' to include paths

### ISSUE THREAD

**Issue by edlongman** [omnetpp/omnetpp#866]
**Platform**
  -  OMNeT++ version: 5.6.2
  -  OS: Windows (not relevant)

**Describe the bug**

When restructuring my project I tried to import a `defs.msg` with `import common.defs`  into `linklayer/linkLayerFrame.msg` . `defs.msg` contains some definitions. The project looked like so:
```
+-src
    +-common
    |    +-defs.h
    |    +-defs.msg 
    |       +   cplusplus {{
    |       |       #include "common/defs.h"
    |       ╚   }}
    +-linklayer
        +-linkLayerFrame.msg
```

I had a problem with the message compiler, which would give the following error compilling
linkLayerFrame.msg
`Error: cannot resolve import 'common.defs'`
```py
import common.defs;
import inet.common.packet.chunk.Chunk;
import inet.linklayer.common.MacAddress;

namespace msg_import_bug;

enum FrameType {
    DATA = 1;
    WU_ACK = 2;
};

class Datagram extends inet::FieldsChunk
{
    FrameType type;
    inet::MacAddress transmitterAddress;
    inet::MacAddress receiverAddress;
}
```

Which was being compiled with: 
`opp_msgc --msg6 -s _m.cc -MD -MP -MF ../out/gcc-release/src/linklayer/linkLayerFrame_m.h.d -I../../inet/src linklayer/linkLayerFrame.msg`
**To Reproduce**
Attached project:
[msg_import_bug.zip](https://github.com/omnetpp/omnetpp/files/5893908/msg_import_bug.zip)

Does not build unless `../src` is added to C/C++ Build -> Paths and Symbols -> Includes 

**Problem**
It is implied that, like `.ned` files messages will be included if they are within the directory structure of the same package. But this is not the case and it is not explained anywhere that the C/C++ include paths are relevant for the msgtool.

**Comment by Avian688** [comment]
Have the same error, any update on a fix?

**Comment by rhornig** [comment]
Works as expected. It expected that the root of the source tree is added to the c++ include path and the message path.
