### ISSUE TITLE
error: invalid use of incomplete type ‘struct std::hash<omnetpp::scave::ResultItem::FieldNum>’ in omnetpp/src/common/stlutil.h

### ISSUE THREAD

**Issue by BingLiHanShuang** [omnetpp/omnetpp#868]
**Platform**
 - OMNeT++ version: omnetpp-6.0pre5
 - OS: Ubuntu 16.04

**Describe the bug**
When make, it report:
error: invalid use of incomplete type ‘struct std::hash<omnetpp::scave::ResultItem::FieldNum>’ in omnetpp/src/common/stlutil.h and stop make.

**To Reproduce**
I change tag to omnetpp-5.4.1 and this problem doesn't happen.

**Comment by BingLiHanShuang** [comment]
It seems a problem related with unordermap in g++. My g++ version is 5.3.1.(latest in Ubuntu16.04)

**Comment by avarga** [comment]
Yes, your compiler is too old. Looks like we need to update our checks for minimum required compiler version in the configure script.

**Comment by rhornig** [comment]
only ubuntu 20.04 or later is supported with omnetpp-6.0
