### ISSUE TITLE
Provide API to get Submodule Type from NED file

### ISSUE THREAD

**Issue by t-moe** [omnetpp/omnetpp#869]
### Feature Request

**Summary**

Provide an API method to get the Submodule Type (typename) from a NED file.
E.g I would like to get the string "Ieee80211g" from C++ when having a NED file like:

```
network Network
{
    parameters:
        node[*].nic.typename = "Ieee80211g";
    submodules:
        node: Node[100];
}
```

**Description**

The Omnet Manual Section  [3.11 Parametric Submodule and Connection Types](https://doc.omnetpp.org/omnetpp/manual/#sec:ned-lang:submodule-like) states that it is preferred to use "Typename pattern assignments" over "node type strings" when specifying submodule types. 

This works well as long as the submodules are constructed by the simulation core. If I as a user want to create the submodules dynamically (e.g. using `cModuleType::find(modtypename)->create(..)` as seen in netbuilder.cc of the routing example), then I have to escape to "node type strings" again, because there's no API to query the "Typename pattern assignments".

It seems as the functionality is already there in [cNedNetworkBuilder::getSubmoduleTypeName](https://github.com/omnetpp/omnetpp/blob/master/src/sim/netbuilder/cnednetworkbuilder.cc#L626), it's just not exposed as public API.

**Comment by avarga** [comment]
The NED type name is already available via the "component type" object of the module (`cComponentType`).
`module->getComponentType()->getFullName()` returns the NED type in a fully qualified form (i.e. including the package name), and `module->getComponentType()->getName()` returns the unqualified name, i.e. just the part after the last dot.
