### ISSUE TITLE
Update MSYS2 version

### ISSUE THREAD

**Issue by a-huk** [omnetpp/omnetpp#871]
**Platform**
 - OMNeT++ version: 5.6.2
 - OS: Windows 10

**Describe the bug**
Msys2 is used to launch omnetpp, but it also has python, bash and other commands. It does not however have pip by default. It can be installed with pacman. The issue is that it is an old verion that does not support the current zstd packages. In addition manually updating pacman results in breaking it. However, it fully work in the current/latest version of msys2. Therefore, could you update msys2, especially pacman?

**To Reproduce**
Run these https://www.msys2.org/news/#2020-12-26-zstd-exemption-for-core-packages-removed in the msys2 terminal given by mingwenv.cmd

**Comment by zigen** [comment]
@a-huk 
FYI I also faced the same problem and partially solved it with omnetpp6 zip contents. 
In my solution still has a problem that cannot build omnet with OSG

https://github.com/sfc-aqua/quisp/wiki/Windows-Setup-note
