### ISSUE TITLE
Scavetool cannot filter histograms when histogram data is of limited precision

### ISSUE THREAD

**Issue by edlongman** [omnetpp/omnetpp#872]
Platform details: Windows 10, OMNeT 5.6.2, build: 200518-aa79d0918f

I ran a simulation with reduced precision of scalars (that took many hours to complete)

Some of the histogram bins have ended up the same as a consequence, I don't care about this (broken) statistic at the moment and need to filter to only the statistic I need using `scavetool`. *It filters fine in the IDE*, but I need to use the command line tool due to the large size and large number of different run files.

<details><summary>The file (minimum example) </summary>
<p>

```
version 2
run DutyCycleInvestigation-0-20210308-16:17:59-12004
attr configname DutyCycleInvestigation
attr datetime 20210308-16:17:59
attr experiment DutyCycleInvestigation
attr inifile omnetpp.ini
attr iterationvars "$dcMult=0"
attr iterationvarsf dcMult=0
attr measurement "$dcMult=0"
attr network MixedDCNetwork
attr processid 12004
attr repetition 0
attr replication #0
attr resultdir results
attr runnumber 0
attr seedset 0
itervar dcMult 0

statistic MixedDCNetwork.node20.wlan[0].mac.monitor unknownConsumption:histogram
field count 1
field mean 0.000388162
field stddev 0.000000000
field min 0.000388162
field max 0.000388162
field sum 0.000776324
field sqrsum 3.01339e-007
attr title "Energy consumption of unknown source, histogram"
bin	-inf	0
bin	0.000388162	1
bin	0.000388162	0
bin	0.000388162	0
bin	0.000388162	0

statistic MixedDCNetwork.node7.packetMonitor packetReceivedEnergyConsumed:histogram
field count 99
field mean 0.00182593
field stddev 0.000757531
field min 1.44e-005
field max 0.0002
field sqrsum 0.00340968
attr title "Energy used by packet for transmission to destination, histogram"
bin	-inf	0
bin	0	3
bin	0.0001	2
bin	0.0002	94
```
</p>
</details>

The scave command being run:
```
scavetool x -f "name(packetReceived*:histogram)" test.sca -o test-Sparse.sca
```

The error output:
```
scavetool: Assert: Condition 'bins.empty() || lowerBound > bins.back().lowerBound' does not hold in function 'addBin' at C:/<omnetppdir>/src/common/histogram.h:58, file test.sca, line 30
```

Changing the following lines to have increasing bin values prevents the bug from appearing:

```
attr title "Energy consumption of unknown source, histogram"
bin	-inf	0
bin	0.000388162	1
bin	0.000388162	0
bin	0.000388162	0
bin	0.000388162	0
```

**Comment by torokati44** [comment]
Thanks for the detailed report, it was really useful!

I'm not sure when a new 5.x release will come out, but until then, this is what I ended up doing to fix it:

```diff
--- a/src/common/histogram.h
+++ b/src/common/histogram.h
@@ -55,8 +55,13 @@ class COMMON_API Histogram {
 
 inline void Histogram::addBin(double lowerBound, double count)
 {
-    Assert(bins.empty() || lowerBound > bins.back().lowerBound); // preserve ordering
-    bins.push_back(Bin { lowerBound, count} );
+    if (!bins.empty())
+        Assert(lowerBound >= bins.back().lowerBound); // preserve ordering
+    if (!bins.empty() && lowerBound == bins.back().lowerBound)
+        bins.back().count += count;
+    else
+        bins.push_back(Bin { lowerBound, count} );
 }
 
 inline void Histogram::collect(double value, double weight)
 ```
 
This will admittedly change these irregular histograms even when they are reexported without (intentional) modification, but I don't think this bin merging will make them significantly less accurate or useful.

The same issue was also in `master` (so, the 6.0 pre-releases), it's nice that this is now also fixed in there!

And finally, may I ask what was the reason for you lowering the scalar precision? To save disk space?

**Comment by edlongman** [comment]
Thank you, I had to just go through the files manually removing the broken statistic but no doubt it will happen again in the future so it's very useful. 

Yes, it was to save disk space, I'd applied precision limiting to both scalars and vectors. In hindsight, it was only needed for the vectors as the scalar files aren't that big!
