### ISSUE TITLE
Inconsistent Fingerprint computation but only *slightly* wrong

### ISSUE THREAD

**Issue by edlongman** [omnetpp/omnetpp#873]
**Platform**
 - OMNeT++ version: 5.6.2, build: 200518-aa79d0918f
 - OS: Windows 10

**Describe the bug**
The fingerprint computation is inconsistent. If the simulation is run via the command line, the fingerprint is verified. If it is run in the QtGui the statistics fingerprint (`zvs`) is completely wrong and the messages, signals fingerprint is **slightly** wrong.

**To Reproduce**
I can provide code examples privately on request (personal git reference: cab121abe92b95c68d117a1892dc54343a2a749e)

Fingerprint (Fp) results 
Environment | Sim Speed setup | Stats Fp (/zvs) | Struct/Event Fp (/tplx) | 
------------ | -------------| ----------------| ----------|
CmdEnv | Express | 7880-7526 |  2765-c880 ☑ |
CmdEnv | Normal | 7880-7526 |  2765-c880 ☑ |
QtEnv | Express | 8fe4-9555 | 2765-c880 ☑ |
QtEnv | Fast | 6bbe-17a5 | **2545-f1c3** ❌ |
QtEnv | Normal till t=5s, Express to end | bd7a-35fa | 2765-**e**88**2** ❌ |
QtEnv | Fast till t=400s, Express to end | 766c-eb73  | **e1**65-**a**880 ❌|
QtEnv |Fast till t=100.545673152053s, <br/>Fast till t=400s, Express to end| 6097-60e5 | 2765-c880 ☑ |

**Comment by torokati44** [comment]
Thanks for the report!
If you could share the complete repro case (including your code), that would help a lot in tracking this down!

**Comment by edlongman** [comment]
I have emailed my code as an example of what doesn't work. Let me know if you are unable to reproduce the problem.

Thank you

**Comment by torokati44** [comment]
I got it to build and run, but none of the Configs run to completion. I'm always getting this error, no matter which run mode I choose:
```
Cannot switch to a new radio mode while another switch is in progress -- in module (inet::physicallayer::FlatRadioBase) IntermittentDenseTest.node2.wlan[0].dataRadio (id=175), at t=0.516558940003s, event #687
```
Have you made any modifications to INET 4.2.0 to make it work?

**Comment by edlongman** [comment]
Yes, I have. 
Please appply the attached git patch file.


[0001-Patch-Radio-bugs.patch.txt](https://github.com/omnetpp/omnetpp/files/6433542/0001-Patch-Radio-bugs.patch.txt)

**Comment by torokati44** [comment]
Yeah, the patch. I forgot about that, sorry.

**Comment by torokati44** [comment]
The mismatches seem to originate from `inet::power::SimpleEpEnergyStorage`, as it incorrectly changes state in  `getResidualEnergyCapacity() const`, which is called from `refreshDisplay()`.

Here is a stack trace as evidence:
![image](https://user-images.githubusercontent.com/288816/117328198-b11faa00-ae93-11eb-83ab-993b9b7a09df.png)

`Cmdenv` never calls `refreshDisplay()`, so the fingerprints remain deterministic. I backported the `fake-gui` feature - which causes `Cmdenv` to _do_ call `refreshDisplay()`, and was made to spot exactly these kind of mistakes - to 5.6.2, and enabling it again makes the fingerprints unstable.

`Qtenv` calls `refreshDisplay()` fairly often, but at completely undeterministic times - which is why this function must never alter simulation state. One exception is in "Express" mode, with auto-update disabled, in which case `Qtenv` also doesn't call `refreshDisplay()`, except maybe once after the simulation has terminated - which explains why the "slight" differences are possible: it only alters the final fingerprint incorrectly once, at the very end.

**Comment by torokati44** [comment]
After removing this single line from `SimpleEpEnergyStorage.cc`:
```c++
    const_cast<SimpleEpEnergyStorage *>(this)->updateResidualCapacity();
```

I am no longer able to generate any fingerprints other than `3d3b-5814/zvs, ca58-3a9f/tplx` from the `IntermittentLowRateTest` config, no matter how much I vary the environment used, the run modes, or display updates, even within a single run.

Perhaps this could be added to your INET patch.
Do you plan to submit those changes as PRs BTW? Do you consider those actual fixes, or just hacks/workarounds?

**Comment by edlongman** [comment]
Thanks for finding that. I’m not sure I can remove that though, since I use that function in some of my models which require an up to date value for the residual capacity, not just the value when the last event happened. The const_cast in the const function is a sneaky piece of work that violates the const-ness so shouldn’t really be there to be honest! 

Possibly this could be the moment to implement the stub function `SimpleEpEnergyManagement::getEstimatedEnergyCapacity()`. 

I think I’ve already submitted most as PRs but they were merged into master and not into v4.2.x Will there be another version of v4.2 that I could get them merged into? I’ve also slightly lost track of the patches I’ve made so would just have to submit as one big PR to v4.2!

**Comment by torokati44** [comment]
Okay, I see that all of that patch is now in master, I'm cherry-picking them over to 4.2.x :)

**Comment by edlongman** [comment]
Ok, I've created pull requests to inet for all my fixes I think. Just inet-framework/inet#695 and inet-framework/inet#696 and you've made the issue for the getResidualCapacity so I'll consider this topic closed. Thanks

**Comment by torokati44** [comment]
We're planning to add the ability to set a custom seed for the fake-gui feature of Cmdenv - both in 6.0 and 5.6 -, which will be useful for spotting these kinds of fingerprint stability issues - originating from `refreshDisplay()` calls - in the future.

**Comment by torokati44** [comment]
Thanks for the PRs (again)!
