### ISSUE TITLE
For non zero exit codes, returning the integer exit value is not helpful. Hexidecimal would be much better

### ISSUE THREAD

**Issue by edlongman** [omnetpp/omnetpp#875]
https://github.com/omnetpp/omnetpp/blob/00f99d59c385eff8c5068134ea9af7fb90a9a192/ui/org.omnetpp.launch/src/org/omnetpp/launch/SimulationLauncherJob.java#L191

For example: `Simulation terminated with exit code: -1073741571` vs `Simulation terminated with exit code: 0xC00000FD`

and `Simulation terminated with exit code: -1073741819` vs `Simulation terminated with exit code: 0xC0000005` 

This may just be the way windows presents errors, but doing a google search for the in form is always futile!

**Comment by rhornig** [comment]
Fixed in 6.0
