### ISSUE TITLE
anybody can access to database?

### ISSUE THREAD

**Issue by jky000** [omnetpp/omnetpp#879]
**Platform**
 - OMNeT++ version: 6.0
 - OS: Windows10

**Describe the bug**
the samples/database can't work now according to Read me.txt
anybody can help me? I'll appreciate it

**To Reproduce**
Help the development team to reproduce the issue.
Provide step-by-step instructions, code examples, etc.

**Comment by rhornig** [comment]
That sample is not maintained and no longer part of the distribution
