### ISSUE TITLE
Omnetpp-6.0pre11 Pointer displayed at screen native dpi

### ISSUE THREAD

**Issue by smblackledge** [omnetpp/omnetpp#882]
My laptop has a 4K screen.  The Omnetpp-6.0pre11 pointer is displayed at the native dpi rather than enlarged to the same size as the rest of the screen elements.  It is rather hard to locate.

:joke I have not had to practice squinting for several years.  Please help save my eyesight.  (Maybe organize a telethon?  Just think of what celebrities we could get to volunteer.) :joke

**Comment by rhornig** [comment]
Is this happening in the IDE or the Qtenv? What is the operating system? Win/Linux/macOS?

**Comment by smblackledge** [comment]
It is in the IDE which runs on Linux 20.04.  BUT, MobaXterm is the way to the server.  It runs on Windows 10 and I use "ssh -X" to get to the server.

**Comment by smblackledge** [comment]
I've noticed that the pointer returns to the full size when on the title bar.

**Comment by rhornig** [comment]
This might be some configuration issue with the XServer. Sadly this is outside of control of us apart from trying to upgrade to the latest Eclipse version.
