### ISSUE TITLE
During it's make, inet4 is not a clean compile

### ISSUE THREAD

**Issue by smblackledge** [omnetpp/omnetpp#883]
**Platform**
 - OMNeT++ version: 6.0pre11
 - OS: Ubuntu 20.04
 - inet version: inet4 (4.3.1)

---

**Problem**
When autoload and make specified, 23 warnings and 8 info messages are created by clang

---

**Compiler Messages**

Description	Resource	Path	Location	Type
'~PimNeighbor' has a non-throwing exception specification but can still throw [-Wexceptions]	PimNeighborTable.cc	/inet4/src/inet/routing/pim/tables	line 40	C/C++ Problem
'forceTransmissionFinishTime' is deprecated [-Wdeprecated-declarations]	EtherBus.cc	/inet4/src/inet/linklayer/ethernet	line 240	C/C++ Problem
'forceTransmissionFinishTime' is deprecated [-Wdeprecated-declarations]	EtherHub.cc	/inet4/src/inet/linklayer/ethernet	line 179	C/C++ Problem
'forceTransmissionFinishTime' is deprecated [-Wdeprecated-declarations]	EtherMac.cc	/inet4/src/inet/linklayer/ethernet	line 706	C/C++ Problem
'forceTransmissionFinishTime' is deprecated [-Wdeprecated-declarations]	Ppp.cc	/inet4/src/inet/linklayer/ppp	line 132	C/C++ Problem
'hasher' is deprecated [-Wdeprecated-declarations]	NetworkCommunicationFingerprintCalculator.cc	/inet4/src/inet/common	line 42	C/C++ Problem
'hasher' is deprecated [-Wdeprecated-declarations]	NetworkCommunicationFingerprintCalculator.cc	/inet4/src/inet/common	line 43	C/C++ Problem
'hasher' is deprecated [-Wdeprecated-declarations]	NetworkCommunicationFingerprintCalculator.cc	/inet4/src/inet/common	line 47	C/C++ Problem
'hasher' is deprecated [-Wdeprecated-declarations]	NetworkCommunicationFingerprintCalculator.cc	/inet4/src/inet/common	line 49	C/C++ Problem
'hasher' is deprecated [-Wdeprecated-declarations]	NetworkCommunicationFingerprintCalculator.cc	/inet4/src/inet/common	line 58	C/C++ Problem
'hasher' is deprecated [-Wdeprecated-declarations]	NetworkCommunicationFingerprintCalculator.cc	/inet4/src/inet/common	line 63	C/C++ Problem
'setDeliverOnReceptionStart' is deprecated: Renamed to setDeliverImmediately() -- please use the new name [-Wdeprecated-declarations]	EtherBus.cc	/inet4/src/inet/linklayer/ethernet	line 97	C/C++ Problem
'setDeliverOnReceptionStart' is deprecated: Renamed to setDeliverImmediately() -- please use the new name [-Wdeprecated-declarations]	EtherHub.cc	/inet4/src/inet/linklayer/ethernet	line 42	C/C++ Problem
'setDeliverOnReceptionStart' is deprecated: Renamed to setDeliverImmediately() -- please use the new name [-Wdeprecated-declarations]	EtherHub.cc	/inet4/src/inet/linklayer/ethernet	line 118	C/C++ Problem
'setDeliverOnReceptionStart' is deprecated: Renamed to setDeliverImmediately() -- please use the new name [-Wdeprecated-declarations]	EtherMac.cc	/inet4/src/inet/linklayer/ethernet	line 103	C/C++ Problem
'setDeliverOnReceptionStart' is deprecated: Renamed to setDeliverImmediately() -- please use the new name [-Wdeprecated-declarations]	EtherMacFullDuplex.cc	/inet4/src/inet/linklayer/ethernet	line 65	C/C++ Problem
'setDeliverOnReceptionStart' is deprecated: Renamed to setDeliverImmediately() -- please use the new name [-Wdeprecated-declarations]	NoiseSource.cc	/inet4/src/inet/physicallayer/common/packetlevel	line 47	C/C++ Problem
'setDeliverOnReceptionStart' is deprecated: Renamed to setDeliverImmediately() -- please use the new name [-Wdeprecated-declarations]	Radio.cc	/inet4/src/inet/physicallayer/common/packetlevel	line 58	C/C++ Problem
'setDeliverOnReceptionStart' is deprecated: Renamed to setDeliverImmediately() -- please use the new name [-Wdeprecated-declarations]	ShortcutRadio.cc	/inet4/src/inet/physicallayer/shortcut	line 42	C/C++ Problem
format string is not a string literal (potentially insecure) [-Wformat-security]	SignalBasedTokenGenerator.cc	/inet4/src/inet/queueing/tokengenerator	line 51	C/C++ Problem
format string is not a string literal (potentially insecure) [-Wformat-security]	SignalBasedTokenGenerator.cc	/inet4/src/inet/queueing/tokengenerator	line 57	C/C++ Problem
format string is not a string literal (potentially insecure) [-Wformat-security]	SignalBasedTokenGenerator.cc	/inet4/src/inet/queueing/tokengenerator	line 63	C/C++ Problem
overlapping comparisons always evaluate to true [-Wtautological-overlap-compare]	Ospfv3InterfaceState.cc	/inet4/src/inet/routing/ospfv3/interface	line 206	C/C++ Problem
'forceTransmissionFinishTime' has been explicitly marked deprecated here	inet4		line 321, external location: /home/localuser/scott/omnetpp-6.0pre11/include/omnetpp/cchannel.h	C/C++ Problem
'hasher' has been explicitly marked deprecated here	inet4		line 154, external location: /home/localuser/scott/omnetpp-6.0pre11/include/omnetpp/cfingerprint.h	C/C++ Problem
'setDeliverOnReceptionStart' has been explicitly marked deprecated here	inet4		line 387, external location: /home/localuser/scott/omnetpp-6.0pre11/include/omnetpp/cgate.h	C/C++ Problem
destructor has a implicit non-throwing exception specification	PimNeighborTable.cc	/inet4/src/inet/routing/pim/tables	line 38	C/C++ Problem
expanded from macro 'ASSERT'	inet4		line 51, external location: /home/localuser/scott/omnetpp-6.0pre11/include/omnetpp/simkerneldefs.h	C/C++ Problem
treat the string as an argument to avoid this	SignalBasedTokenGenerator.cc	/inet4/src/inet/queueing/tokengenerator	line 51	C/C++ Problem
treat the string as an argument to avoid this	SignalBasedTokenGenerator.cc	/inet4/src/inet/queueing/tokengenerator	line 57	C/C++ Problem
treat the string as an argument to avoid this	SignalBasedTokenGenerator.cc	/inet4/src/inet/queueing/tokengenerator	line 63	C/C++ Problem

---

Here's the setup and installation process so far:

These are the updates I used for my .bashrc. With them, I don't even need the ". setenv".

    export PATH=/usr/lib/ccache:$HOME/scott/omnetpp-6.0pre11/bin:$PATH
    export PATH=$PATH:$HOME/.local/bin
    export LD_LIBRARY_PATH=$HOME/scott/omnetpp-6.0pre11/lib
    export PYTHONPATH=$HOME/scott/omnetpp=6.0pre11/python:$PYTHONPATH

Then from the terminal (started with "ssh -XC servername")

    Download omnetpp-6.0pre11 to your directory (in my case, it is /home/localuser/scott)
    $ cd  scott
    $ tar xvfz omnetpp-6.0pre11-src-linux.tgz
    $ ./configure
    $ make
    $ omnetpp

    Indicate the Workbench (I use the default Samples)
    When the popup asks if you want to autoload/install inet, I just click on the OK/Yes/whatever button
    All should be well at this point. inet4 is now loaded and made

**Comment by rhornig** [comment]
This is not an OMNeT++ issue, though INET 4.3.8 and OMNEt++ 6.0 final is building fairly celan.
