### ISSUE TITLE
Icon size (large) in Display String Tags Shows ?? in QtEnvironment

### ISSUE THREAD

**Issue by edlongman** [omnetpp/omnetpp#885]
**Platform**
 - OMNeT++ version: 5.4
 - OS: Windows

**Describe the bug**
Size setting for icon does not display in QtEnv

**To Reproduce**

```
        node1: <default("...")> like INetworkNode {
            @display("i=old/x_green;p=10.76,108.90;is=l");
        }
```

Shows as: 
![image](https://user-images.githubusercontent.com/693456/126189870-23a4a200-c5c3-4ef0-86f5-745f08f7d453.png)

**Comment by torokati44** [comment]
The icon size (`is`) DisplayString tag acts as a (`_`-separated) suffix during image lookup, so it actually selects a different image file to be loaded and used - as an attempt to make them look good in any size, providing an opportunity to hand-tune the different size variants.
As you can see, quite a few of the icons in the `old/` folder have different sized variants, and in case the selected (optionally size-specific) file doesn't exist, the icon is replaced with this inquisitive placeholder.
At the moment, the icons used for modules can't be resized (stretched) to a different size than their native sizes (except for whole-window HiDPI scaling of course, but that's entirely done by Qt).

If you wish to add custom images (or even just additional size variants for existing images) to your project, create an `images` folder in the project root. Both the IDE and Qtenv will load `.png` files from there - and names conflicting with the factory built-ins will even take priority there. This is also done in INET, for example.
