### ISSUE TITLE
Running `mingwenv.cmd ide` errors to "Cannot find ...\ide\omnest"

### ISSUE THREAD

**Issue by edlongman** [omnetpp/omnetpp#887]
**Platform**
 - OMNeT++ version: 5.6
 - OS: Windows 10

**Steps to reproduce**
From a fresh install of OMNeT++ 5.6 I ran `{{path}}/omnetpp/mingwenv.cmd ide` to start the IDE without running the omnetpp command.

> Windows Cannot find '{{path}}\bin\\..\ide\omnest'. Make sure you typed the name correctly and then try again?

This runs `bin/omnetpp.cmd` but that tries to run `omnest`

**To Fix**
edit `bin\omnetpp.cmd` 

Change: `SET LAUNCHER=omnest` to `SET LAUNCHER=omnetpp`

**Comment by rhornig** [comment]
The make process on 6,0 now installs correcnt .LNK files in the WIndows start menu that allows starting the IDE from the start menu instead of command line.
