### ISSUE TITLE
Understanding Simulation time (simtime_t)

### ISSUE THREAD

**Issue by lingcy0328** [omnetpp/omnetpp#889]
Hi Guys, I am currently confusing on how simulation time works in omnetpp. More specifically, what is the code section below means?

simtime_t waitDelay1Time = -1;

Is it means that the simtime_t variable "waitDelay1Time" has the value of -1 second? If yes, why we have negative value of time? If no, what is its exact meaning?

**Comment by edlongman** [comment]
It is probably better to ask questions about code stack exchange generally.

When it is set to -1 that is normally because it is initialized later in the CLASS::initialize() from a parameter value.
So -1 is just the initialization value or to indicate that it is not in use.
