### ISSUE TITLE
Misleading warning "Parameter refers to itself in its assignment" when setting submodule parameters

### ISSUE THREAD

**Issue by edlongman** [omnetpp/omnetpp#893]
**Platform**
 - OMNeT++ version: 6.0pre12
 - OS: Windows 10

**Describe the bug**
The NED builder will not construct a module which sets a submodule parameter from it's own parameter using parent notation. Giving the error: Parameter refers to itself in its assignment (did you mean 'parent.displayAddresses'?)

```js
module ProblematicNode
{
    parameters:
        string radioMediumModule;
        **.radioMediumModule = default(absPath(radioMediumModule));
}
```
But when set to `parent.radioMediumModule` it doesn't evaluate it in the right context, and tries to find it in the parent of the parent "SimpleNet has no parameter named..."
```js
module ProblematicNode
{
    parameters:
        @networkNode;
        bool displayAddresses;
        *.displayAddresses = parent.displayAddresses;
    submodules:
        interfaceTable: InterfaceTable;
}
```

However, it should also suggest (did you mean 'this.displayAddresses'?)

**To Reproduce**
Using INET 4.3 run a simulation of the following network
```js
import inet.networklayer.common.*;

module ProblematicNode
{
    parameters:
        @networkNode;
        bool displayAddresses;
        *.displayAddresses = displayAddresses;
    submodules:
        interfaceTable: InterfaceTable;
}

network SimpleNet
{
    parameters:
    	@display("bgb=522,282");
    submodules:
        problemNode: ProblematicNode{
            displayAddresses = false;
        }
}
```

**Comment by rhornig** [comment]
Evaluation comntext has changes since pre12. Now you should prefix with `parent.` or `this.` explictly.
