### ISSUE TITLE
I can't make Omnet++ 6.0 preview 12

### ISSUE THREAD

**Issue by edadilann** [omnetpp/omnetpp#895]
**Platform**
 - OMNeT++ version: 6.0 preview 12
 - OS: Ubuntu 20.04.3

**Describe the bug**
Hello, I did all the steps while installing for Omnet++ 6.0 Preview 12, but when I run the "make" command at the end, I get an error.

**Comment by edlongman** [comment]
Please copy and paste the error and what your `configure.user` file state is

**Comment by edadilann** [comment]
Makefile:61: Makefile.inc: No such file or directory
make: *** No rule to make target 'Makefile.inc'. Stop.

**Comment by edlongman** [comment]
Have you run ./configure ?

**Comment by edadilann** [comment]
Yes as it says in the readme file
-source setenv
-./configure
I don't get any errors when I run the commands. But when I type "make" as step 3, I get this error.

**Comment by edlongman** [comment]
Check the output of ./configure because this creates the Makefile.inc

Maybe post it here as that would be helpful.

**Comment by edadilann** [comment]
configure: Environment variables (PATH and PYTHONPATH) are correctly set.
configure: reading configure.user for your custom settings
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for clang... no
checking for icc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for clang++... no
checking for clang... no
checking for icpc... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for g++... g++
checking for c++14 support... yes
checking for ranlib... ranlib
checking whether LLD linker is available... no
checking whether g++ supports -fno-omit-frame-pointer... yes
checking whether g++ supports -glldb... no
checking whether g++ supports -ggdb3... yes
checking whether g++ supports -fstandalone-debug... no
checking whether g++ supports -fno-limit-debug-info... no
checking whether g++ supports -Wl,--no-as-needed... yes
checking whether g++ supports -Wl,--as-needed... yes
checking for swapcontext... yes
checking if shared libs need -fPIC... yes
checking for dlopen with CFLAGS="" LIBS=""... no
checking if --export-dynamic linker option is supported/needed... both
checking for flags needed to link with static libs containing simple modules... --whole-archive
configure: NOTE: Use the following syntax when linking with static libraries
configure: containing simple modules and other dynamically registered components:
configure:    g++ ... -Wl,--whole-archive <libs> -Wl,--no-whole-archive ...
checking whether linker supports -rpath... yes
checking for bison... bison -y
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking for make... make
checking for perl... perl
checking for swig... not found
checking for python3... python3
checking if all necessary Python modules are available... no
configure: error: Some Python modules required by the IDE were not found: numpy scipy pandas matplotlib posix_ipc

**Comment by edlongman** [comment]
The last line shows the error. It is missing some python modules

**Comment by 18mandy** [comment]
But how to resolve it?

**Comment by rhornig** [comment]
Follow the InstallGuide instructions by installing all python module requirements too.

**Comment by hatemTrabelsi** [comment]
this can help, 

sudo apt-get install libjpeg-dev

and then

python3 -m pip install --user scipy matplotlib posix_ipc
