### ISSUE TITLE
NED Visual editor cannot show warning symbol. Showing image not found placeholder instead

### ISSUE THREAD

**Issue by edlongman** [omnetpp/omnetpp#896]
**Platform**
 - OMNeT++ version: 6pre12
 - OS: Windows 10

**Describe the bug**
![image](https://user-images.githubusercontent.com/693456/134539126-1b5185b5-2b49-49ee-9152-a5efb533af18.png)
Warning symbol cannot be found and shown as question mark placeholder.

What I would expect (from 5.6): 
![image](https://user-images.githubusercontent.com/693456/134539670-03c17fd2-1a6e-459d-bb82-d0a5797c2d15.png)

**To Reproduce**
```
package inet.linklayer.ieee802154;

import inet.linklayer.contract.IWirelessInterface;
import inet.networklayer.common.NetworkInterface;
import inet.physicallayer.wireless.common.contract.packetlevel.IRadio;
module MisingSymbolModule extends NetworkInterface like IWirelessInterface
{
    submodules:
        radio: <default("Ieee802154NarrowbandScalarRadio")> like IRadio {
            parameters:
                @display("p=100,50");
            	transmitter.power = 0.003W;
        }
}
```

**Comment by edlongman** [comment]
I'm still getting this error and it's quite frustrating, any idea about a solution?

**Comment by avarga** [comment]
If you don't mind monkey patching, renaming `warn_tsk.png`  to `warning_tsk.png` in the `images/_internal/decorators/` directory inside `omnetpp-6.0/ide/plugins/org.omnetpp.common_6.0.0.220413-71d8fab425.jar` should fix it. Should be corrected in the next patch release.
