### ISSUE TITLE
No rule to make target

### ISSUE THREAD

**Issue by Mardok95** [omnetpp/omnetpp#897]
Hi, this is the console log when I try to build Inet 4.3.2 on Omnet++ 5.7 on my Mac Os Big Sur:

12:45:15 **** Incremental Build of configuration debug for project inet ****
make MODE=debug -j3 all 
*** CCACHE not detected - using precompiled headers
*** COMPILING with:
clang++ -c -std=c++14  -O0 -Wall -glldb -fstandalone-debug   -MMD -MP -MF .d    -isystem /Users/andreadimartino/Desktop/omnetpp-5.7/tools/macosx/include -Wno-deprecated-register -Wno-unused-function -fno-omit-frame-pointer  -DXMLPARSER=libxml -DPREFER_QTENV -DWITH_QTENV -DWITH_PARSIM -DWITH_NETBUILDER -DWITH_OSG -DWITH_OSGEARTH  -Wno-overloaded-virtual -include inet/common/precompiled_debug.h -DOMNETPPLIBS_IMPORT -DINET_EXPORT -I. -I/Users/andreadimartino/Desktop/omnetpp-5.7/include
*** LINKING with:
clang++ -shared  -o ../out/clang-debug/src/libINET_dbg.dylib  -Wl,-all_load   -loppenvir_dbg -loppsim_dbg -lstdc++    -Wl,-rpath,/Users/andreadimartino/Desktop/omnetpp-5.7/lib -Wl,-rpath,/Users/andreadimartino/Desktop/omnetpp-5.7/tools/macosx/lib -Wl,-rpath,.  -L/usr/lib -L/Users/andreadimartino/Desktop/omnetpp-5.7/tools/macosx/lib -F/Users/andreadimartino/Desktop/omnetpp-5.7/tools/macosx/lib -L/Users/andreadimartino/Desktop/omnetpp-5.7/lib 
Building...
make[1]: *** No rule to make target `../out/clang-debug/src/.last-copts', needed by `inet/opp_defines.h'.  Stop.
make: *** [all] Error 2
"make MODE=debug -j3 all" terminated with exit code 2. Build might be incomplete.

12:45:18 Build Failed. 2 errors, 0 warnings. (took 3s.182ms)

Any suggestion?

**Comment by harirRzi** [comment]
Hello. I have the same problem. Have you been able to solve the issue?

**Comment by Mardok95** [comment]
Hi, i'm not able to solve this. I changed simulator and used MATLAB.

Il mer 12 gen 2022, 20:28 harirRzi ***@***.***> ha scritto:

**Comment by rhornig** [comment]
INET 4.3 requires OMNeT++ 6.0. It will NOT work
