### ISSUE TITLE
Long file name problems

### ISSUE THREAD

**Issue by edlongman** [omnetpp/omnetpp#904]
**Platform**
 - OMNeT++ version: 6
 - OS: Windows 10

**Describe the bug**
OMNeT produces very long file names when doing parametric simulations as  it adds all the parameters into the file path like so 
`results/LongConfigNameHere-interfaceType=WirelessInterface,slotDuration=0.4,sendInterval=200,numNodes=50,parameter5=false, parameter6=true-#2.sca`

Windows has a default max path length of 260 - this means files over this length cannot be opened. But they are still written by opp_run. However running scavetool cannot open them. Giving the error:
`opp_scavetool: Cannot open 'results/LongConfigNameHere-interfaceType=WirelessInterface,slotDuration=0.4,sendInterval=200,numNodes=50,parameter5=false, parameter6=true-#2.sca' for read`

**The Problem**
Following the instructions here does not appear to fix since scavetool apparently converts it back to an old NT style name https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd

There may be a different fopen that allows opening of such long path names.

**Comment by avarga** [comment]
We are still looking a solution. In the meantime, one potential workaround is to manually configure shorter file names in omnetpp.ini. For example, instead of including all iteration variables, use just the run number, or a selected subset of the iteration variables (plus the run number to make them unique).

```
output-scalar-file = "${resultdir}/${configname}-${iterationvarsf}#${repetition}.sca"  # this is the default
output-scalar-file = "${resultdir}/${configname}-${runnumber}.sca"  # use just the run number in the file name
output-scalar-file = "${resultdir}/${configname}-iaMean=${iaMean}-run${runnumber}.sca"  # use an itervar and run number
```

**Comment by rhornig** [comment]
This is a file system issue we can't fix easily with a know workaround so I'm closing this. Also in recent Win10 versions there is a global switch that would allow long filenames on NTFS:

https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later
