### ISSUE TITLE
Error build SAMPLES on mac osx 

### ISSUE THREAD

**Issue by kevinyuan** [omnetpp/omnetpp#906]
**Platform**
 - OMNeT++ version: omnetpp-6.0pre13
 - OS: OSX 11.5.2 (20G95)
 
**Describe the bug**
The BASE targets compile succeeded, but SAMPLES failed.
Please see the following log message.

** Log **
...
Creating shared library: /Users/kevinyuan/works/omnetpp-6.0pre13/out/clang-release/src/qtenv/liboppqtenv.dylib
Copying to: /Users/kevinyuan/works/omnetpp-6.0pre13/lib/liboppqtenv.dylib
osgviewer.cc
cameramanipulators.cc
moc_osgviewer.cpp
moc_cameramanipulators.cpp
osg_m.cc
Creating shared library: /Users/kevinyuan/works/omnetpp-6.0pre13/out/clang-release/src/qtenv/osg/liboppqtenv-osg.dylib
Copying to: /Users/kevinyuan/works/omnetpp-6.0pre13/lib/liboppqtenv-osg.dylib
===== Compiling opp_run ====
Creating executable: /Users/kevinyuan/works/omnetpp-6.0pre13/out/clang-release/src/envir/opp_run
Copying to: /Users/kevinyuan/works/omnetpp-6.0pre13/bin/opp_run
Copying to: /Users/kevinyuan/works/omnetpp-6.0pre13/bin/opp_run_release
===== Compiling aloha ====
Creating executable: out/clang-release//aloha
ld: warning: ignoring file /Users/kevinyuan/works/omnetpp-6.0pre13/lib/liboppmain.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Makefile:93: out/clang-release//aloha] Error 1
make[1]: *** [Makefile:144: aloha] Error 2
make: *** [Makefile:35: allmodes] Error 2

**To Reproduce**
>source setenv
>./configure
>make

**Comment by kevinyuan** [comment]
Solution:
>brew uninstall binutils

Reference:
https://github.com/bitcoin/bitcoin/issues/20825

**Comment by rhornig** [comment]
Thanks for the followup. I will experiment with nix package manager to allow reproducible builds and avoid these mishaps in the future.
