### ISSUE TITLE
Using name() filter in result analysis leads to "filter expression invalid" error

### ISSUE THREAD

**Issue by schattenwantler** [omnetpp/omnetpp#908]
**Platform**
 - OMNeT++ version: 5.7
 - OS: Ubuntu 20.04

**Describe the bug**
When filtering by name in the result analysis, I get the error "Filter expression invalid, please fix it. Contents are not changed.".

![Error](https://user-images.githubusercontent.com/59311080/148100015-7dc59d28-7a9b-4b5a-9997-c1e10ad1ce0d.png)

**To Reproduce**
I opened an anf file for result analysis.
After that I dragged a result file (.vec) into the input files section.
Than I switched to the "browse data" tab at the bottom of the window.
As soon as I select a name to filter by I get an error popup saying: "Filter expression invalid, please fix it. Contents are not changed."
I tried many things and I found a workaround. When using the name() filter in the advanced filter input you still get the error. But as soon as you enclose the name you want to filter by in " " it works. (For example **name("abc")** instead of **name(abc)** )

![sol](https://user-images.githubusercontent.com/59311080/148100355-3d2c91c1-2c0f-415b-8fa3-53f6689c803d.png)
works

This seems to only happen with vectors not with scalar values.

**Comment by edlongman** [comment]
Does the same problem occur with variables with no special char i.e. `=` in their name?

**Comment by schattenwantler** [comment]
You are right. I just tested the same input without the "=" and got no error.
I don't know why but before i reinstalled my workspace with an older version of omnetpp it was no problem to do that.
Is there an solution to use "=" in the filer expression or do i have to rename the statistic names?

**Comment by rhornig** [comment]
The expression parser cannot parse names if they are not quoted and contain non alphanumeric chars. Quote your names properly if spacial chars are included.
