### ISSUE TITLE
OMNet++ 5.7 Projet Explorer cannot display items

### ISSUE THREAD

**Issue by HandSonic** [omnetpp/omnetpp#909]
**Platform**
 - OMNeT++ version: OMNet++ 5.7 
 - OS: Windows 10 21H1

**Describe the bug**
In this release, the project cannot be displayed correctly, whether the new project or import project or re-open the Projet Explorer , is displayed correctly.
For example
![image](https://user-images.githubusercontent.com/8078023/148170463-95d1de87-2a4f-4d98-b5f6-6c6e1ada48e9.png)

So I tried the latest 6.0pre15 version and the last version 5.6.2, and the Projet Explorer in these two versions can be displayed.

**Comment by rhornig** [comment]
Is this still happening after a system restart? This looks like some kind of intermittent exception .
