### ISSUE TITLE
Built-in histogram x-axis limits set in the chart properties dialog leads to error

### ISSUE THREAD

**Issue by adamgeorge309** [omnetpp/omnetpp#922]
**Platform**
 - OMNeT++ version: 6.0
 - OS: Ubuntu 22.04

Here are screenshots of the bug:
![unnamed](https://user-images.githubusercontent.com/17473608/167830491-6aefc177-8450-4671-87f8-4e7f6cb4e044.png)
![unnamed](https://user-images.githubusercontent.com/17473608/167830528-0399c538-85d1-4d71-a0d1-6876c307a96e.png)

**Comment by torokati44** [comment]
Fixed by https://github.com/omnetpp/omnetpp/commit/b5a68e7d87e9302bae26dfa1139ca3b3a3423d75.
