### ISSUE TITLE
Question about one library EtherEncap.h

### ISSUE THREAD

**Issue by NikolaosGian** [omnetpp/omnetpp#927]
Hello everyone,
I just install new version of OMNeT++6.0 but the library with name ` EtherEncap.h ` dosen't exist.
Before i was using  `OMNeT++5.0` with ` iNET-3.2.4 ` and now i using `iNET: 4.3.9(stable)`.
Someone know where the library get included to other file ?

**Comment by rhornig** [comment]
Unrelated to the core OMNET simulator.
