### ISSUE TITLE
python interface

### ISSUE THREAD

**Issue by wggegshjg** [omnetpp/omnetpp#930]
At one time, if I want to use python to process real-time simulation data and return the result to omnet++
what should i do？thanks，i want to find the python interface。

**Comment by wggegshjg** [comment]
How to write python code in omnet++？

**Comment by avarga** [comment]
Try using the [cppyy](https://cppyy.readthedocs.io/en/latest/) package. The our team is also working on OMNeT++-Python intergration, but we don't have anything to release yet.
