### ISSUE TITLE
Filter button doesn't work or giving out error.

### ISSUE THREAD

**Issue by HunterX-X** [omnetpp/omnetpp#932]
I am totally new to OMNET and I am using v6.0, So I stumbled on this issue while doing an elog on OMNET, When I tried to click on the Filter option it gives me a java run time error or it doesn't work. Can anyone help me to figure this out?

![image](https://user-images.githubusercontent.com/74244462/180625647-fb3264db-fb34-4124-b0dc-86fcb3dd1aa9.png)

**Comment by albymor** [comment]
Same here
![image](https://user-images.githubusercontent.com/19717991/181554112-e5bbbed4-4826-418c-86a3-f211b5d46331.png)


[omnet_info.txt](https://github.com/omnetpp/omnetpp/files/9212176/omnet_info.txt)

**Comment by avarga** [comment]
Confirmed on Ubuntu. We are looking into it.

**Comment by rhornig** [comment]
Fixed in fb11f604704afe3e2a6f822b444d5c0a6c15f99c
