### ISSUE TITLE
Makefile:67: Makefile.inc: No such file or directory on Raspberry Pi4

### ISSUE THREAD

**Issue by B0GDAN** [omnetpp/omnetpp#942]
**Platform**
 - OMNeT++ version: 6.0.1
 - OS: Linux raspberrypi 5.15.61-v8+ 64bit (Debian GNU/Linux 11 (bullseye)) 

**Describe the bug**
Has anybody tried to install omnetpp-6.0.1-linux-aarch64 ?
I've set up Raspbian x64 on my Pi4 and so far I'm not able to run the make command

So far I've installed this:
sudo apt-get install build-essential clang lld gdb bison flex perl python3 python3-pip qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libqt5opengl5-dev libxml2-dev zlib1g-dev doxygen graphviz libwebkit2gtk-4.0-37

python3 -m pip install --user --upgrade numpy pandas matplotlib scipy seaborn posix_ipc

sudo apt-get install openscenegraph-plugin-osgearth libosgearth-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package openscenegraph-plugin-osgearth
E: Unable to locate package libosgearth-dev

sudo apt-get install mpi-default-dev

./configure gives me this

configure: Environment variables (PATH and PYTHONPATH) are correctly set.
configure: Reading configure.user for your custom settings.
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking for clang... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking for clang++... clang++
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking for clang++... clang++
checking for c++14 support... yes
checking for ranlib... ranlib
checking whether LLD linker is available... yes
checking whether clang++ supports -fno-omit-frame-pointer... yes
checking whether clang++ supports -glldb... yes
checking whether clang++ supports -fstandalone-debug... yes
checking whether clang++ supports -Wl,--no-as-needed... yes
checking whether clang++ supports -Wl,--as-needed... yes
checking for swapcontext... yes
checking if shared libs need -fPIC... yes
checking for dlopen with CFLAGS="" LIBS=""... no
checking if --export-dynamic linker option is supported/needed... both
checking for flags needed to link with static libs containing simple modules... --whole-archive
configure: NOTE: Use the following syntax when linking with static libraries
configure: containing simple modules and other dynamically registered components:
configure:    clang++ ... -Wl,--whole-archive <libs> -Wl,--no-whole-archive ...
checking whether linker supports -rpath... yes
checking for bison... bison -y
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking for make... make
checking for perl... perl
checking for swig... not found
checking for python3... python3
checking if all necessary Python modules are available... yes
checking for math with CFLAGS=" -fPIC" LIBS=""... yes
checking for standard C++ lib with CFLAGS=" -fPIC" LIBS="-lstdc++"... yes
checking for dlopen with CFLAGS=" -fPIC" LIBS=""... no
checking for dlopen with CFLAGS=" -fPIC" LIBS="-ldl"... yes
checking for qmake-qt5... no
checking for qmake5... no
checking for qmake... /usr/bin/qmake
checking for moc-qt5... no
checking for moc5... no
checking for moc... /usr/lib/qt5/bin/moc
checking for uic-qt5... no
checking for uic5... no
checking for uic... /usr/lib/qt5/bin/uic
checking for rcc-qt5... no
checking for rcc5... no
checking for rcc... /usr/lib/qt5/bin/rcc
checking for Qt5 with CFLAGS="  -fPIC -isystem /usr/include/aarch64-linux-gnu/qt5  -fPIC -isystem /usr/include/aarch64-linux-gnu/qt5" LIBS="-lQt5Gui -lQt5Core -lQt5Widgets -lQt5PrintSupport -lQt5OpenGL -L/usr/lib/aarch64-linux-gnu"... yes
checking for OpenSceneGraph with CFLAGS=" -fPIC  -Wno-deprecated-register -Wno-unused-function -fno-omit-frame-pointer  " LIBS=" -Wl,--export-dynamic  -losg -losgDB -losgGA -losgViewer -losgUtil -lOpenThreads"... no
configure: error: Cannot find OpenSceneGraph 3.2 or later - 3D view in Qtenv will not be available. Set WITH_OSG=no in configure.user to disable this feature or install the development package for OpenSceneGraph.

but make doesn't work

Makefile:67: Makefile.inc: No such file or directory
make: *** No rule to make target 'Makefile.inc'.  Stop.

Any clues?
Thanks

**Comment by torokati44** [comment]
> Any clues?

The clues are right there in the message you pasted:

```
E: Unable to locate package openscenegraph-plugin-osgearth
E: Unable to locate package libosgearth-dev
```

```
configure: error: Cannot find OpenSceneGraph 3.2 or later - 3D view in Qtenv will not be available. Set WITH_OSG=no in configure.user to disable this feature or install the development package for OpenSceneGraph.
```

The distribution you are running does not have the osgEarth packages necessary for this feature.
