### ISSUE TITLE
videostreaming emulation showcase

### ISSUE THREAD

**Issue by aimanakkad** [omnetpp/omnetpp#948]
Could you please help in solving this issue!
Platform:
INET framework 4.4.1
Omnet++ 6.0.1 under
Ubuntu 20.04.5 LTS focal
The error:
<!> Error: Cannot assign parameter 'config': xml(): Parse error: Syntax error at string-content:1 -- at /home/aiman/omnetpp-6.0.1/samples/inet/showcases/emulation/videostreaming/omnetpp.ini:21 -- in module (inet::Ipv4NatTable) VideoStreamingShowcase.router.ipv4.natTable (id=175), during network setup

**Comment by ZoltanBojthe** [comment]
This is an INET issue, fixed in inet: https://github.com/inet-framework/inet/commit/8bf773a0d56c466e9bb1f42b4dce6ff8eef0d9e9

**Comment by aimanakkad** [comment]
Thank you! But again later after solving the issue below, I started getting it again.
Could you please tell me how to get rid of this error?

OMNeT++ Discrete Event Simulation  (C) 1992-2022 Andras Varga, OpenSim Ltd.
Version: 6.0.1, build: 220831-e4f07d04b8, edition: Academic Public License -- NOT FOR COMMERCIAL USE
See the license for distribution terms and warranty disclaimer


<!> Error: Cannot load library '../../../src//libINET.so': ../../../src//libINET.so: cannot open shared object file: No such file or directory

End.
Starting...

$ cd /home/aiman/omnetpp-6.0.1/samples/inet/showcases/emulation/videostreaming
$ opp_run -m -n ../../../examples:../..:../../../src:../../../tests/validation:../../../tests/networks:../../../tutorials -x inet.common.selfdoc;inet.linklayer.configurator.gatescheduling.z3;inet.showcases.visualizer.osg;inet.transportlayer.tcp_lwip;inet.visualizer.osg;inet.examples.voipstream --image-path=../../../images -l ../../../src/INET omnetpp.ini


Simulation terminated with exit code: 1
Working directory: /home/aiman/omnetpp-6.0.1/samples/inet/showcases/emulation/videostreaming
Command line: opp_run -m -n ../../../examples:../..:../../../src:../../../tests/validation:../../../tests/networks:../../../tutorials -x inet.common.selfdoc;inet.linklayer.configurator.gatescheduling.z3;inet.showcases.visualizer.osg;inet.transportlayer.tcp_lwip;inet.visualizer.osg;inet.examples.voipstream --image-path=../../../images -l ../../../src/INET omnetpp.ini

Environment variables:
PATH=/home/aiman/omnetpp-6.0.1/bin::/home/aiman/omnetpp-6.0.1/bin:/home/aiman/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/aiman/omnetpp-6.0.1/bin:/home/aiman/omnetpp-6.0.1/samples/inet/bin
LD_LIBRARY_PATH=/home/aiman/omnetpp-6.0.1/lib::/home/aiman/omnetpp-6.0.1/samples/inet/src:
OMNETPP_RELEASE=omnetpp-6.0.1
OMNETPP_IMAGE_PATH=/home/aiman/omnetpp-6.0.1/images
