### ISSUE TITLE
OMNET++ 6.0.1 INET 4.4 crashes if simulation is closed during message animation

### ISSUE THREAD

**Issue by amrcg** [omnetpp/omnetpp#949]
Hello,

I have detected this with several simulations. In order to reproduce the problem, do the follwing, for example:

1) Run the inet4.4/examples/wireless/wiredandwirelesshostswithap/ example (I did it in debug mode, and don't know if the same is true for release mode).
2) Run until 20s.
3) "Run with full animation" until you begin to see data messages being transmitted. Pause immediately.
4) Close the simulation canvas on the top-right corner.

The simulation will crash with a "Problem Occurred" message. If running under the debug, the stack is like the one in attachment.

I'm running OMNET++ in Windows 10.
[crash.pdf](https://github.com/omnetpp/omnetpp/files/9809406/crash.pdf)

Regards,
António

**Comment by torokati44** [comment]
This got fixed by 0870dd45485aa511ac7af10e665b09491881e60c.
