### ISSUE TITLE
Videostreamin showcase

### ISSUE THREAD

**Issue by aimanakkad** [omnetpp/omnetpp#952]
Hello! on
 - OMNeT++ 6.0.1
 - Inet 4.4.1
 - Ubuntu 20.04]
I get
Class "inet::ExtInterface" not found -- perhaps its code was not linked in, or the class wasn't registered with Register_Class(), or in the case of modules and channels, with Define_Module()/Define_Channel() -- in module (inet::NodeBase) VideoStreamingShowcase.host1 (id=7), during network setup
could you please help me in solving this?

**Comment by aimanakkad** [comment]
now I am getting: 
Class "inet::visualizer::SceneOsgVisualizer" not found -- perhaps its code was not linked in, or the class wasn't registered with Register_Class(), or in the case of modules and channels, with Define_Module()/Define_Channel() -- in module (omnetpp::cModule) VideoStreamingShowcase.visualizer.osgVisualizer (id=18), during network setup

**Comment by aimanakkad** [comment]
Hello! on

    OMNeT++ 6.0.1
    Inet 4.4.1
    Ubuntu 20.04]
    I get
    Class "inet::ExtInterface" not found -- perhaps its code was not linked in, or the class wasn't registered with Register_Class(), or in the case of modules and channels, with Define_Module()/Define_Channel() -- in module (inet::NodeBase) VideoStreamingShowcase.host1 (id=7), during network setup
    could you please help me in solving this?
now I am getting:
Class "inet::visualizer::SceneOsgVisualizer" not found -- perhaps its code was not linked in, or the class wasn't registered with Register_Class(), or in the case of modules and channels, with Define_Module()/Define_Channel() -- in module (omnetpp::cModule) VideoStreamingShowcase.visualizer.osgVisualizer (id=18), during network setup

**Comment by aimanakkad** [comment]
another error:
Gate VideoStreamingShowcase.host1.eth[0].mac.upperLayerIn is not connected to a module of type queueing::IPacketQueue -- in module (inet::EthernetMac) VideoStreamingShowcase.host1.eth[0].mac (id=206), during network initialization

**Comment by rhornig** [comment]
This is INET specific issue. Please use the INET Framework issue tracker for this.
