### ISSUE TITLE
Interference simulation in OMNET++ and channel capacity measurement

### ISSUE THREAD

**Issue by ssooffiiaannee** [omnetpp/omnetpp#955]
I would like to simulate interference in V2V communication using OMNET++, and measure channel capacity in the presence of interference. 
Let's forget mobility and suppose we are dealing with static nodes. I want to broadcast data between a group of communicating nodes sharing the same bandwidth (5.9 GHz, 802.11p) and measure the rate at which I can share data (while increasing the number of nodes for example).

**Comment by rhornig** [comment]
This is not a bug report and not releated to omnet either.
