### ISSUE TITLE
Error including additional API library

### ISSUE THREAD

**Issue by juansebastiani2cat** [omnetpp/omnetpp#956]
Hello. I need to make a simulation with an API Rest and I thought of including a C++ library (called CPR) that helps the management of the API methods. I wanted to test it in a really simple environment to check that everything worked smoothly. 

I'm using Omnet++ Version: 6.0, Build id: 220413-71d8fab425, and performing the tests using the TicToc example (tictoc3), where I have included this lines of code: 

`#include <cpr/cpr.h>`

```
void Txc3::handleMessage(cMessage *msg)
{
    cpr::Response r = cpr::Get(cpr::Url{"https://dog.ceo/api/breeds/list/all"});
    // Increment counter and check value.
    counter--;
    if (counter == 0) {
        // If counter is zero, delete message. If you run the model, you'll
        // find that the simulation will stop at this point with the message
        // "no more events".
        EV << getName() << "'s counter reached zero, deleting message\n";
        delete msg;
    }
    else {
        EV << getName() << "'s counter is " << counter << ", sending back message\n";
        send(msg, "out");
    }
}
```
I included the following into the makefrag file:

> 
> INCLUDE_PATH += -I/usr/lib
> LIBS += -lcpr
> 
> 

I checked the usr/lib directory and it contains the cpr library files (I guess...):
 
> libcpr.so
> libcpr.so.1
> libcpr.so.1.8.1

The tictoc3 project builds alright and when I start the simulation everything seems ok. Then, Omnet++ launches the new simulation window but when I press the play button it suddenly closes the window and says the following: 

```
Simulation terminated with exit code: 8b
Working directory: /omnetpp-6.0/samples/tictoc
Command line: tictoc -m -n . omnetpp.ini

```
> libcpr.so
> libcpr.so.1
> libcpr.so.1.8.1

The tictoc3 project builds alright and when I start the simulation everything seems ok. Omnet++ launches the simulation window but when I press the play button it suddenly closes the window and says the following: 

```
Simulation terminated with exit code: 8b
Working directory: /home/i2cat/Downloads/omnetpp-6.0/samples/tictoc
Command line: tictoc -m -n . omnetpp.ini

```
Could you help me with this please? Is there any other way to include REST API into OMNET++ ?? Thanks a lot for your answer.

**Comment by rhornig** [comment]
8b error code is an access violation signal, meaning that your model code has crashed. This is not an OMNeT++ issue. You should run your model in debugger and see where it crashes.
