### ISSUE TITLE
Ex1

### ISSUE THREAD

**Issue by Kazemrade** [omnetpp/omnetpp#960]
#include <omnetpp.h>
#include <cstdlib>

using namespace omnetpp;

class PoissonGenerator : public cSimpleModule
{
  protected:
    virtual void initialize() override;
    virtual void handleMessage(cMessage *msg) override;
};

Define_Module(PoissonGenerator);

void PoissonGenerator::initialize()
{
    cStdDev poisson;
    poisson.setSeed((int)simTime().dbl());  // set the seed for the random number generator
    poisson.setPoisson(5);  // set the mean value of the Poisson distribution

    // generate and print 1000 random numbers
    for (int i = 0; i < 1000; i++) {
        double number = poisson();
        EV << "Random number: " << number << endl;
    }
}

void PoissonGenerator::handleMessage(cMessage *msg)
{
    // the generator doesn't receive any messages, so this function should never be called
    throw cRuntimeError("Invalid call to handleMessage");
}

**Comment by Kazemrade** [comment]
1

**Comment by avarga** [comment]
Garbage. E.g. does not state what is the bug, cStdDev does not have setSeed() or setPoisson(), makes no sense to use simtime as seed, etc.

**Comment by avarga** [comment]
Closing
