### ISSUE TITLE
OMNeT++ IDE not useable on WSL2

### ISSUE THREAD

**Issue by mathys2000** [omnetpp/omnetpp#961]
Installation of OMNeT++ 6.0.1 (for Linux from https://omnetpp.org/download/) in WSL2 (Major 10, minor  0, build 22000, revision 1281) on Windows 11, running Ubuntu 22.04.1, works fine, but when running the omnetpp command the text panes in the IDE do not render correctly, see the screen snapshot below.
![image](https://user-images.githubusercontent.com/12535130/211628565-b5c27de2-d8ff-410d-a1c7-a11b14a11435.png)
In particular, the tree view of the files in the workspace in the Project Explorer is unreadable, thus making the IDE unuseable.
I get the same results under Ubuntu 20.04.5 in WSL2 and there is no difference when I use VcXsrv instead of WSLg.exe as the GUI interface. When I install the same OMNeT++ 6.0.1 download in VirtualBox 7.0.4 the IDE renders as expected, see the screen snapshot below.
![image](https://user-images.githubusercontent.com/12535130/211629893-21915179-aa08-49d7-853a-4f5593996e72.png)
The issue does not seem to be related to either the version of Ubuntu used nor the X11 server (wayland or VcServ) used in WSL2, it must be part of the Eclipse IDE code. Any insights would be helpful. Thanks!

**Comment by rhornig** [comment]
You should force the x11 backend for the GTK widgets (that are used by SWT in Eclipse):

`export GDK_BACKEND=x11`

**Comment by rhornig** [comment]
Workaround commit: d180441b1522490631ce5172bd20732ab00b928a

**Comment by mathys2000** [comment]
That worked like a charm. Thank you!
