### ISSUE TITLE
Error importing project Omnet++ 5.6.2.

### ISSUE THREAD

**Issue by MartinaBarbiFivecomm** [omnetpp/omnetpp#967]
Good afternoon,

I'm experiencing an import error when trying to open a directory after simulating with Omnet/Qtenv. In attached the error I'm getting.
I do not know why is this happening. Any hint on this?

 
![omnet_Importing_Error](https://user-images.githubusercontent.com/102963213/228876174-07e69628-4d00-44bc-9117-e2d8aa58ae87.png)

Thank you in advance for your help,

Martina

**Comment by rhornig** [comment]
It is not possible to diagnose this issue without further info. Maybe opening the "details" button would help, but also the `<workspace>/.metadata/.log` file contains important info about the failure. Please reopen if this is still an issue and can provide additional info.
