### ISSUE TITLE
Strange import errors & wrong instruction - veins-5.2

### ISSUE THREAD

**Issue by MoienBowen** [omnetpp/omnetpp#970]
**Platform**
 - OMNeT++ version: 6.0
 - OS: macOS 13.3.1

**Describe the bug**
Once I finish installing Simu5G (via Omnet++ - Help - Install Simulation Models... - Simu5G 1.2.2 + Inet 4.5) and downloading veins 5.2 from its website, I tried to follow the instruction: [http://www.simu5g.org/veins_integration.html](http://www.simu5g.org/veins_integration.html) (starting from the step: Import Veins into your workspace using the IDE).
1. There is a string error of the import
2. The instruction is not complete

**To Reproduce**
1. Regarding the first error, if I follow the instruction: File - Import... - General - Existing Projects into Workspace - Select root directory, there the veins_inet will never show up in the Project Explorer at the left side. Then it is hard to locate the error. You can try to import the project via: File - Import... - General - Existing Projects into Workspace - Select archive file - select veins-5.2.zip, even the error is still there, at least you can see veins_inet on the left side.
2. About the second point, which is related to the error mentioned above, you did not mention that we need to link inet in your instruction. To eliminate the error, do: right click veins_inet in Project Explorer - Properties - Project References - select inet4.x (I use inet4.5) while keeping inet and veins. Then you can continue the following steps in the instruction.

By the way, your OMNeT++ 6.0.1 has serious issue, I cannot even properly install inet4.5 in it, thus I have to use 6.0...

Good luck.

**Comment by rhornig** [comment]
This report should be filed in the veins bugtracker. It's not OMNeT++ releated.
