### ISSUE TITLE
intuniform() has broken bounds check in OMNeT 6.0.1

### ISSUE THREAD

**Issue by roland-bless** [omnetpp/omnetpp#972]
We need to generate 32bit random IDs across the whole range, i.e., 0..2^32-1.
In OMNeT++ 5.7 
intuniform(rng,0,0xFFFFFFFF); simply worked, but with OMNeT 6.0.1 we got an error that
a > b and b was -1.  But when using
intuniform(rng, std::numeric_limits<int32_t>::min(),std::numeric_limits<int32_t>::max());
the intuniform() function wrongly throws an exception, although the numbers a,b are within the 32-bit range:
<!> intuniform(): Wrong parameters a=-2147483648 and b=2147483647: Interval is greater than RNG range 

This should not happen, as b-a+1 is exactly 2^32 which is the range of a 32-bit integer, 
but the check is made against 2^32-1, so
obviously the comparison in distrib.cc is wrong:
    int64_t range = (int64_t)b - (int64_t)a + 1;
    if (range > rng->intRandMax())
        throw cRuntimeError("intuniform(): Wrong parameters a=%d and b=%d: Interval is greater than RNG range", a, b); // could work around but nobody will need it
If you want to do the comparison in the uint64_t domain, the code should then use
uint64_t max_range=rng->intRandMax()+1; 
and compare range > max_range
Consequently, intuniformexcl() must be fixed, too.

**Comment by avarga** [comment]
Fixed by changing the comparison to:

    int64_t rngRange = (int64_t)rng->intRandMax() + 1;
    if (range > rngRange)
         throw cRuntimeError(...)
