### ISSUE TITLE
lldbmi2's rpath maybe set wrongly

### ISSUE THREAD

**Issue by owlright** [omnetpp/omnetpp#974]
**Platform**
 - OMNeT++ version: 6.0.1
 - OS: macOS 10.15.7

**Describe the bug**
It says "xcode-select --install" in the install manual.pdf, but this is not enough, Xcode has to be installed.

I use otool to find out the @rpath in lldbmi2 is hard coded as /Applications/Xcode.app/Contents/SharedFrameworks. Since CommandTool and Xcode both have LLDB, are they both required? or @rpath should be referred to /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework?

**To Reproduce**
Just run any debug simulation in samples.

**Comment by rhornig** [comment]
The lldbmi2 executable must be updated in the tools folder for both the aarch64 and x86_64 distro.

**Comment by rhornig** [comment]
Recompiled the lldbmi2 executable as an universal binary (x86_64 and aarch64). Added both the xcode LLDB framework and the CommandlineTool's LLDB framework to the rpath, so either of them is present, it can be used (prefers the xcdde framework and fals back to the command line tool). This might be added to a later omnet version (probably 6.1)
