### ISSUE TITLE
Simulation terminated with exit code: c0000139

### ISSUE THREAD

**Issue by asd0323a** [omnetpp/omnetpp#975]
**Platform**
 - OMNeT++ version: 6.0.1
 - OS: Windows10

Simulation terminated with exit code: c0000139
Working directory: C:/Users/UserX/src/omnetpp-6.0.1/samples/wpcn-omnet
Command line: wpcn-omnet.exe -m -u Qtenv -n . pCN.ini

Environment variables:
PATH=C:\Users\UserX\src\omnetpp-6.0.1\bin;C:\Users\UserX\src\omnetpp-6.0.1\tools\win32.x86_64\opt\mingw64\bin;C:\Users\UserX\src\omnetpp-6.0.1\tools\win32.x86_64\usr\bin;C:\Users\UserX\src\omnetpp-6.0.1\tools\win32.x86_64\mingw64\bin;;C:/Users/UserX/src/omnetpp-6.0.1/ide//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.stripped.win32.x86_64_17.0.4.v20220805-1047/jre/bin/server;C:/Users/UserX/src/omnetpp-6.0.1/ide//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.stripped.win32.x86_64_17.0.4.v20220805-1047/jre/bin;C:\Users\UserX\src\omnetpp-6.0.1\bin;C:\Users\UserX\src\omnetpp-6.0.1\tools\win32.x86_64\opt\mingw64\bin;C:\Users\UserX\src\omnetpp-6.0.1\tools\win32.x86_64\mingw64\bin;C:\Users\UserX\src\omnetpp-6.0.1\tools\win32.x86_64\usr\local\bin;C:\Users\UserX\src\omnetpp-6.0.1\tools\win32.x86_64\usr\bin;C:\Users\UserX\src\omnetpp-6.0.1\tools\win32.x86_64\usr\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\UserX\src\omnetpp-6.0.1\tools\win32.x86_64\usr\bin\site_perl;C:\Users\UserX\src\omnetpp-6.0.1\tools\win32.x86_64\usr\bin\vendor_perl;C:\Users\UserX\src\omnetpp-6.0.1\tools\win32.x86_64\usr\bin\core_perl;C:\Users\UserX\src\omnetpp-6.0.1;
OMNETPP_RELEASE=C:\Users\UserX\src\omnetpp-6.0.1
OMNETPP_IMAGE_PATH=C:\Users\UserX\src\omnetpp-6.0.1\images

![微信图片_20230510231329](https://github.com/omnetpp/omnetpp/assets/75878409/d3d5c332-bc66-4b93-9b18-6f6d1088e61a)

I am completely unaware of this exit code and would appreciate it if someone could tell me what it means.

**Comment by rhornig** [comment]
This is a memory access fault in the model code. You should run your simulation in a debugger and it will show you the point in the stack trace where the actual error happened in your code.
