### ISSUE TITLE
configure: error: Some Python modules required by the IDE were not found: posix_ipc

### ISSUE THREAD

**Issue by mbalalzade** [omnetpp/omnetpp#985]
hello 
i want to install omnetpp but aftre run ./configure it show me this err:
***configure: error: Some Python modules required by the IDE were not found: posix_ipc****
can any body help me please?

**Comment by rhornig** [comment]
As the installation manual suggest you will need several python modules installed (inlcuding the posix_ipc one) to run the IDE:

`python3 -m pip install --user --upgrade numpy pandas matplotlib scipy seaborn posix_ipc`

It's best to install these using pip. Certain distros has dropped `posix_ipc` from the system packages, so you cannot install that using the system package manager.
