### ISSUE TITLE
Cannot launch IDE

### ISSUE THREAD

**Issue by Caillassage** [omnetpp/omnetpp#994]
**Platform**
- OMNeT++ version : omnetpp-6.1.0pre1
- OS : Ubuntu 22.04.2 LTS

**Describe the bug**
After cloning the repository and executing the command `omnetpp`, I can't launch the IDE and an error message drops : `The OMNeT++ IDE is not installed!`. I can still launch simulations in the command line, but it's annoying to program without the IDE.

**To reproduce**
1. Clone the project
2. Install the prerequisite packages (see the [Installation Guide](https://doc.omnetpp.org/omnetpp/InstallGuide.pdf))
3. `source setenv` & `omnetpp`
4. You will see the same error

**Comment by torokati44** [comment]
You can build the IDE with `make ide -B`.
Due to the complicated build setup, this requires a running Docker daemon to do the actual build process in a container.
When it's done, you should be able to run the IDE from the cloned repo just fine.
